// Code generated by enumgen from character_classes.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// CharacterClassType is a int8-wide identifier. The zero-cost conversion CharacterClassType(x) is
// intentional: the underlying value is the wire value.
type CharacterClassType int8

const (
	CharacterClassTypeUnknown    CharacterClassType = -1
	CharacterClassTypeWarrior    CharacterClassType = 0
	CharacterClassTypeHashashin  CharacterClassType = 1
	CharacterClassTypeSage       CharacterClassType = 2
	CharacterClassTypeWukong     CharacterClassType = 3
	CharacterClassTypeRanger     CharacterClassType = 4
	CharacterClassTypeGuardian   CharacterClassType = 5
	CharacterClassTypeScholar    CharacterClassType = 6
	CharacterClassTypeDrakania   CharacterClassType = 7
	CharacterClassTypeSorceress  CharacterClassType = 8
	CharacterClassTypeNova       CharacterClassType = 9
	CharacterClassTypeCorsair    CharacterClassType = 10
	CharacterClassTypeLahn       CharacterClassType = 11
	CharacterClassTypeBerserker  CharacterClassType = 12
	CharacterClassTypeReserved13 CharacterClassType = 13
	CharacterClassTypeReserved14 CharacterClassType = 14
	CharacterClassTypeMaegu      CharacterClassType = 15
	CharacterClassTypeTamer      CharacterClassType = 16
	CharacterClassTypeShai       CharacterClassType = 17
	CharacterClassTypeReserved18 CharacterClassType = 18
	CharacterClassTypeStriker    CharacterClassType = 19
	CharacterClassTypeMusa       CharacterClassType = 20
	CharacterClassTypeMaehwa     CharacterClassType = 21
	CharacterClassTypeReserved22 CharacterClassType = 22
	CharacterClassTypeMystic     CharacterClassType = 23
	CharacterClassTypeValkyrie   CharacterClassType = 24
	CharacterClassTypeKunoichi   CharacterClassType = 25
	CharacterClassTypeNinja      CharacterClassType = 26
	CharacterClassTypeDarkKnight CharacterClassType = 27
	CharacterClassTypeWizard     CharacterClassType = 28
	CharacterClassTypeArcher     CharacterClassType = 29
	CharacterClassTypeWoosa      CharacterClassType = 30
	CharacterClassTypeWitch      CharacterClassType = 31
	CharacterClassTypeSeraph     CharacterClassType = 32
	CharacterClassTypeDosa       CharacterClassType = 33
	CharacterClassTypeDeadeye    CharacterClassType = 34
	CharacterClassTypeReserved35 CharacterClassType = 35
	CharacterClassTypeReserved36 CharacterClassType = 36
	CharacterClassTypeMAX        CharacterClassType = 37
)

type CharacterClassTypeContainer struct {
	Unknown    CharacterClassType
	Warrior    CharacterClassType
	Hashashin  CharacterClassType
	Sage       CharacterClassType
	Wukong     CharacterClassType
	Ranger     CharacterClassType
	Guardian   CharacterClassType
	Scholar    CharacterClassType
	Drakania   CharacterClassType
	Sorceress  CharacterClassType
	Nova       CharacterClassType
	Corsair    CharacterClassType
	Lahn       CharacterClassType
	Berserker  CharacterClassType
	Reserved13 CharacterClassType
	Reserved14 CharacterClassType
	Maegu      CharacterClassType
	Tamer      CharacterClassType
	Shai       CharacterClassType
	Reserved18 CharacterClassType
	Striker    CharacterClassType
	Musa       CharacterClassType
	Maehwa     CharacterClassType
	Reserved22 CharacterClassType
	Mystic     CharacterClassType
	Valkyrie   CharacterClassType
	Kunoichi   CharacterClassType
	Ninja      CharacterClassType
	DarkKnight CharacterClassType
	Wizard     CharacterClassType
	Archer     CharacterClassType
	Woosa      CharacterClassType
	Witch      CharacterClassType
	Seraph     CharacterClassType
	Dosa       CharacterClassType
	Deadeye    CharacterClassType
	Reserved35 CharacterClassType
	Reserved36 CharacterClassType
}

// CharacterClassTypes is the entry point for the CharacterClassType enum.
var CharacterClassTypes = CharacterClassTypeContainer{
	Unknown:    CharacterClassTypeUnknown,
	Warrior:    CharacterClassTypeWarrior,
	Hashashin:  CharacterClassTypeHashashin,
	Sage:       CharacterClassTypeSage,
	Wukong:     CharacterClassTypeWukong,
	Ranger:     CharacterClassTypeRanger,
	Guardian:   CharacterClassTypeGuardian,
	Scholar:    CharacterClassTypeScholar,
	Drakania:   CharacterClassTypeDrakania,
	Sorceress:  CharacterClassTypeSorceress,
	Nova:       CharacterClassTypeNova,
	Corsair:    CharacterClassTypeCorsair,
	Lahn:       CharacterClassTypeLahn,
	Berserker:  CharacterClassTypeBerserker,
	Reserved13: CharacterClassTypeReserved13,
	Reserved14: CharacterClassTypeReserved14,
	Maegu:      CharacterClassTypeMaegu,
	Tamer:      CharacterClassTypeTamer,
	Shai:       CharacterClassTypeShai,
	Reserved18: CharacterClassTypeReserved18,
	Striker:    CharacterClassTypeStriker,
	Musa:       CharacterClassTypeMusa,
	Maehwa:     CharacterClassTypeMaehwa,
	Reserved22: CharacterClassTypeReserved22,
	Mystic:     CharacterClassTypeMystic,
	Valkyrie:   CharacterClassTypeValkyrie,
	Kunoichi:   CharacterClassTypeKunoichi,
	Ninja:      CharacterClassTypeNinja,
	DarkKnight: CharacterClassTypeDarkKnight,
	Wizard:     CharacterClassTypeWizard,
	Archer:     CharacterClassTypeArcher,
	Woosa:      CharacterClassTypeWoosa,
	Witch:      CharacterClassTypeWitch,
	Seraph:     CharacterClassTypeSeraph,
	Dosa:       CharacterClassTypeDosa,
	Deadeye:    CharacterClassTypeDeadeye,
	Reserved35: CharacterClassTypeReserved35,
	Reserved36: CharacterClassTypeReserved36,
}

// CharacterClassTypeInfo is the static metadata attached to a CharacterClassType.
type CharacterClassTypeInfo struct {
	CharacterClassType
	Name     string
	Reserved bool
	Title    string
}

var characterClassTypeInfos = map[CharacterClassType]CharacterClassTypeInfo{
	CharacterClassTypeUnknown: {
		CharacterClassType: CharacterClassTypeUnknown,
		Name:               "Unknown",
		Reserved:           true,
		Title:              "",
	},
	CharacterClassTypeWarrior: {
		CharacterClassType: CharacterClassTypeWarrior,
		Name:               "Warrior",
		Reserved:           false,
		Title:              "Warrior",
	},
	CharacterClassTypeHashashin: {
		CharacterClassType: CharacterClassTypeHashashin,
		Name:               "Hashashin",
		Reserved:           false,
		Title:              "Hashashin",
	},
	CharacterClassTypeSage: {
		CharacterClassType: CharacterClassTypeSage,
		Name:               "Sage",
		Reserved:           false,
		Title:              "Sage",
	},
	CharacterClassTypeWukong: {
		CharacterClassType: CharacterClassTypeWukong,
		Name:               "Wukong",
		Reserved:           false,
		Title:              "Wukong",
	},
	CharacterClassTypeRanger: {
		CharacterClassType: CharacterClassTypeRanger,
		Name:               "Ranger",
		Reserved:           false,
		Title:              "Ranger",
	},
	CharacterClassTypeGuardian: {
		CharacterClassType: CharacterClassTypeGuardian,
		Name:               "Guardian",
		Reserved:           false,
		Title:              "Guardian",
	},
	CharacterClassTypeScholar: {
		CharacterClassType: CharacterClassTypeScholar,
		Name:               "Scholar",
		Reserved:           false,
		Title:              "Scholar",
	},
	CharacterClassTypeDrakania: {
		CharacterClassType: CharacterClassTypeDrakania,
		Name:               "Drakania",
		Reserved:           false,
		Title:              "Drakania",
	},
	CharacterClassTypeSorceress: {
		CharacterClassType: CharacterClassTypeSorceress,
		Name:               "Sorceress",
		Reserved:           false,
		Title:              "Sorceress",
	},
	CharacterClassTypeNova: {
		CharacterClassType: CharacterClassTypeNova,
		Name:               "Nova",
		Reserved:           false,
		Title:              "Nova",
	},
	CharacterClassTypeCorsair: {
		CharacterClassType: CharacterClassTypeCorsair,
		Name:               "Corsair",
		Reserved:           false,
		Title:              "Corsair",
	},
	CharacterClassTypeLahn: {
		CharacterClassType: CharacterClassTypeLahn,
		Name:               "Lahn",
		Reserved:           false,
		Title:              "Lahn",
	},
	CharacterClassTypeBerserker: {
		CharacterClassType: CharacterClassTypeBerserker,
		Name:               "Berserker",
		Reserved:           false,
		Title:              "Berserker",
	},
	CharacterClassTypeReserved13: {
		CharacterClassType: CharacterClassTypeReserved13,
		Name:               "Reserved13",
		Reserved:           true,
		Title:              "",
	},
	CharacterClassTypeReserved14: {
		CharacterClassType: CharacterClassTypeReserved14,
		Name:               "Reserved14",
		Reserved:           true,
		Title:              "",
	},
	CharacterClassTypeMaegu: {
		CharacterClassType: CharacterClassTypeMaegu,
		Name:               "Maegu",
		Reserved:           false,
		Title:              "Maegu",
	},
	CharacterClassTypeTamer: {
		CharacterClassType: CharacterClassTypeTamer,
		Name:               "Tamer",
		Reserved:           false,
		Title:              "Tamer",
	},
	CharacterClassTypeShai: {
		CharacterClassType: CharacterClassTypeShai,
		Name:               "Shai",
		Reserved:           false,
		Title:              "Shai",
	},
	CharacterClassTypeReserved18: {
		CharacterClassType: CharacterClassTypeReserved18,
		Name:               "Reserved18",
		Reserved:           true,
		Title:              "",
	},
	CharacterClassTypeStriker: {
		CharacterClassType: CharacterClassTypeStriker,
		Name:               "Striker",
		Reserved:           false,
		Title:              "Striker",
	},
	CharacterClassTypeMusa: {
		CharacterClassType: CharacterClassTypeMusa,
		Name:               "Musa",
		Reserved:           false,
		Title:              "Musa",
	},
	CharacterClassTypeMaehwa: {
		CharacterClassType: CharacterClassTypeMaehwa,
		Name:               "Maehwa",
		Reserved:           false,
		Title:              "Maehwa",
	},
	CharacterClassTypeReserved22: {
		CharacterClassType: CharacterClassTypeReserved22,
		Name:               "Reserved22",
		Reserved:           true,
		Title:              "",
	},
	CharacterClassTypeMystic: {
		CharacterClassType: CharacterClassTypeMystic,
		Name:               "Mystic",
		Reserved:           false,
		Title:              "Mystic",
	},
	CharacterClassTypeValkyrie: {
		CharacterClassType: CharacterClassTypeValkyrie,
		Name:               "Valkyrie",
		Reserved:           false,
		Title:              "Valkyrie",
	},
	CharacterClassTypeKunoichi: {
		CharacterClassType: CharacterClassTypeKunoichi,
		Name:               "Kunoichi",
		Reserved:           false,
		Title:              "Kunoichi",
	},
	CharacterClassTypeNinja: {
		CharacterClassType: CharacterClassTypeNinja,
		Name:               "Ninja",
		Reserved:           false,
		Title:              "Ninja",
	},
	CharacterClassTypeDarkKnight: {
		CharacterClassType: CharacterClassTypeDarkKnight,
		Name:               "DarkKnight",
		Reserved:           false,
		Title:              "Dark Knight",
	},
	CharacterClassTypeWizard: {
		CharacterClassType: CharacterClassTypeWizard,
		Name:               "Wizard",
		Reserved:           false,
		Title:              "Wizard",
	},
	CharacterClassTypeArcher: {
		CharacterClassType: CharacterClassTypeArcher,
		Name:               "Archer",
		Reserved:           false,
		Title:              "Archer",
	},
	CharacterClassTypeWoosa: {
		CharacterClassType: CharacterClassTypeWoosa,
		Name:               "Woosa",
		Reserved:           false,
		Title:              "Woosa",
	},
	CharacterClassTypeWitch: {
		CharacterClassType: CharacterClassTypeWitch,
		Name:               "Witch",
		Reserved:           false,
		Title:              "Witch",
	},
	CharacterClassTypeSeraph: {
		CharacterClassType: CharacterClassTypeSeraph,
		Name:               "Seraph",
		Reserved:           false,
		Title:              "Seraph",
	},
	CharacterClassTypeDosa: {
		CharacterClassType: CharacterClassTypeDosa,
		Name:               "Dosa",
		Reserved:           false,
		Title:              "Dosa",
	},
	CharacterClassTypeDeadeye: {
		CharacterClassType: CharacterClassTypeDeadeye,
		Name:               "Deadeye",
		Reserved:           false,
		Title:              "Deadeye",
	},
	CharacterClassTypeReserved35: {
		CharacterClassType: CharacterClassTypeReserved35,
		Name:               "Reserved35",
		Reserved:           true,
		Title:              "",
	},
	CharacterClassTypeReserved36: {
		CharacterClassType: CharacterClassTypeReserved36,
		Name:               "Reserved36",
		Reserved:           true,
		Title:              "",
	},
}

var characterClassTypeValues = []CharacterClassType{
	CharacterClassTypeUnknown,
	CharacterClassTypeWarrior,
	CharacterClassTypeHashashin,
	CharacterClassTypeSage,
	CharacterClassTypeWukong,
	CharacterClassTypeRanger,
	CharacterClassTypeGuardian,
	CharacterClassTypeScholar,
	CharacterClassTypeDrakania,
	CharacterClassTypeSorceress,
	CharacterClassTypeNova,
	CharacterClassTypeCorsair,
	CharacterClassTypeLahn,
	CharacterClassTypeBerserker,
	CharacterClassTypeReserved13,
	CharacterClassTypeReserved14,
	CharacterClassTypeMaegu,
	CharacterClassTypeTamer,
	CharacterClassTypeShai,
	CharacterClassTypeReserved18,
	CharacterClassTypeStriker,
	CharacterClassTypeMusa,
	CharacterClassTypeMaehwa,
	CharacterClassTypeReserved22,
	CharacterClassTypeMystic,
	CharacterClassTypeValkyrie,
	CharacterClassTypeKunoichi,
	CharacterClassTypeNinja,
	CharacterClassTypeDarkKnight,
	CharacterClassTypeWizard,
	CharacterClassTypeArcher,
	CharacterClassTypeWoosa,
	CharacterClassTypeWitch,
	CharacterClassTypeSeraph,
	CharacterClassTypeDosa,
	CharacterClassTypeDeadeye,
	CharacterClassTypeReserved35,
	CharacterClassTypeReserved36,
}

var characterClassTypeByName = map[string]CharacterClassType{
	"unknown":    CharacterClassTypeUnknown,
	"warrior":    CharacterClassTypeWarrior,
	"hashashin":  CharacterClassTypeHashashin,
	"sage":       CharacterClassTypeSage,
	"wukong":     CharacterClassTypeWukong,
	"ranger":     CharacterClassTypeRanger,
	"guardian":   CharacterClassTypeGuardian,
	"scholar":    CharacterClassTypeScholar,
	"drakania":   CharacterClassTypeDrakania,
	"sorceress":  CharacterClassTypeSorceress,
	"nova":       CharacterClassTypeNova,
	"corsair":    CharacterClassTypeCorsair,
	"lahn":       CharacterClassTypeLahn,
	"berserker":  CharacterClassTypeBerserker,
	"reserved13": CharacterClassTypeReserved13,
	"reserved14": CharacterClassTypeReserved14,
	"maegu":      CharacterClassTypeMaegu,
	"tamer":      CharacterClassTypeTamer,
	"shai":       CharacterClassTypeShai,
	"reserved18": CharacterClassTypeReserved18,
	"striker":    CharacterClassTypeStriker,
	"musa":       CharacterClassTypeMusa,
	"maehwa":     CharacterClassTypeMaehwa,
	"reserved22": CharacterClassTypeReserved22,
	"mystic":     CharacterClassTypeMystic,
	"valkyrie":   CharacterClassTypeValkyrie,
	"kunoichi":   CharacterClassTypeKunoichi,
	"ninja":      CharacterClassTypeNinja,
	"darkknight": CharacterClassTypeDarkKnight,
	"wizard":     CharacterClassTypeWizard,
	"archer":     CharacterClassTypeArcher,
	"woosa":      CharacterClassTypeWoosa,
	"witch":      CharacterClassTypeWitch,
	"seraph":     CharacterClassTypeSeraph,
	"dosa":       CharacterClassTypeDosa,
	"deadeye":    CharacterClassTypeDeadeye,
	"reserved35": CharacterClassTypeReserved35,
	"reserved36": CharacterClassTypeReserved36,
}

// Values returns every declared value in declaration order.
func (c CharacterClassTypeContainer) Values() []CharacterClassType {
	out := make([]CharacterClassType, len(characterClassTypeValues))
	copy(out, characterClassTypeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c CharacterClassTypeContainer) Infos() []CharacterClassTypeInfo {
	out := make([]CharacterClassTypeInfo, len(characterClassTypeValues))
	for i, v := range characterClassTypeValues {
		out[i] = characterClassTypeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c CharacterClassTypeContainer) Len() int {
	return len(characterClassTypeValues)
}

// All iterates every declared value in declaration order.
func (c CharacterClassTypeContainer) All() iter.Seq[CharacterClassType] {
	return func(yield func(CharacterClassType) bool) {
		for _, v := range characterClassTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c CharacterClassTypeContainer) FromWire(w int8) (CharacterClassType, bool) {
	v := CharacterClassType(w)
	_, ok := characterClassTypeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c CharacterClassTypeContainer) FromWireUnsafe(w int8) CharacterClassType {
	return CharacterClassType(w)
}

// Parse resolves a value by name, case-insensitively.
func (c CharacterClassTypeContainer) Parse(s string) (CharacterClassType, error) {
	if v, ok := characterClassTypeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero CharacterClassType
	return zero, fmt.Errorf("unknown CharacterClassType: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v CharacterClassType) TryGetInfo() (CharacterClassTypeInfo, bool) {
	i, ok := characterClassTypeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v CharacterClassType) Info() CharacterClassTypeInfo {
	return characterClassTypeInfos[v]
}

func (v CharacterClassType) Valid() bool {
	_, ok := characterClassTypeInfos[v]
	return ok
}

func (v CharacterClassType) Wire() int8 {
	return int8(v)
}

func (v CharacterClassType) Name() string {
	return characterClassTypeInfos[v].Name
}

func (v CharacterClassType) String() string {
	if i, ok := characterClassTypeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("CharacterClassType(%d)", int8(v))
}

func (v CharacterClassType) Reserved() bool {
	return characterClassTypeInfos[v].Reserved
}

func (v CharacterClassType) Title() string {
	return characterClassTypeInfos[v].Title
}

// IterTitle iterates each declared value's Title in declaration order.
func (c CharacterClassTypeContainer) IterTitle() iter.Seq[string] {
	return func(yield func(string) bool) {
		for _, v := range characterClassTypeValues {
			if !yield(characterClassTypeInfos[v].Title) {
				return
			}
		}
	}
}
