// Code generated by enumgen from crystal_preset_slots.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// CrystalPresetSlot is a int-wide identifier. The zero-cost conversion CrystalPresetSlot(x) is
// intentional: the underlying value is the wire value.
type CrystalPresetSlot int

const (
	CrystalPresetSlotBase0         CrystalPresetSlot = 0
	CrystalPresetSlotBase1         CrystalPresetSlot = 1
	CrystalPresetSlotBase2         CrystalPresetSlot = 2
	CrystalPresetSlotBase3         CrystalPresetSlot = 3
	CrystalPresetSlotBase4         CrystalPresetSlot = 4
	CrystalPresetSlotBase5         CrystalPresetSlot = 5
	CrystalPresetSlotBase6         CrystalPresetSlot = 6
	CrystalPresetSlotBase7         CrystalPresetSlot = 7
	CrystalPresetSlotBase8         CrystalPresetSlot = 8
	CrystalPresetSlotBase9         CrystalPresetSlot = 9
	CrystalPresetSlotBase10        CrystalPresetSlot = 10
	CrystalPresetSlotBase11        CrystalPresetSlot = 11
	CrystalPresetSlotCostume       CrystalPresetSlot = 12
	CrystalPresetSlotHeartL        CrystalPresetSlot = 13
	CrystalPresetSlotHeartR        CrystalPresetSlot = 14
	CrystalPresetSlotLoMLL         CrystalPresetSlot = 15
	CrystalPresetSlotLoMLR         CrystalPresetSlot = 16
	CrystalPresetSlotDawnNecklace  CrystalPresetSlot = 17
	CrystalPresetSlotDawnRingI     CrystalPresetSlot = 18
	CrystalPresetSlotDawnRingII    CrystalPresetSlot = 19
	CrystalPresetSlotDawnEarringI  CrystalPresetSlot = 20
	CrystalPresetSlotDawnEarringII CrystalPresetSlot = 21
	CrystalPresetSlotDawnBelt      CrystalPresetSlot = 22
	CrystalPresetSlotMAX           CrystalPresetSlot = 23
)

type CrystalPresetSlotContainer struct {
	Base0         CrystalPresetSlot
	Base1         CrystalPresetSlot
	Base2         CrystalPresetSlot
	Base3         CrystalPresetSlot
	Base4         CrystalPresetSlot
	Base5         CrystalPresetSlot
	Base6         CrystalPresetSlot
	Base7         CrystalPresetSlot
	Base8         CrystalPresetSlot
	Base9         CrystalPresetSlot
	Base10        CrystalPresetSlot
	Base11        CrystalPresetSlot
	Costume       CrystalPresetSlot
	HeartL        CrystalPresetSlot
	HeartR        CrystalPresetSlot
	LoMLL         CrystalPresetSlot
	LoMLR         CrystalPresetSlot
	DawnNecklace  CrystalPresetSlot
	DawnRingI     CrystalPresetSlot
	DawnRingII    CrystalPresetSlot
	DawnEarringI  CrystalPresetSlot
	DawnEarringII CrystalPresetSlot
	DawnBelt      CrystalPresetSlot
}

// CrystalPresetSlots is the entry point for the CrystalPresetSlot enum.
var CrystalPresetSlots = CrystalPresetSlotContainer{
	Base0:         CrystalPresetSlotBase0,
	Base1:         CrystalPresetSlotBase1,
	Base2:         CrystalPresetSlotBase2,
	Base3:         CrystalPresetSlotBase3,
	Base4:         CrystalPresetSlotBase4,
	Base5:         CrystalPresetSlotBase5,
	Base6:         CrystalPresetSlotBase6,
	Base7:         CrystalPresetSlotBase7,
	Base8:         CrystalPresetSlotBase8,
	Base9:         CrystalPresetSlotBase9,
	Base10:        CrystalPresetSlotBase10,
	Base11:        CrystalPresetSlotBase11,
	Costume:       CrystalPresetSlotCostume,
	HeartL:        CrystalPresetSlotHeartL,
	HeartR:        CrystalPresetSlotHeartR,
	LoMLL:         CrystalPresetSlotLoMLL,
	LoMLR:         CrystalPresetSlotLoMLR,
	DawnNecklace:  CrystalPresetSlotDawnNecklace,
	DawnRingI:     CrystalPresetSlotDawnRingI,
	DawnRingII:    CrystalPresetSlotDawnRingII,
	DawnEarringI:  CrystalPresetSlotDawnEarringI,
	DawnEarringII: CrystalPresetSlotDawnEarringII,
	DawnBelt:      CrystalPresetSlotDawnBelt,
}

// CrystalPresetSlotInfo is the static metadata attached to a CrystalPresetSlot.
type CrystalPresetSlotInfo struct {
	CrystalPresetSlot
	Name          string
	Title         string
	Kind          string
	CrystalGroup  uint32
	SpecialSlot   CrystalSpecialSlot
	DawnEquipSlot SlotName
}

var crystalPresetSlotInfos = map[CrystalPresetSlot]CrystalPresetSlotInfo{
	CrystalPresetSlotBase0: {
		CrystalPresetSlot: CrystalPresetSlotBase0,
		Name:              "Base0",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase1: {
		CrystalPresetSlot: CrystalPresetSlotBase1,
		Name:              "Base1",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase2: {
		CrystalPresetSlot: CrystalPresetSlotBase2,
		Name:              "Base2",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase3: {
		CrystalPresetSlot: CrystalPresetSlotBase3,
		Name:              "Base3",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase4: {
		CrystalPresetSlot: CrystalPresetSlotBase4,
		Name:              "Base4",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase5: {
		CrystalPresetSlot: CrystalPresetSlotBase5,
		Name:              "Base5",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase6: {
		CrystalPresetSlot: CrystalPresetSlotBase6,
		Name:              "Base6",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase7: {
		CrystalPresetSlot: CrystalPresetSlotBase7,
		Name:              "Base7",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase8: {
		CrystalPresetSlot: CrystalPresetSlotBase8,
		Name:              "Base8",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase9: {
		CrystalPresetSlot: CrystalPresetSlotBase9,
		Name:              "Base9",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase10: {
		CrystalPresetSlot: CrystalPresetSlotBase10,
		Name:              "Base10",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotBase11: {
		CrystalPresetSlot: CrystalPresetSlotBase11,
		Name:              "Base11",
		Title:             "Crystal",
		Kind:              "base",
		CrystalGroup:      0,
	},
	CrystalPresetSlotCostume: {
		CrystalPresetSlot: CrystalPresetSlotCostume,
		Name:              "Costume",
		Title:             "Costume",
		Kind:              "costume",
		CrystalGroup:      101,
		SpecialSlot:       CrystalSpecialSlotPearlAvatarChest,
	},
	CrystalPresetSlotHeartL: {
		CrystalPresetSlot: CrystalPresetSlotHeartL,
		Name:              "HeartL",
		Title:             "Heart L",
		Kind:              "heart",
		CrystalGroup:      0,
	},
	CrystalPresetSlotHeartR: {
		CrystalPresetSlot: CrystalPresetSlotHeartR,
		Name:              "HeartR",
		Title:             "Heart R",
		Kind:              "heart",
		CrystalGroup:      0,
	},
	CrystalPresetSlotLoMLL: {
		CrystalPresetSlot: CrystalPresetSlotLoMLL,
		Name:              "LoMLL",
		Title:             "LoML L",
		Kind:              "loml",
		CrystalGroup:      0,
	},
	CrystalPresetSlotLoMLR: {
		CrystalPresetSlot: CrystalPresetSlotLoMLR,
		Name:              "LoMLR",
		Title:             "LoML R",
		Kind:              "loml",
		CrystalGroup:      0,
	},
	CrystalPresetSlotDawnNecklace: {
		CrystalPresetSlot: CrystalPresetSlotDawnNecklace,
		Name:              "DawnNecklace",
		Title:             "Necklace",
		Kind:              "dawn",
		CrystalGroup:      103,
		SpecialSlot:       CrystalSpecialSlotNecklace,
		DawnEquipSlot:     SlotNameNecklace,
	},
	CrystalPresetSlotDawnRingI: {
		CrystalPresetSlot: CrystalPresetSlotDawnRingI,
		Name:              "DawnRingI",
		Title:             "Ring I",
		Kind:              "dawn",
		CrystalGroup:      103,
		SpecialSlot:       CrystalSpecialSlotRingI,
		DawnEquipSlot:     SlotNameRingI,
	},
	CrystalPresetSlotDawnRingII: {
		CrystalPresetSlot: CrystalPresetSlotDawnRingII,
		Name:              "DawnRingII",
		Title:             "Ring II",
		Kind:              "dawn",
		CrystalGroup:      103,
		SpecialSlot:       CrystalSpecialSlotRingII,
		DawnEquipSlot:     SlotNameRingII,
	},
	CrystalPresetSlotDawnEarringI: {
		CrystalPresetSlot: CrystalPresetSlotDawnEarringI,
		Name:              "DawnEarringI",
		Title:             "Earring I",
		Kind:              "dawn",
		CrystalGroup:      103,
		SpecialSlot:       CrystalSpecialSlotEarringI,
		DawnEquipSlot:     SlotNameEarringI,
	},
	CrystalPresetSlotDawnEarringII: {
		CrystalPresetSlot: CrystalPresetSlotDawnEarringII,
		Name:              "DawnEarringII",
		Title:             "Earring II",
		Kind:              "dawn",
		CrystalGroup:      103,
		SpecialSlot:       CrystalSpecialSlotEarringII,
		DawnEquipSlot:     SlotNameEarringII,
	},
	CrystalPresetSlotDawnBelt: {
		CrystalPresetSlot: CrystalPresetSlotDawnBelt,
		Name:              "DawnBelt",
		Title:             "Belt",
		Kind:              "dawn",
		CrystalGroup:      103,
		SpecialSlot:       CrystalSpecialSlotBelt,
		DawnEquipSlot:     SlotNameBelt,
	},
}

var crystalPresetSlotValues = []CrystalPresetSlot{
	CrystalPresetSlotBase0,
	CrystalPresetSlotBase1,
	CrystalPresetSlotBase2,
	CrystalPresetSlotBase3,
	CrystalPresetSlotBase4,
	CrystalPresetSlotBase5,
	CrystalPresetSlotBase6,
	CrystalPresetSlotBase7,
	CrystalPresetSlotBase8,
	CrystalPresetSlotBase9,
	CrystalPresetSlotBase10,
	CrystalPresetSlotBase11,
	CrystalPresetSlotCostume,
	CrystalPresetSlotHeartL,
	CrystalPresetSlotHeartR,
	CrystalPresetSlotLoMLL,
	CrystalPresetSlotLoMLR,
	CrystalPresetSlotDawnNecklace,
	CrystalPresetSlotDawnRingI,
	CrystalPresetSlotDawnRingII,
	CrystalPresetSlotDawnEarringI,
	CrystalPresetSlotDawnEarringII,
	CrystalPresetSlotDawnBelt,
}

var crystalPresetSlotByName = map[string]CrystalPresetSlot{
	"base0":         CrystalPresetSlotBase0,
	"base1":         CrystalPresetSlotBase1,
	"base2":         CrystalPresetSlotBase2,
	"base3":         CrystalPresetSlotBase3,
	"base4":         CrystalPresetSlotBase4,
	"base5":         CrystalPresetSlotBase5,
	"base6":         CrystalPresetSlotBase6,
	"base7":         CrystalPresetSlotBase7,
	"base8":         CrystalPresetSlotBase8,
	"base9":         CrystalPresetSlotBase9,
	"base10":        CrystalPresetSlotBase10,
	"base11":        CrystalPresetSlotBase11,
	"costume":       CrystalPresetSlotCostume,
	"heartl":        CrystalPresetSlotHeartL,
	"heartr":        CrystalPresetSlotHeartR,
	"lomll":         CrystalPresetSlotLoMLL,
	"lomlr":         CrystalPresetSlotLoMLR,
	"dawnnecklace":  CrystalPresetSlotDawnNecklace,
	"dawnringi":     CrystalPresetSlotDawnRingI,
	"dawnringii":    CrystalPresetSlotDawnRingII,
	"dawnearringi":  CrystalPresetSlotDawnEarringI,
	"dawnearringii": CrystalPresetSlotDawnEarringII,
	"dawnbelt":      CrystalPresetSlotDawnBelt,
}

// Values returns every declared value in declaration order.
func (c CrystalPresetSlotContainer) Values() []CrystalPresetSlot {
	out := make([]CrystalPresetSlot, len(crystalPresetSlotValues))
	copy(out, crystalPresetSlotValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c CrystalPresetSlotContainer) Infos() []CrystalPresetSlotInfo {
	out := make([]CrystalPresetSlotInfo, len(crystalPresetSlotValues))
	for i, v := range crystalPresetSlotValues {
		out[i] = crystalPresetSlotInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c CrystalPresetSlotContainer) Len() int {
	return len(crystalPresetSlotValues)
}

// All iterates every declared value in declaration order.
func (c CrystalPresetSlotContainer) All() iter.Seq[CrystalPresetSlot] {
	return func(yield func(CrystalPresetSlot) bool) {
		for _, v := range crystalPresetSlotValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c CrystalPresetSlotContainer) FromWire(w int) (CrystalPresetSlot, bool) {
	v := CrystalPresetSlot(w)
	_, ok := crystalPresetSlotInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c CrystalPresetSlotContainer) FromWireUnsafe(w int) CrystalPresetSlot {
	return CrystalPresetSlot(w)
}

// Parse resolves a value by name, case-insensitively.
func (c CrystalPresetSlotContainer) Parse(s string) (CrystalPresetSlot, error) {
	if v, ok := crystalPresetSlotByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero CrystalPresetSlot
	return zero, fmt.Errorf("unknown CrystalPresetSlot: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v CrystalPresetSlot) TryGetInfo() (CrystalPresetSlotInfo, bool) {
	i, ok := crystalPresetSlotInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v CrystalPresetSlot) Info() CrystalPresetSlotInfo {
	return crystalPresetSlotInfos[v]
}

func (v CrystalPresetSlot) Valid() bool {
	_, ok := crystalPresetSlotInfos[v]
	return ok
}

func (v CrystalPresetSlot) Wire() int {
	return int(v)
}

func (v CrystalPresetSlot) Name() string {
	return crystalPresetSlotInfos[v].Name
}

func (v CrystalPresetSlot) String() string {
	if i, ok := crystalPresetSlotInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("CrystalPresetSlot(%d)", int(v))
}

func (v CrystalPresetSlot) Title() string {
	return crystalPresetSlotInfos[v].Title
}

func (v CrystalPresetSlot) Kind() string {
	return crystalPresetSlotInfos[v].Kind
}

func (v CrystalPresetSlot) CrystalGroup() uint32 {
	return crystalPresetSlotInfos[v].CrystalGroup
}

func (v CrystalPresetSlot) SpecialSlot() CrystalSpecialSlot {
	return crystalPresetSlotInfos[v].SpecialSlot
}

func (v CrystalPresetSlot) DawnEquipSlot() SlotName {
	return crystalPresetSlotInfos[v].DawnEquipSlot
}
