// Code generated by enumgen from crystal_special_slots.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// CrystalSpecialSlot is a uint8-wide identifier. The zero-cost conversion CrystalSpecialSlot(x) is
// intentional: the underlying value is the wire value.
type CrystalSpecialSlot uint8

const (
	CrystalSpecialSlotPearlAvatarChest CrystalSpecialSlot = 14
	CrystalSpecialSlotNecklace         CrystalSpecialSlot = 17
	CrystalSpecialSlotRingI            CrystalSpecialSlot = 18
	CrystalSpecialSlotRingII           CrystalSpecialSlot = 19
	CrystalSpecialSlotEarringI         CrystalSpecialSlot = 20
	CrystalSpecialSlotEarringII        CrystalSpecialSlot = 21
	CrystalSpecialSlotBelt             CrystalSpecialSlot = 22
)

type CrystalSpecialSlotContainer struct {
	PearlAvatarChest CrystalSpecialSlot
	Necklace         CrystalSpecialSlot
	RingI            CrystalSpecialSlot
	RingII           CrystalSpecialSlot
	EarringI         CrystalSpecialSlot
	EarringII        CrystalSpecialSlot
	Belt             CrystalSpecialSlot
}

// CrystalSpecialSlots is the entry point for the CrystalSpecialSlot enum.
var CrystalSpecialSlots = CrystalSpecialSlotContainer{
	PearlAvatarChest: CrystalSpecialSlotPearlAvatarChest,
	Necklace:         CrystalSpecialSlotNecklace,
	RingI:            CrystalSpecialSlotRingI,
	RingII:           CrystalSpecialSlotRingII,
	EarringI:         CrystalSpecialSlotEarringI,
	EarringII:        CrystalSpecialSlotEarringII,
	Belt:             CrystalSpecialSlotBelt,
}

// CrystalSpecialSlotInfo is the static metadata attached to a CrystalSpecialSlot.
type CrystalSpecialSlotInfo struct {
	CrystalSpecialSlot
	Name  string
	Title string
}

var crystalSpecialSlotInfos = map[CrystalSpecialSlot]CrystalSpecialSlotInfo{
	CrystalSpecialSlotPearlAvatarChest: {
		CrystalSpecialSlot: CrystalSpecialSlotPearlAvatarChest,
		Name:               "PearlAvatarChest",
		Title:              "Costume Armor",
	},
	CrystalSpecialSlotNecklace: {
		CrystalSpecialSlot: CrystalSpecialSlotNecklace,
		Name:               "Necklace",
		Title:              "Necklace",
	},
	CrystalSpecialSlotRingI: {
		CrystalSpecialSlot: CrystalSpecialSlotRingI,
		Name:               "RingI",
		Title:              "Ring I",
	},
	CrystalSpecialSlotRingII: {
		CrystalSpecialSlot: CrystalSpecialSlotRingII,
		Name:               "RingII",
		Title:              "Ring II",
	},
	CrystalSpecialSlotEarringI: {
		CrystalSpecialSlot: CrystalSpecialSlotEarringI,
		Name:               "EarringI",
		Title:              "Earring I",
	},
	CrystalSpecialSlotEarringII: {
		CrystalSpecialSlot: CrystalSpecialSlotEarringII,
		Name:               "EarringII",
		Title:              "Earring II",
	},
	CrystalSpecialSlotBelt: {
		CrystalSpecialSlot: CrystalSpecialSlotBelt,
		Name:               "Belt",
		Title:              "Belt",
	},
}

var crystalSpecialSlotValues = []CrystalSpecialSlot{
	CrystalSpecialSlotPearlAvatarChest,
	CrystalSpecialSlotNecklace,
	CrystalSpecialSlotRingI,
	CrystalSpecialSlotRingII,
	CrystalSpecialSlotEarringI,
	CrystalSpecialSlotEarringII,
	CrystalSpecialSlotBelt,
}

var crystalSpecialSlotByName = map[string]CrystalSpecialSlot{
	"pearlavatarchest": CrystalSpecialSlotPearlAvatarChest,
	"necklace":         CrystalSpecialSlotNecklace,
	"ringi":            CrystalSpecialSlotRingI,
	"ringii":           CrystalSpecialSlotRingII,
	"earringi":         CrystalSpecialSlotEarringI,
	"earringii":        CrystalSpecialSlotEarringII,
	"belt":             CrystalSpecialSlotBelt,
}

// Values returns every declared value in declaration order.
func (c CrystalSpecialSlotContainer) Values() []CrystalSpecialSlot {
	out := make([]CrystalSpecialSlot, len(crystalSpecialSlotValues))
	copy(out, crystalSpecialSlotValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c CrystalSpecialSlotContainer) Infos() []CrystalSpecialSlotInfo {
	out := make([]CrystalSpecialSlotInfo, len(crystalSpecialSlotValues))
	for i, v := range crystalSpecialSlotValues {
		out[i] = crystalSpecialSlotInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c CrystalSpecialSlotContainer) Len() int {
	return len(crystalSpecialSlotValues)
}

// All iterates every declared value in declaration order.
func (c CrystalSpecialSlotContainer) All() iter.Seq[CrystalSpecialSlot] {
	return func(yield func(CrystalSpecialSlot) bool) {
		for _, v := range crystalSpecialSlotValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c CrystalSpecialSlotContainer) FromWire(w uint8) (CrystalSpecialSlot, bool) {
	v := CrystalSpecialSlot(w)
	_, ok := crystalSpecialSlotInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c CrystalSpecialSlotContainer) FromWireUnsafe(w uint8) CrystalSpecialSlot {
	return CrystalSpecialSlot(w)
}

// Parse resolves a value by name, case-insensitively.
func (c CrystalSpecialSlotContainer) Parse(s string) (CrystalSpecialSlot, error) {
	if v, ok := crystalSpecialSlotByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero CrystalSpecialSlot
	return zero, fmt.Errorf("unknown CrystalSpecialSlot: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v CrystalSpecialSlot) TryGetInfo() (CrystalSpecialSlotInfo, bool) {
	i, ok := crystalSpecialSlotInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v CrystalSpecialSlot) Info() CrystalSpecialSlotInfo {
	return crystalSpecialSlotInfos[v]
}

func (v CrystalSpecialSlot) Valid() bool {
	_, ok := crystalSpecialSlotInfos[v]
	return ok
}

func (v CrystalSpecialSlot) Wire() uint8 {
	return uint8(v)
}

func (v CrystalSpecialSlot) Name() string {
	return crystalSpecialSlotInfos[v].Name
}

func (v CrystalSpecialSlot) String() string {
	if i, ok := crystalSpecialSlotInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("CrystalSpecialSlot(%d)", uint8(v))
}

func (v CrystalSpecialSlot) Title() string {
	return crystalSpecialSlotInfos[v].Title
}
