// Code generated by enumgen from family_stat_types.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// FamilyStatType is a uint32-wide identifier. The zero-cost conversion FamilyStatType(x) is
// intentional: the underlying value is the wire value.
type FamilyStatType uint32

const (
	FamilyStatTypeOffence           FamilyStatType = 0
	FamilyStatTypeDefence           FamilyStatType = 1
	FamilyStatTypeHP                FamilyStatType = 2
	FamilyStatTypeMP                FamilyStatType = 3
	FamilyStatTypeStamina           FamilyStatType = 4
	FamilyStatTypeWeight            FamilyStatType = 5
	FamilyStatTypeInventory         FamilyStatType = 6
	FamilyStatTypeAccuracy          FamilyStatType = 7
	FamilyStatTypeEvasion           FamilyStatType = 8
	FamilyStatTypeEnhancementChance FamilyStatType = 9
	FamilyStatTypeValksLimit        FamilyStatType = 10
	FamilyStatTypeStackLimit        FamilyStatType = 11
	FamilyStatTypeNone              FamilyStatType = 16
)

type FamilyStatTypeContainer struct {
	Offence           FamilyStatType
	Defence           FamilyStatType
	HP                FamilyStatType
	MP                FamilyStatType
	Stamina           FamilyStatType
	Weight            FamilyStatType
	Inventory         FamilyStatType
	Accuracy          FamilyStatType
	Evasion           FamilyStatType
	EnhancementChance FamilyStatType
	ValksLimit        FamilyStatType
	StackLimit        FamilyStatType
	None              FamilyStatType
}

// FamilyStatTypes is the entry point for the FamilyStatType enum.
var FamilyStatTypes = FamilyStatTypeContainer{
	Offence:           FamilyStatTypeOffence,
	Defence:           FamilyStatTypeDefence,
	HP:                FamilyStatTypeHP,
	MP:                FamilyStatTypeMP,
	Stamina:           FamilyStatTypeStamina,
	Weight:            FamilyStatTypeWeight,
	Inventory:         FamilyStatTypeInventory,
	Accuracy:          FamilyStatTypeAccuracy,
	Evasion:           FamilyStatTypeEvasion,
	EnhancementChance: FamilyStatTypeEnhancementChance,
	ValksLimit:        FamilyStatTypeValksLimit,
	StackLimit:        FamilyStatTypeStackLimit,
	None:              FamilyStatTypeNone,
}

// FamilyStatTypeInfo is the static metadata attached to a FamilyStatType.
type FamilyStatTypeInfo struct {
	FamilyStatType
	Name  string
	Title string
}

var familyStatTypeInfos = map[FamilyStatType]FamilyStatTypeInfo{
	FamilyStatTypeOffence: {
		FamilyStatType: FamilyStatTypeOffence,
		Name:           "Offence",
		Title:          "All AP",
	},
	FamilyStatTypeDefence: {
		FamilyStatType: FamilyStatTypeDefence,
		Name:           "Defence",
		Title:          "All DP",
	},
	FamilyStatTypeHP: {
		FamilyStatType: FamilyStatTypeHP,
		Name:           "HP",
		Title:          "Max HP",
	},
	FamilyStatTypeMP: {
		FamilyStatType: FamilyStatTypeMP,
		Name:           "MP",
		Title:          "Max MP",
	},
	FamilyStatTypeStamina: {
		FamilyStatType: FamilyStatTypeStamina,
		Name:           "Stamina",
		Title:          "Max Stamina",
	},
	FamilyStatTypeWeight: {
		FamilyStatType: FamilyStatTypeWeight,
		Name:           "Weight",
		Title:          "Weight Limit",
	},
	FamilyStatTypeInventory: {
		FamilyStatType: FamilyStatTypeInventory,
		Name:           "Inventory",
		Title:          "Inventory Slots",
	},
	FamilyStatTypeAccuracy: {
		FamilyStatType: FamilyStatTypeAccuracy,
		Name:           "Accuracy",
		Title:          "Accuracy",
	},
	FamilyStatTypeEvasion: {
		FamilyStatType: FamilyStatTypeEvasion,
		Name:           "Evasion",
		Title:          "Evasion",
	},
	FamilyStatTypeEnhancementChance: {
		FamilyStatType: FamilyStatTypeEnhancementChance,
		Name:           "EnhancementChance",
		Title:          "Enhancement Chance",
	},
	FamilyStatTypeValksLimit: {
		FamilyStatType: FamilyStatTypeValksLimit,
		Name:           "ValksLimit",
		Title:          "Additional Enhancement Chance Limit",
	},
	FamilyStatTypeStackLimit: {
		FamilyStatType: FamilyStatTypeStackLimit,
		Name:           "StackLimit",
		Title:          "Enhancement Chance Stack Limit",
	},
	FamilyStatTypeNone: {
		FamilyStatType: FamilyStatTypeNone,
		Name:           "None",
		Title:          "None",
	},
}

var familyStatTypeValues = []FamilyStatType{
	FamilyStatTypeOffence,
	FamilyStatTypeDefence,
	FamilyStatTypeHP,
	FamilyStatTypeMP,
	FamilyStatTypeStamina,
	FamilyStatTypeWeight,
	FamilyStatTypeInventory,
	FamilyStatTypeAccuracy,
	FamilyStatTypeEvasion,
	FamilyStatTypeEnhancementChance,
	FamilyStatTypeValksLimit,
	FamilyStatTypeStackLimit,
	FamilyStatTypeNone,
}

var familyStatTypeByName = map[string]FamilyStatType{
	"offence":           FamilyStatTypeOffence,
	"defence":           FamilyStatTypeDefence,
	"hp":                FamilyStatTypeHP,
	"mp":                FamilyStatTypeMP,
	"stamina":           FamilyStatTypeStamina,
	"weight":            FamilyStatTypeWeight,
	"inventory":         FamilyStatTypeInventory,
	"accuracy":          FamilyStatTypeAccuracy,
	"evasion":           FamilyStatTypeEvasion,
	"enhancementchance": FamilyStatTypeEnhancementChance,
	"valkslimit":        FamilyStatTypeValksLimit,
	"stacklimit":        FamilyStatTypeStackLimit,
	"none":              FamilyStatTypeNone,
}

// Values returns every declared value in declaration order.
func (c FamilyStatTypeContainer) Values() []FamilyStatType {
	out := make([]FamilyStatType, len(familyStatTypeValues))
	copy(out, familyStatTypeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c FamilyStatTypeContainer) Infos() []FamilyStatTypeInfo {
	out := make([]FamilyStatTypeInfo, len(familyStatTypeValues))
	for i, v := range familyStatTypeValues {
		out[i] = familyStatTypeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c FamilyStatTypeContainer) Len() int {
	return len(familyStatTypeValues)
}

// All iterates every declared value in declaration order.
func (c FamilyStatTypeContainer) All() iter.Seq[FamilyStatType] {
	return func(yield func(FamilyStatType) bool) {
		for _, v := range familyStatTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c FamilyStatTypeContainer) FromWire(w uint32) (FamilyStatType, bool) {
	v := FamilyStatType(w)
	_, ok := familyStatTypeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c FamilyStatTypeContainer) FromWireUnsafe(w uint32) FamilyStatType {
	return FamilyStatType(w)
}

// Parse resolves a value by name, case-insensitively.
func (c FamilyStatTypeContainer) Parse(s string) (FamilyStatType, error) {
	if v, ok := familyStatTypeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero FamilyStatType
	return zero, fmt.Errorf("unknown FamilyStatType: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v FamilyStatType) TryGetInfo() (FamilyStatTypeInfo, bool) {
	i, ok := familyStatTypeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v FamilyStatType) Info() FamilyStatTypeInfo {
	return familyStatTypeInfos[v]
}

func (v FamilyStatType) Valid() bool {
	_, ok := familyStatTypeInfos[v]
	return ok
}

func (v FamilyStatType) Wire() uint32 {
	return uint32(v)
}

func (v FamilyStatType) Name() string {
	return familyStatTypeInfos[v].Name
}

func (v FamilyStatType) String() string {
	if i, ok := familyStatTypeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("FamilyStatType(%d)", uint32(v))
}

func (v FamilyStatType) Title() string {
	return familyStatTypeInfos[v].Title
}
