// Code generated by enumgen from item_enhancement_types.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// ItemEnhancementType is a uint32-wide identifier. The zero-cost conversion ItemEnhancementType(x) is
// intentional: the underlying value is the wire value.
type ItemEnhancementType uint32

const (
	ItemEnhancementTypeNone                             ItemEnhancementType = 0
	ItemEnhancementTypeEquipment                        ItemEnhancementType = 1
	ItemEnhancementTypeBlackstar                        ItemEnhancementType = 2
	ItemEnhancementTypeReserved3                        ItemEnhancementType = 3
	ItemEnhancementTypeReserved4                        ItemEnhancementType = 4
	ItemEnhancementTypeReserved5                        ItemEnhancementType = 5
	ItemEnhancementTypeSlumberingOrigin                 ItemEnhancementType = 6
	ItemEnhancementTypeLifeSkillClothing                ItemEnhancementType = 7
	ItemEnhancementTypeUtilityEquipment                 ItemEnhancementType = 8
	ItemEnhancementTypeCaravelGalleassEquipment         ItemEnhancementType = 9
	ItemEnhancementTypeImprovedCaravelGalleassEquipment ItemEnhancementType = 10
	ItemEnhancementTypeCarrackPanokseonEquipment        ItemEnhancementType = 11
	ItemEnhancementTypeChiroEquipment                   ItemEnhancementType = 12
	ItemEnhancementTypeAccessory                        ItemEnhancementType = 13
	ItemEnhancementTypeCapotiaAccessory                 ItemEnhancementType = 14
	ItemEnhancementTypeLifeSkillAccessory               ItemEnhancementType = 15
	ItemEnhancementTypeTuvalaAccessory                  ItemEnhancementType = 16
	ItemEnhancementTypeSealedAsulaAccessory             ItemEnhancementType = 17
	ItemEnhancementTypeQuestAccessory                   ItemEnhancementType = 18
	ItemEnhancementTypeSovereignWeapon                  ItemEnhancementType = 19
	ItemEnhancementTypeTarnishedSword                   ItemEnhancementType = 20
	ItemEnhancementTypeKharazadAccessory                ItemEnhancementType = 21
	ItemEnhancementTypePreonneAccessory                 ItemEnhancementType = 22
	ItemEnhancementTypeTuvalaEquipment                  ItemEnhancementType = 23
	ItemEnhancementTypeEdanaArmor                       ItemEnhancementType = 24
	ItemEnhancementTypeImperfectAlchemyStone            ItemEnhancementType = 25
	ItemEnhancementTypeSturdyAlchemyStone               ItemEnhancementType = 26
	ItemEnhancementTypeSharpAlchemyStone                ItemEnhancementType = 27
	ItemEnhancementTypeResplendentAlchemyStone          ItemEnhancementType = 28
	ItemEnhancementTypeSplendidAlchemyStone             ItemEnhancementType = 29
)

type ItemEnhancementTypeContainer struct {
	None                             ItemEnhancementType
	Equipment                        ItemEnhancementType
	Blackstar                        ItemEnhancementType
	Reserved3                        ItemEnhancementType
	Reserved4                        ItemEnhancementType
	Reserved5                        ItemEnhancementType
	SlumberingOrigin                 ItemEnhancementType
	LifeSkillClothing                ItemEnhancementType
	UtilityEquipment                 ItemEnhancementType
	CaravelGalleassEquipment         ItemEnhancementType
	ImprovedCaravelGalleassEquipment ItemEnhancementType
	CarrackPanokseonEquipment        ItemEnhancementType
	ChiroEquipment                   ItemEnhancementType
	Accessory                        ItemEnhancementType
	CapotiaAccessory                 ItemEnhancementType
	LifeSkillAccessory               ItemEnhancementType
	TuvalaAccessory                  ItemEnhancementType
	SealedAsulaAccessory             ItemEnhancementType
	QuestAccessory                   ItemEnhancementType
	SovereignWeapon                  ItemEnhancementType
	TarnishedSword                   ItemEnhancementType
	KharazadAccessory                ItemEnhancementType
	PreonneAccessory                 ItemEnhancementType
	TuvalaEquipment                  ItemEnhancementType
	EdanaArmor                       ItemEnhancementType
	ImperfectAlchemyStone            ItemEnhancementType
	SturdyAlchemyStone               ItemEnhancementType
	SharpAlchemyStone                ItemEnhancementType
	ResplendentAlchemyStone          ItemEnhancementType
	SplendidAlchemyStone             ItemEnhancementType
}

// ItemEnhancementTypes is the entry point for the ItemEnhancementType enum.
var ItemEnhancementTypes = ItemEnhancementTypeContainer{
	None:                             ItemEnhancementTypeNone,
	Equipment:                        ItemEnhancementTypeEquipment,
	Blackstar:                        ItemEnhancementTypeBlackstar,
	Reserved3:                        ItemEnhancementTypeReserved3,
	Reserved4:                        ItemEnhancementTypeReserved4,
	Reserved5:                        ItemEnhancementTypeReserved5,
	SlumberingOrigin:                 ItemEnhancementTypeSlumberingOrigin,
	LifeSkillClothing:                ItemEnhancementTypeLifeSkillClothing,
	UtilityEquipment:                 ItemEnhancementTypeUtilityEquipment,
	CaravelGalleassEquipment:         ItemEnhancementTypeCaravelGalleassEquipment,
	ImprovedCaravelGalleassEquipment: ItemEnhancementTypeImprovedCaravelGalleassEquipment,
	CarrackPanokseonEquipment:        ItemEnhancementTypeCarrackPanokseonEquipment,
	ChiroEquipment:                   ItemEnhancementTypeChiroEquipment,
	Accessory:                        ItemEnhancementTypeAccessory,
	CapotiaAccessory:                 ItemEnhancementTypeCapotiaAccessory,
	LifeSkillAccessory:               ItemEnhancementTypeLifeSkillAccessory,
	TuvalaAccessory:                  ItemEnhancementTypeTuvalaAccessory,
	SealedAsulaAccessory:             ItemEnhancementTypeSealedAsulaAccessory,
	QuestAccessory:                   ItemEnhancementTypeQuestAccessory,
	SovereignWeapon:                  ItemEnhancementTypeSovereignWeapon,
	TarnishedSword:                   ItemEnhancementTypeTarnishedSword,
	KharazadAccessory:                ItemEnhancementTypeKharazadAccessory,
	PreonneAccessory:                 ItemEnhancementTypePreonneAccessory,
	TuvalaEquipment:                  ItemEnhancementTypeTuvalaEquipment,
	EdanaArmor:                       ItemEnhancementTypeEdanaArmor,
	ImperfectAlchemyStone:            ItemEnhancementTypeImperfectAlchemyStone,
	SturdyAlchemyStone:               ItemEnhancementTypeSturdyAlchemyStone,
	SharpAlchemyStone:                ItemEnhancementTypeSharpAlchemyStone,
	ResplendentAlchemyStone:          ItemEnhancementTypeResplendentAlchemyStone,
	SplendidAlchemyStone:             ItemEnhancementTypeSplendidAlchemyStone,
}

// ItemEnhancementTypeInfo is the static metadata attached to a ItemEnhancementType.
type ItemEnhancementTypeInfo struct {
	ItemEnhancementType
	Name     string
	Title    string
	Reserved bool
}

var itemEnhancementTypeInfos = map[ItemEnhancementType]ItemEnhancementTypeInfo{
	ItemEnhancementTypeNone: {
		ItemEnhancementType: ItemEnhancementTypeNone,
		Name:                "None",
		Title:               "None",
		Reserved:            false,
	},
	ItemEnhancementTypeEquipment: {
		ItemEnhancementType: ItemEnhancementTypeEquipment,
		Name:                "Equipment",
		Title:               "Equipment",
		Reserved:            false,
	},
	ItemEnhancementTypeBlackstar: {
		ItemEnhancementType: ItemEnhancementTypeBlackstar,
		Name:                "Blackstar",
		Title:               "Blackstar",
		Reserved:            false,
	},
	ItemEnhancementTypeReserved3: {
		ItemEnhancementType: ItemEnhancementTypeReserved3,
		Name:                "Reserved3",
		Title:               "Reserved 3",
		Reserved:            true,
	},
	ItemEnhancementTypeReserved4: {
		ItemEnhancementType: ItemEnhancementTypeReserved4,
		Name:                "Reserved4",
		Title:               "Reserved 4",
		Reserved:            true,
	},
	ItemEnhancementTypeReserved5: {
		ItemEnhancementType: ItemEnhancementTypeReserved5,
		Name:                "Reserved5",
		Title:               "Reserved 5",
		Reserved:            true,
	},
	ItemEnhancementTypeSlumberingOrigin: {
		ItemEnhancementType: ItemEnhancementTypeSlumberingOrigin,
		Name:                "SlumberingOrigin",
		Title:               "Slumbering Origin",
		Reserved:            false,
	},
	ItemEnhancementTypeLifeSkillClothing: {
		ItemEnhancementType: ItemEnhancementTypeLifeSkillClothing,
		Name:                "LifeSkillClothing",
		Title:               "Life Skill Clothing",
		Reserved:            false,
	},
	ItemEnhancementTypeUtilityEquipment: {
		ItemEnhancementType: ItemEnhancementTypeUtilityEquipment,
		Name:                "UtilityEquipment",
		Title:               "Utility Equipment",
		Reserved:            false,
	},
	ItemEnhancementTypeCaravelGalleassEquipment: {
		ItemEnhancementType: ItemEnhancementTypeCaravelGalleassEquipment,
		Name:                "CaravelGalleassEquipment",
		Title:               "Caravel and Galleass Equipment",
		Reserved:            false,
	},
	ItemEnhancementTypeImprovedCaravelGalleassEquipment: {
		ItemEnhancementType: ItemEnhancementTypeImprovedCaravelGalleassEquipment,
		Name:                "ImprovedCaravelGalleassEquipment",
		Title:               "Improved Caravel and Galleass Equipment",
		Reserved:            false,
	},
	ItemEnhancementTypeCarrackPanokseonEquipment: {
		ItemEnhancementType: ItemEnhancementTypeCarrackPanokseonEquipment,
		Name:                "CarrackPanokseonEquipment",
		Title:               "Carrack and Panokseon Equipment",
		Reserved:            false,
	},
	ItemEnhancementTypeChiroEquipment: {
		ItemEnhancementType: ItemEnhancementTypeChiroEquipment,
		Name:                "ChiroEquipment",
		Title:               "Chiro Equipment",
		Reserved:            false,
	},
	ItemEnhancementTypeAccessory: {
		ItemEnhancementType: ItemEnhancementTypeAccessory,
		Name:                "Accessory",
		Title:               "Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypeCapotiaAccessory: {
		ItemEnhancementType: ItemEnhancementTypeCapotiaAccessory,
		Name:                "CapotiaAccessory",
		Title:               "Capotia Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypeLifeSkillAccessory: {
		ItemEnhancementType: ItemEnhancementTypeLifeSkillAccessory,
		Name:                "LifeSkillAccessory",
		Title:               "Life Skill Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypeTuvalaAccessory: {
		ItemEnhancementType: ItemEnhancementTypeTuvalaAccessory,
		Name:                "TuvalaAccessory",
		Title:               "Tuvala Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypeSealedAsulaAccessory: {
		ItemEnhancementType: ItemEnhancementTypeSealedAsulaAccessory,
		Name:                "SealedAsulaAccessory",
		Title:               "Sealed and Asula Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypeQuestAccessory: {
		ItemEnhancementType: ItemEnhancementTypeQuestAccessory,
		Name:                "QuestAccessory",
		Title:               "Quest Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypeSovereignWeapon: {
		ItemEnhancementType: ItemEnhancementTypeSovereignWeapon,
		Name:                "SovereignWeapon",
		Title:               "Sovereign Weapon",
		Reserved:            false,
	},
	ItemEnhancementTypeTarnishedSword: {
		ItemEnhancementType: ItemEnhancementTypeTarnishedSword,
		Name:                "TarnishedSword",
		Title:               "Tarnished Sword",
		Reserved:            false,
	},
	ItemEnhancementTypeKharazadAccessory: {
		ItemEnhancementType: ItemEnhancementTypeKharazadAccessory,
		Name:                "KharazadAccessory",
		Title:               "Kharazad Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypePreonneAccessory: {
		ItemEnhancementType: ItemEnhancementTypePreonneAccessory,
		Name:                "PreonneAccessory",
		Title:               "Preonne Accessory",
		Reserved:            false,
	},
	ItemEnhancementTypeTuvalaEquipment: {
		ItemEnhancementType: ItemEnhancementTypeTuvalaEquipment,
		Name:                "TuvalaEquipment",
		Title:               "Tuvala Equipment",
		Reserved:            false,
	},
	ItemEnhancementTypeEdanaArmor: {
		ItemEnhancementType: ItemEnhancementTypeEdanaArmor,
		Name:                "EdanaArmor",
		Title:               "Edana Armor",
		Reserved:            false,
	},
	ItemEnhancementTypeImperfectAlchemyStone: {
		ItemEnhancementType: ItemEnhancementTypeImperfectAlchemyStone,
		Name:                "ImperfectAlchemyStone",
		Title:               "Imperfect Alchemy Stone",
		Reserved:            false,
	},
	ItemEnhancementTypeSturdyAlchemyStone: {
		ItemEnhancementType: ItemEnhancementTypeSturdyAlchemyStone,
		Name:                "SturdyAlchemyStone",
		Title:               "Sturdy Alchemy Stone",
		Reserved:            false,
	},
	ItemEnhancementTypeSharpAlchemyStone: {
		ItemEnhancementType: ItemEnhancementTypeSharpAlchemyStone,
		Name:                "SharpAlchemyStone",
		Title:               "Sharp Alchemy Stone",
		Reserved:            false,
	},
	ItemEnhancementTypeResplendentAlchemyStone: {
		ItemEnhancementType: ItemEnhancementTypeResplendentAlchemyStone,
		Name:                "ResplendentAlchemyStone",
		Title:               "Resplendent Alchemy Stone",
		Reserved:            false,
	},
	ItemEnhancementTypeSplendidAlchemyStone: {
		ItemEnhancementType: ItemEnhancementTypeSplendidAlchemyStone,
		Name:                "SplendidAlchemyStone",
		Title:               "Splendid Alchemy Stone",
		Reserved:            false,
	},
}

var itemEnhancementTypeValues = []ItemEnhancementType{
	ItemEnhancementTypeNone,
	ItemEnhancementTypeEquipment,
	ItemEnhancementTypeBlackstar,
	ItemEnhancementTypeReserved3,
	ItemEnhancementTypeReserved4,
	ItemEnhancementTypeReserved5,
	ItemEnhancementTypeSlumberingOrigin,
	ItemEnhancementTypeLifeSkillClothing,
	ItemEnhancementTypeUtilityEquipment,
	ItemEnhancementTypeCaravelGalleassEquipment,
	ItemEnhancementTypeImprovedCaravelGalleassEquipment,
	ItemEnhancementTypeCarrackPanokseonEquipment,
	ItemEnhancementTypeChiroEquipment,
	ItemEnhancementTypeAccessory,
	ItemEnhancementTypeCapotiaAccessory,
	ItemEnhancementTypeLifeSkillAccessory,
	ItemEnhancementTypeTuvalaAccessory,
	ItemEnhancementTypeSealedAsulaAccessory,
	ItemEnhancementTypeQuestAccessory,
	ItemEnhancementTypeSovereignWeapon,
	ItemEnhancementTypeTarnishedSword,
	ItemEnhancementTypeKharazadAccessory,
	ItemEnhancementTypePreonneAccessory,
	ItemEnhancementTypeTuvalaEquipment,
	ItemEnhancementTypeEdanaArmor,
	ItemEnhancementTypeImperfectAlchemyStone,
	ItemEnhancementTypeSturdyAlchemyStone,
	ItemEnhancementTypeSharpAlchemyStone,
	ItemEnhancementTypeResplendentAlchemyStone,
	ItemEnhancementTypeSplendidAlchemyStone,
}

var itemEnhancementTypeByName = map[string]ItemEnhancementType{
	"none":                             ItemEnhancementTypeNone,
	"equipment":                        ItemEnhancementTypeEquipment,
	"blackstar":                        ItemEnhancementTypeBlackstar,
	"reserved3":                        ItemEnhancementTypeReserved3,
	"reserved4":                        ItemEnhancementTypeReserved4,
	"reserved5":                        ItemEnhancementTypeReserved5,
	"slumberingorigin":                 ItemEnhancementTypeSlumberingOrigin,
	"lifeskillclothing":                ItemEnhancementTypeLifeSkillClothing,
	"utilityequipment":                 ItemEnhancementTypeUtilityEquipment,
	"caravelgalleassequipment":         ItemEnhancementTypeCaravelGalleassEquipment,
	"improvedcaravelgalleassequipment": ItemEnhancementTypeImprovedCaravelGalleassEquipment,
	"carrackpanokseonequipment":        ItemEnhancementTypeCarrackPanokseonEquipment,
	"chiroequipment":                   ItemEnhancementTypeChiroEquipment,
	"accessory":                        ItemEnhancementTypeAccessory,
	"capotiaaccessory":                 ItemEnhancementTypeCapotiaAccessory,
	"lifeskillaccessory":               ItemEnhancementTypeLifeSkillAccessory,
	"tuvalaaccessory":                  ItemEnhancementTypeTuvalaAccessory,
	"sealedasulaaccessory":             ItemEnhancementTypeSealedAsulaAccessory,
	"questaccessory":                   ItemEnhancementTypeQuestAccessory,
	"sovereignweapon":                  ItemEnhancementTypeSovereignWeapon,
	"tarnishedsword":                   ItemEnhancementTypeTarnishedSword,
	"kharazadaccessory":                ItemEnhancementTypeKharazadAccessory,
	"preonneaccessory":                 ItemEnhancementTypePreonneAccessory,
	"tuvalaequipment":                  ItemEnhancementTypeTuvalaEquipment,
	"edanaarmor":                       ItemEnhancementTypeEdanaArmor,
	"imperfectalchemystone":            ItemEnhancementTypeImperfectAlchemyStone,
	"sturdyalchemystone":               ItemEnhancementTypeSturdyAlchemyStone,
	"sharpalchemystone":                ItemEnhancementTypeSharpAlchemyStone,
	"resplendentalchemystone":          ItemEnhancementTypeResplendentAlchemyStone,
	"splendidalchemystone":             ItemEnhancementTypeSplendidAlchemyStone,
}

// Values returns every declared value in declaration order.
func (c ItemEnhancementTypeContainer) Values() []ItemEnhancementType {
	out := make([]ItemEnhancementType, len(itemEnhancementTypeValues))
	copy(out, itemEnhancementTypeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c ItemEnhancementTypeContainer) Infos() []ItemEnhancementTypeInfo {
	out := make([]ItemEnhancementTypeInfo, len(itemEnhancementTypeValues))
	for i, v := range itemEnhancementTypeValues {
		out[i] = itemEnhancementTypeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c ItemEnhancementTypeContainer) Len() int {
	return len(itemEnhancementTypeValues)
}

// All iterates every declared value in declaration order.
func (c ItemEnhancementTypeContainer) All() iter.Seq[ItemEnhancementType] {
	return func(yield func(ItemEnhancementType) bool) {
		for _, v := range itemEnhancementTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c ItemEnhancementTypeContainer) FromWire(w uint32) (ItemEnhancementType, bool) {
	v := ItemEnhancementType(w)
	_, ok := itemEnhancementTypeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c ItemEnhancementTypeContainer) FromWireUnsafe(w uint32) ItemEnhancementType {
	return ItemEnhancementType(w)
}

// Parse resolves a value by name, case-insensitively.
func (c ItemEnhancementTypeContainer) Parse(s string) (ItemEnhancementType, error) {
	if v, ok := itemEnhancementTypeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero ItemEnhancementType
	return zero, fmt.Errorf("unknown ItemEnhancementType: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v ItemEnhancementType) TryGetInfo() (ItemEnhancementTypeInfo, bool) {
	i, ok := itemEnhancementTypeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v ItemEnhancementType) Info() ItemEnhancementTypeInfo {
	return itemEnhancementTypeInfos[v]
}

func (v ItemEnhancementType) Valid() bool {
	_, ok := itemEnhancementTypeInfos[v]
	return ok
}

func (v ItemEnhancementType) Wire() uint32 {
	return uint32(v)
}

func (v ItemEnhancementType) Name() string {
	return itemEnhancementTypeInfos[v].Name
}

func (v ItemEnhancementType) String() string {
	if i, ok := itemEnhancementTypeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("ItemEnhancementType(%d)", uint32(v))
}

func (v ItemEnhancementType) Title() string {
	return itemEnhancementTypeInfos[v].Title
}

func (v ItemEnhancementType) Reserved() bool {
	return itemEnhancementTypeInfos[v].Reserved
}
