// Code generated by enumgen from item_grades.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// ItemGrade is a int8-wide identifier. The zero-cost conversion ItemGrade(x) is
// intentional: the underlying value is the wire value.
type ItemGrade int8

const (
	ItemGradeNone   ItemGrade = -1
	ItemGradeWhite  ItemGrade = 0
	ItemGradeGreen  ItemGrade = 1
	ItemGradeBlue   ItemGrade = 2
	ItemGradeYellow ItemGrade = 3
	ItemGradeRed    ItemGrade = 4
	ItemGradePurple ItemGrade = 5
)

type ItemGradeContainer struct {
	None   ItemGrade
	White  ItemGrade
	Green  ItemGrade
	Blue   ItemGrade
	Yellow ItemGrade
	Red    ItemGrade
	Purple ItemGrade
}

// ItemGrades is the entry point for the ItemGrade enum.
var ItemGrades = ItemGradeContainer{
	None:   ItemGradeNone,
	White:  ItemGradeWhite,
	Green:  ItemGradeGreen,
	Blue:   ItemGradeBlue,
	Yellow: ItemGradeYellow,
	Red:    ItemGradeRed,
	Purple: ItemGradePurple,
}

// ItemGradeInfo is the static metadata attached to a ItemGrade.
type ItemGradeInfo struct {
	ItemGrade
	Name  string
	Color string
}

var itemGradeInfos = map[ItemGrade]ItemGradeInfo{
	ItemGradeNone: {
		ItemGrade: ItemGradeNone,
		Name:      "none",
		Color:     "",
	},
	ItemGradeWhite: {
		ItemGrade: ItemGradeWhite,
		Name:      "white",
		Color:     "#e8eaed",
	},
	ItemGradeGreen: {
		ItemGrade: ItemGradeGreen,
		Name:      "green",
		Color:     "#7dc86e",
	},
	ItemGradeBlue: {
		ItemGrade: ItemGradeBlue,
		Name:      "blue",
		Color:     "#5b9dff",
	},
	ItemGradeYellow: {
		ItemGrade: ItemGradeYellow,
		Name:      "yellow",
		Color:     "#e6c84e",
	},
	ItemGradeRed: {
		ItemGrade: ItemGradeRed,
		Name:      "red",
		Color:     "#db4d3d",
	},
	ItemGradePurple: {
		ItemGrade: ItemGradePurple,
		Name:      "purple",
		Color:     "#c084e6",
	},
}

var itemGradeValues = []ItemGrade{
	ItemGradeNone,
	ItemGradeWhite,
	ItemGradeGreen,
	ItemGradeBlue,
	ItemGradeYellow,
	ItemGradeRed,
	ItemGradePurple,
}

var itemGradeByName = map[string]ItemGrade{
	"none":   ItemGradeNone,
	"white":  ItemGradeWhite,
	"green":  ItemGradeGreen,
	"blue":   ItemGradeBlue,
	"yellow": ItemGradeYellow,
	"red":    ItemGradeRed,
	"purple": ItemGradePurple,
}

// Values returns every declared value in declaration order.
func (c ItemGradeContainer) Values() []ItemGrade {
	out := make([]ItemGrade, len(itemGradeValues))
	copy(out, itemGradeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c ItemGradeContainer) Infos() []ItemGradeInfo {
	out := make([]ItemGradeInfo, len(itemGradeValues))
	for i, v := range itemGradeValues {
		out[i] = itemGradeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c ItemGradeContainer) Len() int {
	return len(itemGradeValues)
}

// All iterates every declared value in declaration order.
func (c ItemGradeContainer) All() iter.Seq[ItemGrade] {
	return func(yield func(ItemGrade) bool) {
		for _, v := range itemGradeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c ItemGradeContainer) FromWire(w int8) (ItemGrade, bool) {
	v := ItemGrade(w)
	_, ok := itemGradeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c ItemGradeContainer) FromWireUnsafe(w int8) ItemGrade {
	return ItemGrade(w)
}

// Parse resolves a value by name, case-insensitively.
func (c ItemGradeContainer) Parse(s string) (ItemGrade, error) {
	if v, ok := itemGradeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero ItemGrade
	return zero, fmt.Errorf("unknown ItemGrade: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v ItemGrade) TryGetInfo() (ItemGradeInfo, bool) {
	i, ok := itemGradeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v ItemGrade) Info() ItemGradeInfo {
	return itemGradeInfos[v]
}

func (v ItemGrade) Valid() bool {
	_, ok := itemGradeInfos[v]
	return ok
}

func (v ItemGrade) Wire() int8 {
	return int8(v)
}

func (v ItemGrade) Name() string {
	return itemGradeInfos[v].Name
}

func (v ItemGrade) String() string {
	if i, ok := itemGradeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("ItemGrade(%d)", int8(v))
}

func (v ItemGrade) Color() string {
	return itemGradeInfos[v].Color
}
