// Code generated by enumgen from item_types.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// ItemType is a uint8-wide identifier. The zero-cost conversion ItemType(x) is
// intentional: the underlying value is the wire value.
type ItemType uint8

const (
	ItemTypeNormal        ItemType = 0
	ItemTypeEquip         ItemType = 1
	ItemTypeSkill         ItemType = 2
	ItemTypeTent          ItemType = 3
	ItemTypeInstallation  ItemType = 4
	ItemTypeJewel         ItemType = 5
	ItemTypeCannonBall    ItemType = 6
	ItemTypeMapae         ItemType = 7
	ItemTypeMaterial      ItemType = 8
	ItemTypeInteraction   ItemType = 9
	ItemTypeContentsEvent ItemType = 10
	ItemTypeToVehicle     ItemType = 11
	ItemTypeReserved12    ItemType = 12
	ItemTypeReserved13    ItemType = 13
	ItemTypeReserved14    ItemType = 14
	ItemTypeReserved15    ItemType = 15
	ItemTypeReserved16    ItemType = 16
	ItemTypeReserved17    ItemType = 17
	ItemTypeReserved18    ItemType = 18
	ItemTypeReserved19    ItemType = 19
)

type ItemTypeContainer struct {
	Normal        ItemType
	Equip         ItemType
	Skill         ItemType
	Tent          ItemType
	Installation  ItemType
	Jewel         ItemType
	CannonBall    ItemType
	Mapae         ItemType
	Material      ItemType
	Interaction   ItemType
	ContentsEvent ItemType
	ToVehicle     ItemType
	Reserved12    ItemType
	Reserved13    ItemType
	Reserved14    ItemType
	Reserved15    ItemType
	Reserved16    ItemType
	Reserved17    ItemType
	Reserved18    ItemType
	Reserved19    ItemType
}

// ItemTypes is the entry point for the ItemType enum.
var ItemTypes = ItemTypeContainer{
	Normal:        ItemTypeNormal,
	Equip:         ItemTypeEquip,
	Skill:         ItemTypeSkill,
	Tent:          ItemTypeTent,
	Installation:  ItemTypeInstallation,
	Jewel:         ItemTypeJewel,
	CannonBall:    ItemTypeCannonBall,
	Mapae:         ItemTypeMapae,
	Material:      ItemTypeMaterial,
	Interaction:   ItemTypeInteraction,
	ContentsEvent: ItemTypeContentsEvent,
	ToVehicle:     ItemTypeToVehicle,
	Reserved12:    ItemTypeReserved12,
	Reserved13:    ItemTypeReserved13,
	Reserved14:    ItemTypeReserved14,
	Reserved15:    ItemTypeReserved15,
	Reserved16:    ItemTypeReserved16,
	Reserved17:    ItemTypeReserved17,
	Reserved18:    ItemTypeReserved18,
	Reserved19:    ItemTypeReserved19,
}

// ItemTypeInfo is the static metadata attached to a ItemType.
type ItemTypeInfo struct {
	ItemType
	Name     string
	Title    string
	Reserved bool
}

var itemTypeInfos = map[ItemType]ItemTypeInfo{
	ItemTypeNormal: {
		ItemType: ItemTypeNormal,
		Name:     "Normal",
		Title:    "General",
		Reserved: false,
	},
	ItemTypeEquip: {
		ItemType: ItemTypeEquip,
		Name:     "Equip",
		Title:    "Equipment",
		Reserved: false,
	},
	ItemTypeSkill: {
		ItemType: ItemTypeSkill,
		Name:     "Skill",
		Title:    "Consumable",
		Reserved: false,
	},
	ItemTypeTent: {
		ItemType: ItemTypeTent,
		Name:     "Tent",
		Title:    "Holding Tool",
		Reserved: false,
	},
	ItemTypeInstallation: {
		ItemType: ItemTypeInstallation,
		Name:     "Installation",
		Title:    "Installable Object",
		Reserved: false,
	},
	ItemTypeJewel: {
		ItemType: ItemTypeJewel,
		Name:     "Jewel",
		Title:    "Socket Item",
		Reserved: false,
	},
	ItemTypeCannonBall: {
		ItemType: ItemTypeCannonBall,
		Name:     "CannonBall",
		Title:    "Cannonball",
		Reserved: false,
	},
	ItemTypeMapae: {
		ItemType: ItemTypeMapae,
		Name:     "Mapae",
		Title:    "License",
		Reserved: false,
	},
	ItemTypeMaterial: {
		ItemType: ItemTypeMaterial,
		Name:     "Material",
		Title:    "Crafting Material",
		Reserved: false,
	},
	ItemTypeInteraction: {
		ItemType: ItemTypeInteraction,
		Name:     "Interaction",
		Title:    "Enter Area",
		Reserved: false,
	},
	ItemTypeContentsEvent: {
		ItemType: ItemTypeContentsEvent,
		Name:     "ContentsEvent",
		Title:    "Special Items",
		Reserved: false,
	},
	ItemTypeToVehicle: {
		ItemType: ItemTypeToVehicle,
		Name:     "ToVehicle",
		Title:    "General",
		Reserved: false,
	},
	ItemTypeReserved12: {
		ItemType: ItemTypeReserved12,
		Name:     "Reserved12",
		Title:    "General",
		Reserved: true,
	},
	ItemTypeReserved13: {
		ItemType: ItemTypeReserved13,
		Name:     "Reserved13",
		Title:    "General",
		Reserved: true,
	},
	ItemTypeReserved14: {
		ItemType: ItemTypeReserved14,
		Name:     "Reserved14",
		Title:    "General",
		Reserved: true,
	},
	ItemTypeReserved15: {
		ItemType: ItemTypeReserved15,
		Name:     "Reserved15",
		Title:    "General",
		Reserved: true,
	},
	ItemTypeReserved16: {
		ItemType: ItemTypeReserved16,
		Name:     "Reserved16",
		Title:    "General",
		Reserved: true,
	},
	ItemTypeReserved17: {
		ItemType: ItemTypeReserved17,
		Name:     "Reserved17",
		Title:    "General",
		Reserved: true,
	},
	ItemTypeReserved18: {
		ItemType: ItemTypeReserved18,
		Name:     "Reserved18",
		Title:    "General",
		Reserved: true,
	},
	ItemTypeReserved19: {
		ItemType: ItemTypeReserved19,
		Name:     "Reserved19",
		Title:    "General",
		Reserved: true,
	},
}

var itemTypeValues = []ItemType{
	ItemTypeNormal,
	ItemTypeEquip,
	ItemTypeSkill,
	ItemTypeTent,
	ItemTypeInstallation,
	ItemTypeJewel,
	ItemTypeCannonBall,
	ItemTypeMapae,
	ItemTypeMaterial,
	ItemTypeInteraction,
	ItemTypeContentsEvent,
	ItemTypeToVehicle,
	ItemTypeReserved12,
	ItemTypeReserved13,
	ItemTypeReserved14,
	ItemTypeReserved15,
	ItemTypeReserved16,
	ItemTypeReserved17,
	ItemTypeReserved18,
	ItemTypeReserved19,
}

var itemTypeByName = map[string]ItemType{
	"normal":        ItemTypeNormal,
	"equip":         ItemTypeEquip,
	"skill":         ItemTypeSkill,
	"tent":          ItemTypeTent,
	"installation":  ItemTypeInstallation,
	"jewel":         ItemTypeJewel,
	"cannonball":    ItemTypeCannonBall,
	"mapae":         ItemTypeMapae,
	"material":      ItemTypeMaterial,
	"interaction":   ItemTypeInteraction,
	"contentsevent": ItemTypeContentsEvent,
	"tovehicle":     ItemTypeToVehicle,
	"reserved12":    ItemTypeReserved12,
	"reserved13":    ItemTypeReserved13,
	"reserved14":    ItemTypeReserved14,
	"reserved15":    ItemTypeReserved15,
	"reserved16":    ItemTypeReserved16,
	"reserved17":    ItemTypeReserved17,
	"reserved18":    ItemTypeReserved18,
	"reserved19":    ItemTypeReserved19,
}

// Values returns every declared value in declaration order.
func (c ItemTypeContainer) Values() []ItemType {
	out := make([]ItemType, len(itemTypeValues))
	copy(out, itemTypeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c ItemTypeContainer) Infos() []ItemTypeInfo {
	out := make([]ItemTypeInfo, len(itemTypeValues))
	for i, v := range itemTypeValues {
		out[i] = itemTypeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c ItemTypeContainer) Len() int {
	return len(itemTypeValues)
}

// All iterates every declared value in declaration order.
func (c ItemTypeContainer) All() iter.Seq[ItemType] {
	return func(yield func(ItemType) bool) {
		for _, v := range itemTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c ItemTypeContainer) FromWire(w uint8) (ItemType, bool) {
	v := ItemType(w)
	_, ok := itemTypeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c ItemTypeContainer) FromWireUnsafe(w uint8) ItemType {
	return ItemType(w)
}

// Parse resolves a value by name, case-insensitively.
func (c ItemTypeContainer) Parse(s string) (ItemType, error) {
	if v, ok := itemTypeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero ItemType
	return zero, fmt.Errorf("unknown ItemType: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v ItemType) TryGetInfo() (ItemTypeInfo, bool) {
	i, ok := itemTypeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v ItemType) Info() ItemTypeInfo {
	return itemTypeInfos[v]
}

func (v ItemType) Valid() bool {
	_, ok := itemTypeInfos[v]
	return ok
}

func (v ItemType) Wire() uint8 {
	return uint8(v)
}

func (v ItemType) Name() string {
	return itemTypeInfos[v].Name
}

func (v ItemType) String() string {
	if i, ok := itemTypeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("ItemType(%d)", uint8(v))
}

func (v ItemType) Title() string {
	return itemTypeInfos[v].Title
}

func (v ItemType) Reserved() bool {
	return itemTypeInfos[v].Reserved
}
