// Code generated by enumgen from life_skill_grades.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// LifeSkillGrade is a int8-wide identifier. The zero-cost conversion LifeSkillGrade(x) is
// intentional: the underlying value is the wire value.
type LifeSkillGrade int8

const (
	LifeSkillGradeUnknown      LifeSkillGrade = -1
	LifeSkillGradeBeginner     LifeSkillGrade = 0
	LifeSkillGradeApprentice   LifeSkillGrade = 1
	LifeSkillGradeSkilled      LifeSkillGrade = 2
	LifeSkillGradeProfessional LifeSkillGrade = 3
	LifeSkillGradeArtisan      LifeSkillGrade = 4
	LifeSkillGradeMaster       LifeSkillGrade = 5
	LifeSkillGradeGuru         LifeSkillGrade = 6
	LifeSkillGradeCount        LifeSkillGrade = 7
)

type LifeSkillGradeContainer struct {
	Unknown      LifeSkillGrade
	Beginner     LifeSkillGrade
	Apprentice   LifeSkillGrade
	Skilled      LifeSkillGrade
	Professional LifeSkillGrade
	Artisan      LifeSkillGrade
	Master       LifeSkillGrade
	Guru         LifeSkillGrade
}

// LifeSkillGrades is the entry point for the LifeSkillGrade enum.
var LifeSkillGrades = LifeSkillGradeContainer{
	Unknown:      LifeSkillGradeUnknown,
	Beginner:     LifeSkillGradeBeginner,
	Apprentice:   LifeSkillGradeApprentice,
	Skilled:      LifeSkillGradeSkilled,
	Professional: LifeSkillGradeProfessional,
	Artisan:      LifeSkillGradeArtisan,
	Master:       LifeSkillGradeMaster,
	Guru:         LifeSkillGradeGuru,
}

// LifeSkillGradeInfo is the static metadata attached to a LifeSkillGrade.
type LifeSkillGradeInfo struct {
	LifeSkillGrade
	Name     string
	Title    string
	Reserved bool
	MinLevel int
	MaxLevel int
}

var lifeSkillGradeInfos = map[LifeSkillGrade]LifeSkillGradeInfo{
	LifeSkillGradeUnknown: {
		LifeSkillGrade: LifeSkillGradeUnknown,
		Name:           "Unknown",
		Title:          "Unknown",
		Reserved:       true,
		MinLevel:       0,
		MaxLevel:       0,
	},
	LifeSkillGradeBeginner: {
		LifeSkillGrade: LifeSkillGradeBeginner,
		Name:           "Beginner",
		Title:          "Beginner",
		Reserved:       false,
		MinLevel:       1,
		MaxLevel:       10,
	},
	LifeSkillGradeApprentice: {
		LifeSkillGrade: LifeSkillGradeApprentice,
		Name:           "Apprentice",
		Title:          "Apprentice",
		Reserved:       false,
		MinLevel:       11,
		MaxLevel:       20,
	},
	LifeSkillGradeSkilled: {
		LifeSkillGrade: LifeSkillGradeSkilled,
		Name:           "Skilled",
		Title:          "Skilled",
		Reserved:       false,
		MinLevel:       21,
		MaxLevel:       30,
	},
	LifeSkillGradeProfessional: {
		LifeSkillGrade: LifeSkillGradeProfessional,
		Name:           "Professional",
		Title:          "Professional",
		Reserved:       false,
		MinLevel:       31,
		MaxLevel:       40,
	},
	LifeSkillGradeArtisan: {
		LifeSkillGrade: LifeSkillGradeArtisan,
		Name:           "Artisan",
		Title:          "Artisan",
		Reserved:       false,
		MinLevel:       41,
		MaxLevel:       50,
	},
	LifeSkillGradeMaster: {
		LifeSkillGrade: LifeSkillGradeMaster,
		Name:           "Master",
		Title:          "Master",
		Reserved:       false,
		MinLevel:       51,
		MaxLevel:       80,
	},
	LifeSkillGradeGuru: {
		LifeSkillGrade: LifeSkillGradeGuru,
		Name:           "Guru",
		Title:          "Guru",
		Reserved:       false,
		MinLevel:       81,
		MaxLevel:       180,
	},
}

var lifeSkillGradeValues = []LifeSkillGrade{
	LifeSkillGradeUnknown,
	LifeSkillGradeBeginner,
	LifeSkillGradeApprentice,
	LifeSkillGradeSkilled,
	LifeSkillGradeProfessional,
	LifeSkillGradeArtisan,
	LifeSkillGradeMaster,
	LifeSkillGradeGuru,
}

var lifeSkillGradeByName = map[string]LifeSkillGrade{
	"unknown":      LifeSkillGradeUnknown,
	"beginner":     LifeSkillGradeBeginner,
	"apprentice":   LifeSkillGradeApprentice,
	"skilled":      LifeSkillGradeSkilled,
	"professional": LifeSkillGradeProfessional,
	"artisan":      LifeSkillGradeArtisan,
	"master":       LifeSkillGradeMaster,
	"guru":         LifeSkillGradeGuru,
}

// Values returns every declared value in declaration order.
func (c LifeSkillGradeContainer) Values() []LifeSkillGrade {
	out := make([]LifeSkillGrade, len(lifeSkillGradeValues))
	copy(out, lifeSkillGradeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c LifeSkillGradeContainer) Infos() []LifeSkillGradeInfo {
	out := make([]LifeSkillGradeInfo, len(lifeSkillGradeValues))
	for i, v := range lifeSkillGradeValues {
		out[i] = lifeSkillGradeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c LifeSkillGradeContainer) Len() int {
	return len(lifeSkillGradeValues)
}

// All iterates every declared value in declaration order.
func (c LifeSkillGradeContainer) All() iter.Seq[LifeSkillGrade] {
	return func(yield func(LifeSkillGrade) bool) {
		for _, v := range lifeSkillGradeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c LifeSkillGradeContainer) FromWire(w int8) (LifeSkillGrade, bool) {
	v := LifeSkillGrade(w)
	_, ok := lifeSkillGradeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c LifeSkillGradeContainer) FromWireUnsafe(w int8) LifeSkillGrade {
	return LifeSkillGrade(w)
}

// Parse resolves a value by name, case-insensitively.
func (c LifeSkillGradeContainer) Parse(s string) (LifeSkillGrade, error) {
	if v, ok := lifeSkillGradeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero LifeSkillGrade
	return zero, fmt.Errorf("unknown LifeSkillGrade: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v LifeSkillGrade) TryGetInfo() (LifeSkillGradeInfo, bool) {
	i, ok := lifeSkillGradeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v LifeSkillGrade) Info() LifeSkillGradeInfo {
	return lifeSkillGradeInfos[v]
}

func (v LifeSkillGrade) Valid() bool {
	_, ok := lifeSkillGradeInfos[v]
	return ok
}

func (v LifeSkillGrade) Wire() int8 {
	return int8(v)
}

func (v LifeSkillGrade) Name() string {
	return lifeSkillGradeInfos[v].Name
}

func (v LifeSkillGrade) String() string {
	if i, ok := lifeSkillGradeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("LifeSkillGrade(%d)", int8(v))
}

func (v LifeSkillGrade) Title() string {
	return lifeSkillGradeInfos[v].Title
}

func (v LifeSkillGrade) Reserved() bool {
	return lifeSkillGradeInfos[v].Reserved
}

func (v LifeSkillGrade) MinLevel() int {
	return lifeSkillGradeInfos[v].MinLevel
}

func (v LifeSkillGrade) MaxLevel() int {
	return lifeSkillGradeInfos[v].MaxLevel
}
