// Code generated by enumgen from life_skill_types.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// LifeSkillType is a uint8-wide identifier. The zero-cost conversion LifeSkillType(x) is
// intentional: the underlying value is the wire value.
type LifeSkillType uint8

const (
	LifeSkillTypeGathering  LifeSkillType = 0
	LifeSkillTypeFishing    LifeSkillType = 1
	LifeSkillTypeHunting    LifeSkillType = 2
	LifeSkillTypeCooking    LifeSkillType = 3
	LifeSkillTypeAlchemy    LifeSkillType = 4
	LifeSkillTypeProcessing LifeSkillType = 5
	LifeSkillTypeTraining   LifeSkillType = 6
	LifeSkillTypeTrading    LifeSkillType = 7
	LifeSkillTypeFarming    LifeSkillType = 8
	LifeSkillTypeSailing    LifeSkillType = 9
	LifeSkillTypeQuest      LifeSkillType = 10
	LifeSkillTypeBartering  LifeSkillType = 11
	LifeSkillTypeReserved12 LifeSkillType = 12
	LifeSkillTypeReserved13 LifeSkillType = 13
	LifeSkillTypeReserved14 LifeSkillType = 14
	LifeSkillTypeCount      LifeSkillType = 15
)

type LifeSkillTypeContainer struct {
	Gathering  LifeSkillType
	Fishing    LifeSkillType
	Hunting    LifeSkillType
	Cooking    LifeSkillType
	Alchemy    LifeSkillType
	Processing LifeSkillType
	Training   LifeSkillType
	Trading    LifeSkillType
	Farming    LifeSkillType
	Sailing    LifeSkillType
	Quest      LifeSkillType
	Bartering  LifeSkillType
	Reserved12 LifeSkillType
	Reserved13 LifeSkillType
	Reserved14 LifeSkillType
}

// LifeSkillTypes is the entry point for the LifeSkillType enum.
var LifeSkillTypes = LifeSkillTypeContainer{
	Gathering:  LifeSkillTypeGathering,
	Fishing:    LifeSkillTypeFishing,
	Hunting:    LifeSkillTypeHunting,
	Cooking:    LifeSkillTypeCooking,
	Alchemy:    LifeSkillTypeAlchemy,
	Processing: LifeSkillTypeProcessing,
	Training:   LifeSkillTypeTraining,
	Trading:    LifeSkillTypeTrading,
	Farming:    LifeSkillTypeFarming,
	Sailing:    LifeSkillTypeSailing,
	Quest:      LifeSkillTypeQuest,
	Bartering:  LifeSkillTypeBartering,
	Reserved12: LifeSkillTypeReserved12,
	Reserved13: LifeSkillTypeReserved13,
	Reserved14: LifeSkillTypeReserved14,
}

// LifeSkillTypeInfo is the static metadata attached to a LifeSkillType.
type LifeSkillTypeInfo struct {
	LifeSkillType
	Name        string
	Title       string
	NativeName  string
	Playable    bool
	MasteryStat StatId
	Reserved    bool
}

var lifeSkillTypeInfos = map[LifeSkillType]LifeSkillTypeInfo{
	LifeSkillTypeGathering: {
		LifeSkillType: LifeSkillTypeGathering,
		Name:          "Gathering",
		Title:         "Gathering",
		NativeName:    "gathering",
		Playable:      true,
		MasteryStat:   StatIdGatheringMastery,
		Reserved:      false,
	},
	LifeSkillTypeFishing: {
		LifeSkillType: LifeSkillTypeFishing,
		Name:          "Fishing",
		Title:         "Fishing",
		NativeName:    "fishing",
		Playable:      true,
		MasteryStat:   StatIdFishingMastery,
		Reserved:      false,
	},
	LifeSkillTypeHunting: {
		LifeSkillType: LifeSkillTypeHunting,
		Name:          "Hunting",
		Title:         "Hunting",
		NativeName:    "hunting",
		Playable:      true,
		MasteryStat:   StatIdHuntingMastery,
		Reserved:      false,
	},
	LifeSkillTypeCooking: {
		LifeSkillType: LifeSkillTypeCooking,
		Name:          "Cooking",
		Title:         "Cooking",
		NativeName:    "cooking",
		Playable:      true,
		MasteryStat:   StatIdCookingMastery,
		Reserved:      false,
	},
	LifeSkillTypeAlchemy: {
		LifeSkillType: LifeSkillTypeAlchemy,
		Name:          "Alchemy",
		Title:         "Alchemy",
		NativeName:    "alchemy",
		Playable:      true,
		MasteryStat:   StatIdAlchemyMastery,
		Reserved:      false,
	},
	LifeSkillTypeProcessing: {
		LifeSkillType: LifeSkillTypeProcessing,
		Name:          "Processing",
		Title:         "Processing",
		NativeName:    "processing",
		Playable:      true,
		MasteryStat:   StatIdProcessingMastery,
		Reserved:      false,
	},
	LifeSkillTypeTraining: {
		LifeSkillType: LifeSkillTypeTraining,
		Name:          "Training",
		Title:         "Training",
		NativeName:    "training",
		Playable:      true,
		MasteryStat:   StatIdTrainingMastery,
		Reserved:      false,
	},
	LifeSkillTypeTrading: {
		LifeSkillType: LifeSkillTypeTrading,
		Name:          "Trading",
		Title:         "Trading",
		NativeName:    "trading",
		Playable:      true,
		MasteryStat:   StatIdTradingMastery,
		Reserved:      false,
	},
	LifeSkillTypeFarming: {
		LifeSkillType: LifeSkillTypeFarming,
		Name:          "Farming",
		Title:         "Farming",
		NativeName:    "farming",
		Playable:      true,
		MasteryStat:   StatIdFarmingMastery,
		Reserved:      false,
	},
	LifeSkillTypeSailing: {
		LifeSkillType: LifeSkillTypeSailing,
		Name:          "Sailing",
		Title:         "Sailing",
		NativeName:    "sailing",
		Playable:      true,
		MasteryStat:   StatIdSailingMastery,
		Reserved:      false,
	},
	LifeSkillTypeQuest: {
		LifeSkillType: LifeSkillTypeQuest,
		Name:          "Quest",
		Title:         "Quest",
		NativeName:    "quest",
		Playable:      false,
		Reserved:      false,
	},
	LifeSkillTypeBartering: {
		LifeSkillType: LifeSkillTypeBartering,
		Name:          "Bartering",
		Title:         "Bartering",
		NativeName:    "bartering",
		Playable:      true,
		Reserved:      false,
	},
	LifeSkillTypeReserved12: {
		LifeSkillType: LifeSkillTypeReserved12,
		Name:          "Reserved12",
		Title:         "Temp",
		NativeName:    "temp2",
		Playable:      false,
		Reserved:      true,
	},
	LifeSkillTypeReserved13: {
		LifeSkillType: LifeSkillTypeReserved13,
		Name:          "Reserved13",
		Title:         "Temp",
		NativeName:    "temp3",
		Playable:      false,
		Reserved:      true,
	},
	LifeSkillTypeReserved14: {
		LifeSkillType: LifeSkillTypeReserved14,
		Name:          "Reserved14",
		Title:         "Temp",
		NativeName:    "temp4",
		Playable:      false,
		Reserved:      true,
	},
}

var lifeSkillTypeValues = []LifeSkillType{
	LifeSkillTypeGathering,
	LifeSkillTypeFishing,
	LifeSkillTypeHunting,
	LifeSkillTypeCooking,
	LifeSkillTypeAlchemy,
	LifeSkillTypeProcessing,
	LifeSkillTypeTraining,
	LifeSkillTypeTrading,
	LifeSkillTypeFarming,
	LifeSkillTypeSailing,
	LifeSkillTypeQuest,
	LifeSkillTypeBartering,
	LifeSkillTypeReserved12,
	LifeSkillTypeReserved13,
	LifeSkillTypeReserved14,
}

var lifeSkillTypeByName = map[string]LifeSkillType{
	"gathering":  LifeSkillTypeGathering,
	"fishing":    LifeSkillTypeFishing,
	"hunting":    LifeSkillTypeHunting,
	"cooking":    LifeSkillTypeCooking,
	"alchemy":    LifeSkillTypeAlchemy,
	"processing": LifeSkillTypeProcessing,
	"training":   LifeSkillTypeTraining,
	"trading":    LifeSkillTypeTrading,
	"farming":    LifeSkillTypeFarming,
	"sailing":    LifeSkillTypeSailing,
	"quest":      LifeSkillTypeQuest,
	"bartering":  LifeSkillTypeBartering,
	"reserved12": LifeSkillTypeReserved12,
	"reserved13": LifeSkillTypeReserved13,
	"reserved14": LifeSkillTypeReserved14,
}

// Values returns every declared value in declaration order.
func (c LifeSkillTypeContainer) Values() []LifeSkillType {
	out := make([]LifeSkillType, len(lifeSkillTypeValues))
	copy(out, lifeSkillTypeValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c LifeSkillTypeContainer) Infos() []LifeSkillTypeInfo {
	out := make([]LifeSkillTypeInfo, len(lifeSkillTypeValues))
	for i, v := range lifeSkillTypeValues {
		out[i] = lifeSkillTypeInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c LifeSkillTypeContainer) Len() int {
	return len(lifeSkillTypeValues)
}

// All iterates every declared value in declaration order.
func (c LifeSkillTypeContainer) All() iter.Seq[LifeSkillType] {
	return func(yield func(LifeSkillType) bool) {
		for _, v := range lifeSkillTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c LifeSkillTypeContainer) FromWire(w uint8) (LifeSkillType, bool) {
	v := LifeSkillType(w)
	_, ok := lifeSkillTypeInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c LifeSkillTypeContainer) FromWireUnsafe(w uint8) LifeSkillType {
	return LifeSkillType(w)
}

// Parse resolves a value by name, case-insensitively.
func (c LifeSkillTypeContainer) Parse(s string) (LifeSkillType, error) {
	if v, ok := lifeSkillTypeByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero LifeSkillType
	return zero, fmt.Errorf("unknown LifeSkillType: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v LifeSkillType) TryGetInfo() (LifeSkillTypeInfo, bool) {
	i, ok := lifeSkillTypeInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v LifeSkillType) Info() LifeSkillTypeInfo {
	return lifeSkillTypeInfos[v]
}

func (v LifeSkillType) Valid() bool {
	_, ok := lifeSkillTypeInfos[v]
	return ok
}

func (v LifeSkillType) Wire() uint8 {
	return uint8(v)
}

func (v LifeSkillType) Name() string {
	return lifeSkillTypeInfos[v].Name
}

func (v LifeSkillType) String() string {
	if i, ok := lifeSkillTypeInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("LifeSkillType(%d)", uint8(v))
}

func (v LifeSkillType) Title() string {
	return lifeSkillTypeInfos[v].Title
}

func (v LifeSkillType) NativeName() string {
	return lifeSkillTypeInfos[v].NativeName
}

func (v LifeSkillType) Playable() bool {
	return lifeSkillTypeInfos[v].Playable
}

func (v LifeSkillType) MasteryStat() StatId {
	return lifeSkillTypeInfos[v].MasteryStat
}

func (v LifeSkillType) Reserved() bool {
	return lifeSkillTypeInfos[v].Reserved
}
