// Code generated by enumgen from skill_kinds.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// SkillKind is a uint32-wide identifier. The zero-cost conversion SkillKind(x) is
// intentional: the underlying value is the wire value.
type SkillKind uint32

const (
	SkillKindUnknown SkillKind = 0
	SkillKindActive  SkillKind = 1
	SkillKindPassive SkillKind = 2
)

type SkillKindContainer struct {
	Unknown SkillKind
	Active  SkillKind
	Passive SkillKind
}

// SkillKinds is the entry point for the SkillKind enum.
var SkillKinds = SkillKindContainer{
	Unknown: SkillKindUnknown,
	Active:  SkillKindActive,
	Passive: SkillKindPassive,
}

// SkillKindInfo is the static metadata attached to a SkillKind.
type SkillKindInfo struct {
	SkillKind
	Name  string
	Title string
}

var skillKindInfos = map[SkillKind]SkillKindInfo{
	SkillKindUnknown: {
		SkillKind: SkillKindUnknown,
		Name:      "Unknown",
		Title:     "Unknown",
	},
	SkillKindActive: {
		SkillKind: SkillKindActive,
		Name:      "Active",
		Title:     "Active",
	},
	SkillKindPassive: {
		SkillKind: SkillKindPassive,
		Name:      "Passive",
		Title:     "Passive",
	},
}

var skillKindValues = []SkillKind{
	SkillKindUnknown,
	SkillKindActive,
	SkillKindPassive,
}

var skillKindByName = map[string]SkillKind{
	"unknown": SkillKindUnknown,
	"active":  SkillKindActive,
	"passive": SkillKindPassive,
}

// Values returns every declared value in declaration order.
func (c SkillKindContainer) Values() []SkillKind {
	out := make([]SkillKind, len(skillKindValues))
	copy(out, skillKindValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c SkillKindContainer) Infos() []SkillKindInfo {
	out := make([]SkillKindInfo, len(skillKindValues))
	for i, v := range skillKindValues {
		out[i] = skillKindInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c SkillKindContainer) Len() int {
	return len(skillKindValues)
}

// All iterates every declared value in declaration order.
func (c SkillKindContainer) All() iter.Seq[SkillKind] {
	return func(yield func(SkillKind) bool) {
		for _, v := range skillKindValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c SkillKindContainer) FromWire(w uint32) (SkillKind, bool) {
	v := SkillKind(w)
	_, ok := skillKindInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c SkillKindContainer) FromWireUnsafe(w uint32) SkillKind {
	return SkillKind(w)
}

// Parse resolves a value by name, case-insensitively.
func (c SkillKindContainer) Parse(s string) (SkillKind, error) {
	if v, ok := skillKindByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero SkillKind
	return zero, fmt.Errorf("unknown SkillKind: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v SkillKind) TryGetInfo() (SkillKindInfo, bool) {
	i, ok := skillKindInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v SkillKind) Info() SkillKindInfo {
	return skillKindInfos[v]
}

func (v SkillKind) Valid() bool {
	_, ok := skillKindInfos[v]
	return ok
}

func (v SkillKind) Wire() uint32 {
	return uint32(v)
}

func (v SkillKind) Name() string {
	return skillKindInfos[v].Name
}

func (v SkillKind) String() string {
	if i, ok := skillKindInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("SkillKind(%d)", uint32(v))
}

func (v SkillKind) Title() string {
	return skillKindInfos[v].Title
}
