// Code generated by enumgen from item_slots.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// SlotName is a byte-wide identifier. The zero-cost conversion SlotName(x) is
// intentional: the underlying value is the wire value.
type SlotName byte

const (
	SlotNameMainWeapon             SlotName = 0
	SlotNameSubWeapon              SlotName = 1
	SlotNameFishingChair           SlotName = 2
	SlotNameArmor                  SlotName = 3
	SlotNameGloves                 SlotName = 4
	SlotNameShoes                  SlotName = 5
	SlotNameHelmet                 SlotName = 6
	SlotNameNecklace               SlotName = 7
	SlotNameRingI                  SlotName = 8
	SlotNameRingII                 SlotName = 9
	SlotNameEarringI               SlotName = 10
	SlotNameEarringII              SlotName = 11
	SlotNameBelt                   SlotName = 12
	SlotNameLantern                SlotName = 13
	SlotNameCostumeArmor           SlotName = 14
	SlotNameCostumeGloves          SlotName = 15
	SlotNameCostumeShoes           SlotName = 16
	SlotNameCostumeHelmet          SlotName = 17
	SlotNameCostumeMainWeapon      SlotName = 18
	SlotNameCostumeSubWeapon       SlotName = 19
	SlotNameUnderwear              SlotName = 20
	SlotNameCostumeEarring         SlotName = 21
	SlotNameCostumeHeadpiece       SlotName = 22
	SlotNameCostumePiercing        SlotName = 23
	SlotNameShipGear               SlotName = 25
	SlotNameShipGear2              SlotName = 26
	SlotNameAlchemyStone           SlotName = 27
	SlotNameAwakeningWeapon        SlotName = 29
	SlotNameCostumeAwakeningWeapon SlotName = 30
	SlotNameTome                   SlotName = 31
	SlotNameArtifactI              SlotName = 32
	SlotNameArtifactII             SlotName = 33
	SlotNameLumberingAxe           SlotName = 34
	SlotNameFluidCollector         SlotName = 35
	SlotNameHoe                    SlotName = 36
	SlotNameButcherKnife           SlotName = 37
	SlotNameTanningKnife           SlotName = 38
	SlotNamePickaxe                SlotName = 39
	SlotNameFishingRod             SlotName = 40
	SlotNameFishingFloat           SlotName = 41
	SlotNameFishingHarpoon         SlotName = 42
	SlotNameGatheringCarrier       SlotName = 45
	SlotNameNone                   SlotName = 46
	SlotNameMAX                    SlotName = 47
)

type SlotNameContainer struct {
	MainWeapon             SlotName
	SubWeapon              SlotName
	FishingChair           SlotName
	Armor                  SlotName
	Gloves                 SlotName
	Shoes                  SlotName
	Helmet                 SlotName
	Necklace               SlotName
	RingI                  SlotName
	RingII                 SlotName
	EarringI               SlotName
	EarringII              SlotName
	Belt                   SlotName
	Lantern                SlotName
	CostumeArmor           SlotName
	CostumeGloves          SlotName
	CostumeShoes           SlotName
	CostumeHelmet          SlotName
	CostumeMainWeapon      SlotName
	CostumeSubWeapon       SlotName
	Underwear              SlotName
	CostumeEarring         SlotName
	CostumeHeadpiece       SlotName
	CostumePiercing        SlotName
	ShipGear               SlotName
	ShipGear2              SlotName
	AlchemyStone           SlotName
	AwakeningWeapon        SlotName
	CostumeAwakeningWeapon SlotName
	Tome                   SlotName
	ArtifactI              SlotName
	ArtifactII             SlotName
	LumberingAxe           SlotName
	FluidCollector         SlotName
	Hoe                    SlotName
	ButcherKnife           SlotName
	TanningKnife           SlotName
	Pickaxe                SlotName
	FishingRod             SlotName
	FishingFloat           SlotName
	FishingHarpoon         SlotName
	GatheringCarrier       SlotName
	None                   SlotName
}

// SlotNames is the entry point for the SlotName enum.
var SlotNames = SlotNameContainer{
	MainWeapon:             SlotNameMainWeapon,
	SubWeapon:              SlotNameSubWeapon,
	FishingChair:           SlotNameFishingChair,
	Armor:                  SlotNameArmor,
	Gloves:                 SlotNameGloves,
	Shoes:                  SlotNameShoes,
	Helmet:                 SlotNameHelmet,
	Necklace:               SlotNameNecklace,
	RingI:                  SlotNameRingI,
	RingII:                 SlotNameRingII,
	EarringI:               SlotNameEarringI,
	EarringII:              SlotNameEarringII,
	Belt:                   SlotNameBelt,
	Lantern:                SlotNameLantern,
	CostumeArmor:           SlotNameCostumeArmor,
	CostumeGloves:          SlotNameCostumeGloves,
	CostumeShoes:           SlotNameCostumeShoes,
	CostumeHelmet:          SlotNameCostumeHelmet,
	CostumeMainWeapon:      SlotNameCostumeMainWeapon,
	CostumeSubWeapon:       SlotNameCostumeSubWeapon,
	Underwear:              SlotNameUnderwear,
	CostumeEarring:         SlotNameCostumeEarring,
	CostumeHeadpiece:       SlotNameCostumeHeadpiece,
	CostumePiercing:        SlotNameCostumePiercing,
	ShipGear:               SlotNameShipGear,
	ShipGear2:              SlotNameShipGear2,
	AlchemyStone:           SlotNameAlchemyStone,
	AwakeningWeapon:        SlotNameAwakeningWeapon,
	CostumeAwakeningWeapon: SlotNameCostumeAwakeningWeapon,
	Tome:                   SlotNameTome,
	ArtifactI:              SlotNameArtifactI,
	ArtifactII:             SlotNameArtifactII,
	LumberingAxe:           SlotNameLumberingAxe,
	FluidCollector:         SlotNameFluidCollector,
	Hoe:                    SlotNameHoe,
	ButcherKnife:           SlotNameButcherKnife,
	TanningKnife:           SlotNameTanningKnife,
	Pickaxe:                SlotNamePickaxe,
	FishingRod:             SlotNameFishingRod,
	FishingFloat:           SlotNameFishingFloat,
	FishingHarpoon:         SlotNameFishingHarpoon,
	GatheringCarrier:       SlotNameGatheringCarrier,
	None:                   SlotNameNone,
}

// SlotNameInfo is the static metadata attached to a SlotName.
type SlotNameInfo struct {
	SlotName
	Name      string
	Title     string
	Desc      string
	OtherSlot int
}

var slotNameInfos = map[SlotName]SlotNameInfo{
	SlotNameMainWeapon: {
		SlotName:  SlotNameMainWeapon,
		Name:      "MainWeapon",
		Title:     "Main Weapon",
		Desc:      "RightHand",
		OtherSlot: 0,
	},
	SlotNameSubWeapon: {
		SlotName:  SlotNameSubWeapon,
		Name:      "SubWeapon",
		Title:     "Sub-weapon",
		Desc:      "LeftHand",
		OtherSlot: 0,
	},
	SlotNameFishingChair: {
		SlotName:  SlotNameFishingChair,
		Name:      "FishingChair",
		Title:     "Tool",
		Desc:      "(life-tool seat; GatheringTools)",
		OtherSlot: 0,
	},
	SlotNameArmor: {
		SlotName:  SlotNameArmor,
		Name:      "Armor",
		Title:     "Armor",
		Desc:      "Chest",
		OtherSlot: 0,
	},
	SlotNameGloves: {
		SlotName:  SlotNameGloves,
		Name:      "Gloves",
		Title:     "Gloves",
		Desc:      "Glove",
		OtherSlot: 0,
	},
	SlotNameShoes: {
		SlotName:  SlotNameShoes,
		Name:      "Shoes",
		Title:     "Shoes",
		Desc:      "Boots",
		OtherSlot: 0,
	},
	SlotNameHelmet: {
		SlotName:  SlotNameHelmet,
		Name:      "Helmet",
		Title:     "Helmet",
		Desc:      "Helm",
		OtherSlot: 0,
	},
	SlotNameNecklace: {
		SlotName:  SlotNameNecklace,
		Name:      "Necklace",
		Title:     "Necklace",
		Desc:      "Necklace",
		OtherSlot: 0,
	},
	SlotNameRingI: {
		SlotName:  SlotNameRingI,
		Name:      "RingI",
		Title:     "Ring I",
		Desc:      "Ring1",
		OtherSlot: 0,
	},
	SlotNameRingII: {
		SlotName:  SlotNameRingII,
		Name:      "RingII",
		Title:     "Ring II",
		Desc:      "Ring2",
		OtherSlot: 8,
	},
	SlotNameEarringI: {
		SlotName:  SlotNameEarringI,
		Name:      "EarringI",
		Title:     "Earring I",
		Desc:      "Earing1",
		OtherSlot: 0,
	},
	SlotNameEarringII: {
		SlotName:  SlotNameEarringII,
		Name:      "EarringII",
		Title:     "Earring II",
		Desc:      "Earing1",
		OtherSlot: 10,
	},
	SlotNameBelt: {
		SlotName:  SlotNameBelt,
		Name:      "Belt",
		Title:     "Belt",
		Desc:      "Belt",
		OtherSlot: 0,
	},
	SlotNameLantern: {
		SlotName:  SlotNameLantern,
		Name:      "Lantern",
		Title:     "Lantern",
		Desc:      "Lantern",
		OtherSlot: 0,
	},
	SlotNameCostumeArmor: {
		SlotName:  SlotNameCostumeArmor,
		Name:      "CostumeArmor",
		Title:     "Costume: Armor",
		Desc:      "AvatarChest",
		OtherSlot: 0,
	},
	SlotNameCostumeGloves: {
		SlotName:  SlotNameCostumeGloves,
		Name:      "CostumeGloves",
		Title:     "Costume: Gloves",
		Desc:      "AvatarGlove",
		OtherSlot: 0,
	},
	SlotNameCostumeShoes: {
		SlotName:  SlotNameCostumeShoes,
		Name:      "CostumeShoes",
		Title:     "Costume: Shoes",
		Desc:      "AvatarBoots",
		OtherSlot: 0,
	},
	SlotNameCostumeHelmet: {
		SlotName:  SlotNameCostumeHelmet,
		Name:      "CostumeHelmet",
		Title:     "Costume: Helmet",
		Desc:      "AvatarHelm",
		OtherSlot: 0,
	},
	SlotNameCostumeMainWeapon: {
		SlotName:  SlotNameCostumeMainWeapon,
		Name:      "CostumeMainWeapon",
		Title:     "Costume: Main Weapon",
		Desc:      "AvatarWeapon",
		OtherSlot: 0,
	},
	SlotNameCostumeSubWeapon: {
		SlotName:  SlotNameCostumeSubWeapon,
		Name:      "CostumeSubWeapon",
		Title:     "Costume: Sub-weapon",
		Desc:      "AvatarSubWeapon",
		OtherSlot: 0,
	},
	SlotNameUnderwear: {
		SlotName:  SlotNameUnderwear,
		Name:      "Underwear",
		Title:     "Underwear",
		Desc:      "AvatarUnderwear",
		OtherSlot: 0,
	},
	SlotNameCostumeEarring: {
		SlotName:  SlotNameCostumeEarring,
		Name:      "CostumeEarring",
		Title:     "Head & Ear",
		Desc:      "Bottom slot head and ears accessory",
		OtherSlot: 0,
	},
	SlotNameCostumeHeadpiece: {
		SlotName:  SlotNameCostumeHeadpiece,
		Name:      "CostumeHeadpiece",
		Title:     "Eye",
		Desc:      "Bottom slot eyes(typically glasses)",
		OtherSlot: 0,
	},
	SlotNameCostumePiercing: {
		SlotName:  SlotNameCostumePiercing,
		Name:      "CostumePiercing",
		Title:     "Nose, Mouth, Chin",
		Desc:      "Bottom slot nose, mouth, chin accessory",
		OtherSlot: 0,
	},
	SlotNameShipGear: {
		SlotName:  SlotNameShipGear,
		Name:      "ShipGear",
		Title:     "ShipGear",
		Desc:      "(mount/ship equipment)",
		OtherSlot: 0,
	},
	SlotNameShipGear2: {
		SlotName:  SlotNameShipGear2,
		Name:      "ShipGear2",
		Title:     "ShipGear",
		Desc:      "(mount/ship equipment)",
		OtherSlot: 0,
	},
	SlotNameAlchemyStone: {
		SlotName:  SlotNameAlchemyStone,
		Name:      "AlchemyStone",
		Title:     "Alchemy Stone",
		Desc:      "AlchemyStone",
		OtherSlot: 0,
	},
	SlotNameAwakeningWeapon: {
		SlotName:  SlotNameAwakeningWeapon,
		Name:      "AwakeningWeapon",
		Title:     "Awakening Weapon",
		Desc:      "AwakenWeapon",
		OtherSlot: 0,
	},
	SlotNameCostumeAwakeningWeapon: {
		SlotName:  SlotNameCostumeAwakeningWeapon,
		Name:      "CostumeAwakeningWeapon",
		Title:     "Costume: Awakening Weapon",
		Desc:      "AvatarAwakenWeapon",
		OtherSlot: 0,
	},
	SlotNameTome: {
		SlotName:  SlotNameTome,
		Name:      "Tome",
		Title:     "Tome",
		Desc:      "QuestBook",
		OtherSlot: 0,
	},
	SlotNameArtifactI: {
		SlotName:  SlotNameArtifactI,
		Name:      "ArtifactI",
		Title:     "Artifact I",
		Desc:      "Artifact1",
		OtherSlot: 0,
	},
	SlotNameArtifactII: {
		SlotName:  SlotNameArtifactII,
		Name:      "ArtifactII",
		Title:     "Artifact II",
		Desc:      "Artifact2",
		OtherSlot: 32,
	},
	SlotNameLumberingAxe: {
		SlotName:  SlotNameLumberingAxe,
		Name:      "LumberingAxe",
		Title:     "Lumbering Axe",
		Desc:      "Axe",
		OtherSlot: 0,
	},
	SlotNameFluidCollector: {
		SlotName:  SlotNameFluidCollector,
		Name:      "FluidCollector",
		Title:     "Fluid Collector",
		Desc:      "Syringe",
		OtherSlot: 0,
	},
	SlotNameHoe: {
		SlotName:  SlotNameHoe,
		Name:      "Hoe",
		Title:     "Hoe",
		Desc:      "Hoe",
		OtherSlot: 0,
	},
	SlotNameButcherKnife: {
		SlotName:  SlotNameButcherKnife,
		Name:      "ButcherKnife",
		Title:     "Butcher Knife",
		Desc:      "ButcheryKnife",
		OtherSlot: 0,
	},
	SlotNameTanningKnife: {
		SlotName:  SlotNameTanningKnife,
		Name:      "TanningKnife",
		Title:     "Tanning Knife",
		Desc:      "SkinKnife",
		OtherSlot: 0,
	},
	SlotNamePickaxe: {
		SlotName:  SlotNamePickaxe,
		Name:      "Pickaxe",
		Title:     "Pickaxe",
		Desc:      "PickAx",
		OtherSlot: 0,
	},
	SlotNameFishingRod: {
		SlotName:  SlotNameFishingRod,
		Name:      "FishingRod",
		Title:     "Fishing Rod",
		Desc:      "FishingRod",
		OtherSlot: 0,
	},
	SlotNameFishingFloat: {
		SlotName:  SlotNameFishingFloat,
		Name:      "FishingFloat",
		Title:     "Fishing Float",
		Desc:      "Bobber",
		OtherSlot: 0,
	},
	SlotNameFishingHarpoon: {
		SlotName:  SlotNameFishingHarpoon,
		Name:      "FishingHarpoon",
		Title:     "Fishing Harpoon",
		Desc:      "FishingHarpoon",
		OtherSlot: 0,
	},
	SlotNameGatheringCarrier: {
		SlotName:  SlotNameGatheringCarrier,
		Name:      "GatheringCarrier",
		Title:     "Carrier",
		Desc:      "Bottom slot carrier, things like fishing carrier, snowboard",
		OtherSlot: 0,
	},
	SlotNameNone: {
		SlotName:  SlotNameNone,
		Name:      "None",
		Title:     "None",
		Desc:      "Non-equipment sentinel",
		OtherSlot: 0,
	},
}

var slotNameValues = []SlotName{
	SlotNameMainWeapon,
	SlotNameSubWeapon,
	SlotNameFishingChair,
	SlotNameArmor,
	SlotNameGloves,
	SlotNameShoes,
	SlotNameHelmet,
	SlotNameNecklace,
	SlotNameRingI,
	SlotNameRingII,
	SlotNameEarringI,
	SlotNameEarringII,
	SlotNameBelt,
	SlotNameLantern,
	SlotNameCostumeArmor,
	SlotNameCostumeGloves,
	SlotNameCostumeShoes,
	SlotNameCostumeHelmet,
	SlotNameCostumeMainWeapon,
	SlotNameCostumeSubWeapon,
	SlotNameUnderwear,
	SlotNameCostumeEarring,
	SlotNameCostumeHeadpiece,
	SlotNameCostumePiercing,
	SlotNameShipGear,
	SlotNameShipGear2,
	SlotNameAlchemyStone,
	SlotNameAwakeningWeapon,
	SlotNameCostumeAwakeningWeapon,
	SlotNameTome,
	SlotNameArtifactI,
	SlotNameArtifactII,
	SlotNameLumberingAxe,
	SlotNameFluidCollector,
	SlotNameHoe,
	SlotNameButcherKnife,
	SlotNameTanningKnife,
	SlotNamePickaxe,
	SlotNameFishingRod,
	SlotNameFishingFloat,
	SlotNameFishingHarpoon,
	SlotNameGatheringCarrier,
	SlotNameNone,
}

var slotNameByName = map[string]SlotName{
	"mainweapon":             SlotNameMainWeapon,
	"subweapon":              SlotNameSubWeapon,
	"fishingchair":           SlotNameFishingChair,
	"armor":                  SlotNameArmor,
	"gloves":                 SlotNameGloves,
	"shoes":                  SlotNameShoes,
	"helmet":                 SlotNameHelmet,
	"necklace":               SlotNameNecklace,
	"ringi":                  SlotNameRingI,
	"ringii":                 SlotNameRingII,
	"earringi":               SlotNameEarringI,
	"earringii":              SlotNameEarringII,
	"belt":                   SlotNameBelt,
	"lantern":                SlotNameLantern,
	"costumearmor":           SlotNameCostumeArmor,
	"costumegloves":          SlotNameCostumeGloves,
	"costumeshoes":           SlotNameCostumeShoes,
	"costumehelmet":          SlotNameCostumeHelmet,
	"costumemainweapon":      SlotNameCostumeMainWeapon,
	"costumesubweapon":       SlotNameCostumeSubWeapon,
	"underwear":              SlotNameUnderwear,
	"costumeearring":         SlotNameCostumeEarring,
	"costumeheadpiece":       SlotNameCostumeHeadpiece,
	"costumepiercing":        SlotNameCostumePiercing,
	"shipgear":               SlotNameShipGear,
	"shipgear2":              SlotNameShipGear2,
	"alchemystone":           SlotNameAlchemyStone,
	"awakeningweapon":        SlotNameAwakeningWeapon,
	"costumeawakeningweapon": SlotNameCostumeAwakeningWeapon,
	"tome":                   SlotNameTome,
	"artifacti":              SlotNameArtifactI,
	"artifactii":             SlotNameArtifactII,
	"lumberingaxe":           SlotNameLumberingAxe,
	"fluidcollector":         SlotNameFluidCollector,
	"hoe":                    SlotNameHoe,
	"butcherknife":           SlotNameButcherKnife,
	"tanningknife":           SlotNameTanningKnife,
	"pickaxe":                SlotNamePickaxe,
	"fishingrod":             SlotNameFishingRod,
	"fishingfloat":           SlotNameFishingFloat,
	"fishingharpoon":         SlotNameFishingHarpoon,
	"gatheringcarrier":       SlotNameGatheringCarrier,
	"none":                   SlotNameNone,
}

// Values returns every declared value in declaration order.
func (c SlotNameContainer) Values() []SlotName {
	out := make([]SlotName, len(slotNameValues))
	copy(out, slotNameValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c SlotNameContainer) Infos() []SlotNameInfo {
	out := make([]SlotNameInfo, len(slotNameValues))
	for i, v := range slotNameValues {
		out[i] = slotNameInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c SlotNameContainer) Len() int {
	return len(slotNameValues)
}

// All iterates every declared value in declaration order.
func (c SlotNameContainer) All() iter.Seq[SlotName] {
	return func(yield func(SlotName) bool) {
		for _, v := range slotNameValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c SlotNameContainer) FromWire(w byte) (SlotName, bool) {
	v := SlotName(w)
	_, ok := slotNameInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c SlotNameContainer) FromWireUnsafe(w byte) SlotName {
	return SlotName(w)
}

// Parse resolves a value by name, case-insensitively.
func (c SlotNameContainer) Parse(s string) (SlotName, error) {
	if v, ok := slotNameByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero SlotName
	return zero, fmt.Errorf("unknown SlotName: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v SlotName) TryGetInfo() (SlotNameInfo, bool) {
	i, ok := slotNameInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v SlotName) Info() SlotNameInfo {
	return slotNameInfos[v]
}

func (v SlotName) Valid() bool {
	_, ok := slotNameInfos[v]
	return ok
}

func (v SlotName) Wire() byte {
	return byte(v)
}

func (v SlotName) Name() string {
	return slotNameInfos[v].Name
}

func (v SlotName) String() string {
	if i, ok := slotNameInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("SlotName(%d)", byte(v))
}

func (v SlotName) Title() string {
	return slotNameInfos[v].Title
}

func (v SlotName) Desc() string {
	return slotNameInfos[v].Desc
}

func (v SlotName) OtherSlot() int {
	return slotNameInfos[v].OtherSlot
}
