// Code generated by enumgen from stats.yml. DO NOT EDIT.

package model

import (
	"fmt"
	"iter"
	"strings"
)

// StatId is a string-wide identifier. The zero-cost conversion StatId(x) is
// intentional: the underlying value is the wire value.
type StatId string

const (
	StatIdMonsterAp                     StatId = "monsterAp"
	StatIdAdventurerAp                  StatId = "adventurerAp"
	StatIdHumanAp                       StatId = "humanAp"
	StatIdDemihumanAp                   StatId = "demihumanAp"
	StatIdKamasylvianAp                 StatId = "kamasylvianAp"
	StatIdAllSpeciesAp                  StatId = "allSpeciesAp"
	StatIdHiddenAp                      StatId = "hiddenAp"
	StatIdDp                            StatId = "dp"
	StatIdMeleeAp                       StatId = "meleeAp"
	StatIdRangedAp                      StatId = "rangedAp"
	StatIdMagicAp                       StatId = "magicAp"
	StatIdCritDamage                    StatId = "critDamage"
	StatIdSpecialAttackDamage           StatId = "specialAttackDamage"
	StatIdBackAttackDamage              StatId = "backAttackDamage"
	StatIdDownAttackDamage              StatId = "downAttackDamage"
	StatIdHuntingDamage                 StatId = "huntingDamage"
	StatIdAccuracy                      StatId = "accuracy"
	StatIdMeleeAccuracy                 StatId = "meleeAccuracy"
	StatIdRangedAccuracy                StatId = "rangedAccuracy"
	StatIdMagicAccuracy                 StatId = "magicAccuracy"
	StatIdMeleeEvasion                  StatId = "meleeEvasion"
	StatIdRangedEvasion                 StatId = "rangedEvasion"
	StatIdMagicEvasion                  StatId = "magicEvasion"
	StatIdMeleeDamageReduction          StatId = "meleeDamageReduction"
	StatIdRangedDamageReduction         StatId = "rangedDamageReduction"
	StatIdMagicDamageReduction          StatId = "magicDamageReduction"
	StatIdDamageReductionRate           StatId = "damageReductionRate"
	StatIdAllResistance                 StatId = "allResistance"
	StatIdStunResistance                StatId = "stunResistance"
	StatIdKnockdownResistance           StatId = "knockdownResistance"
	StatIdKnockbackResistance           StatId = "knockbackResistance"
	StatIdFearResistance                StatId = "fearResistance"
	StatIdIgnoreAllResistance           StatId = "ignoreAllResistance"
	StatIdIgnoreGrappleResistance       StatId = "ignoreGrappleResistance"
	StatIdIgnoreKnockbackResistance     StatId = "ignoreKnockbackResistance"
	StatIdIgnoreKnockdownResistance     StatId = "ignoreKnockdownResistance"
	StatIdIgnoreStunResistance          StatId = "ignoreStunResistance"
	StatIdAttackSpeed                   StatId = "attackSpeed"
	StatIdCastingSpeed                  StatId = "castingSpeed"
	StatIdMoveSpeed                     StatId = "moveSpeed"
	StatIdLuck                          StatId = "luck"
	StatIdMaxHp                         StatId = "maxHp"
	StatIdHpRecovery                    StatId = "hpRecovery"
	StatIdHpRecoveryOnHit               StatId = "hpRecoveryOnHit"
	StatIdHpRecoveryOnCriticalHit       StatId = "hpRecoveryOnCriticalHit"
	StatIdResourceRecovery              StatId = "resourceRecovery"
	StatIdResourceRecoveryOnHit         StatId = "resourceRecoveryOnHit"
	StatIdResourceRecoveryOnCriticalHit StatId = "resourceRecoveryOnCriticalHit"
	StatIdMaxEnergy                     StatId = "maxEnergy"
	StatIdEnergyRecovery                StatId = "energyRecovery"
	StatIdBlackSpiritRage               StatId = "blackSpiritRage"
	StatIdAllMastery                    StatId = "allMastery"
	StatIdGatheringMastery              StatId = "gatheringMastery"
	StatIdHoeMastery                    StatId = "hoeMastery"
	StatIdLumberingMastery              StatId = "lumberingMastery"
	StatIdFluidCollectorMastery         StatId = "fluidCollectorMastery"
	StatIdTanningMastery                StatId = "tanningMastery"
	StatIdButcherMastery                StatId = "butcherMastery"
	StatIdPickaxeMastery                StatId = "pickaxeMastery"
	StatIdFishingMastery                StatId = "fishingMastery"
	StatIdHuntingMastery                StatId = "huntingMastery"
	StatIdCookingMastery                StatId = "cookingMastery"
	StatIdAlchemyMastery                StatId = "alchemyMastery"
	StatIdProcessingMastery             StatId = "processingMastery"
	StatIdTrainingMastery               StatId = "trainingMastery"
	StatIdSailingMastery                StatId = "sailingMastery"
	StatIdLifeExp                       StatId = "lifeExp"
	StatIdCombatExp                     StatId = "combatExp"
	StatIdSkillExp                      StatId = "skillExp"
	StatIdGatheringExp                  StatId = "gatheringExp"
	StatIdHuntingExp                    StatId = "huntingExp"
	StatIdCookingExp                    StatId = "cookingExp"
	StatIdAlchemyExp                    StatId = "alchemyExp"
	StatIdFishingExp                    StatId = "fishingExp"
	StatIdProcessingExp                 StatId = "processingExp"
	StatIdTrainingExp                   StatId = "trainingExp"
	StatIdSailingExp                    StatId = "sailingExp"
	StatIdBarteringExp                  StatId = "barteringExp"
	StatIdTradingExp                    StatId = "tradingExp"
	StatIdFarmingExp                    StatId = "farmingExp"
	StatIdMountExp                      StatId = "mountExp"
	StatIdMountSkillExp                 StatId = "mountSkillExp"
	StatIdStrengthExp                   StatId = "strengthExp"
	StatIdBreathExp                     StatId = "breathExp"
	StatIdHealthExp                     StatId = "healthExp"
	StatIdGatheringTime                 StatId = "gatheringTime"
	StatIdCookingTime                   StatId = "cookingTime"
	StatIdAlchemyTime                   StatId = "alchemyTime"
	StatIdGatheringDropRate             StatId = "gatheringDropRate"
	StatIdAutoFishingTime               StatId = "autoFishingTime"
	StatIdRareFishChance                StatId = "rareFishChance"
	StatIdHorseCaptureRate              StatId = "horseCaptureRate"
	StatIdProcessingSuccessRate         StatId = "processingSuccessRate"
	StatIdAmity                         StatId = "amity"
	StatIdDeathPenaltyResistance        StatId = "deathPenaltyResistance"
	StatIdDurabilityLossResistance      StatId = "durabilityLossResistance"
	StatIdFallDamage                    StatId = "fallDamage"
	StatIdItemDropRate                  StatId = "itemDropRate"
	StatIdItemDropAmount                StatId = "itemDropAmount"
	StatIdHigherGradeKnowledgeChance    StatId = "higherGradeKnowledgeChance"
	StatIdKarmaRecovery                 StatId = "karmaRecovery"
	StatIdSwimmingSpeed                 StatId = "swimmingSpeed"
	StatIdHeatstrokeResistance          StatId = "heatstrokeResistance"
	StatIdHypothermiaResistance         StatId = "hypothermiaResistance"
	StatIdJumpHeight                    StatId = "jumpHeight"
	StatIdKnowledgeChance               StatId = "knowledgeChance"
	StatIdMermaidsWish                  StatId = "mermaidsWish"
	StatIdUnderwaterBreathing           StatId = "underwaterBreathing"
	StatIdWeightLimit                   StatId = "weightLimit"
	StatIdAp                            StatId = "ap"
	StatIdAwakeningAp                   StatId = "awakeningAp"
	StatIdTotalAp                       StatId = "totalAp"
	StatIdTotalAwakeningAp              StatId = "totalAwakeningAp"
	StatIdBracketAp                     StatId = "bracketAp"
	StatIdBracketAwakeningAp            StatId = "bracketAwakeningAp"
	StatIdBracketMonsterAp              StatId = "bracketMonsterAp"
	StatIdBracketMonsterAwakeningAp     StatId = "bracketMonsterAwakeningAp"
	StatIdApVsMonster                   StatId = "apVsMonster"
	StatIdApVsAdventurer                StatId = "apVsAdventurer"
	StatIdApVsHuman                     StatId = "apVsHuman"
	StatIdApVsDemihuman                 StatId = "apVsDemihuman"
	StatIdApVsKamasylvian               StatId = "apVsKamasylvian"
	StatIdApVsEdania                    StatId = "apVsEdania"
	StatIdApVsNormal                    StatId = "apVsNormal"
	StatIdAwakeningApVsMonster          StatId = "awakeningApVsMonster"
	StatIdAwakeningApVsAdventurer       StatId = "awakeningApVsAdventurer"
	StatIdAwakeningApVsHuman            StatId = "awakeningApVsHuman"
	StatIdAwakeningApVsDemihuman        StatId = "awakeningApVsDemihuman"
	StatIdAwakeningApVsKamasylvian      StatId = "awakeningApVsKamasylvian"
	StatIdAwakeningApVsEdania           StatId = "awakeningApVsEdania"
	StatIdAwakeningApVsNormal           StatId = "awakeningApVsNormal"
	StatIdNormalAp                      StatId = "normalAp"
	StatIdEdaniaAp                      StatId = "edaniaAp"
	StatIdBeastAp                       StatId = "beastAp"
	StatIdDamageReduction               StatId = "damageReduction"
	StatIdTotalDamageReduction          StatId = "totalDamageReduction"
	StatIdHiddenDamageReduction         StatId = "hiddenDamageReduction"
	StatIdMonsterDamageReduction        StatId = "monsterDamageReduction"
	StatIdMonsterDamageReductionRate    StatId = "monsterDamageReductionRate"
	StatIdMeleeMonsterDamageReduction   StatId = "meleeMonsterDamageReduction"
	StatIdRangedMonsterDamageReduction  StatId = "rangedMonsterDamageReduction"
	StatIdMagicMonsterDamageReduction   StatId = "magicMonsterDamageReduction"
	StatIdHiddenMeleeDamageReduction    StatId = "hiddenMeleeDamageReduction"
	StatIdHiddenRangedDamageReduction   StatId = "hiddenRangedDamageReduction"
	StatIdHiddenMagicDamageReduction    StatId = "hiddenMagicDamageReduction"
	StatIdEvasion                       StatId = "evasion"
	StatIdHiddenEvasion                 StatId = "hiddenEvasion"
	StatIdEvasionRate                   StatId = "evasionRate"
	StatIdMeleeEvasionRate              StatId = "meleeEvasionRate"
	StatIdRangedEvasionRate             StatId = "rangedEvasionRate"
	StatIdMagicEvasionRate              StatId = "magicEvasionRate"
	StatIdHiddenMeleeEvasion            StatId = "hiddenMeleeEvasion"
	StatIdHiddenRangedEvasion           StatId = "hiddenRangedEvasion"
	StatIdHiddenMagicEvasion            StatId = "hiddenMagicEvasion"
	StatIdGrappleResistance             StatId = "grappleResistance"
	StatIdAirAttackDamage               StatId = "airAttackDamage"
	StatIdCounterAttackDamage           StatId = "counterAttackDamage"
	StatIdSpeedAttackDamage             StatId = "speedAttackDamage"
	StatIdFarmingMastery                StatId = "farmingMastery"
	StatIdTradingMastery                StatId = "tradingMastery"
	StatIdFilteringMastery              StatId = "filteringMastery"
	StatIdDryingMastery                 StatId = "dryingMastery"
	StatIdGrindingMastery               StatId = "grindingMastery"
	StatIdHeatingMastery                StatId = "heatingMastery"
	StatIdChoppingMastery               StatId = "choppingMastery"
	StatIdShakingMastery                StatId = "shakingMastery"
	StatIdMaxResource                   StatId = "maxResource"
	StatIdMaxStamina                    StatId = "maxStamina"
	StatIdApMin                         StatId = "apMin"
	StatIdApMax                         StatId = "apMax"
	StatIdAwakeningApMin                StatId = "awakeningApMin"
	StatIdAwakeningApMax                StatId = "awakeningApMax"
	StatIdCritLevel                     StatId = "critLevel"
	StatIdCritChance                    StatId = "critChance"
	StatIdFishingSpeed                  StatId = "fishingSpeed"
	StatIdAttackSpeedLevel              StatId = "attackSpeedLevel"
	StatIdCastingSpeedLevel             StatId = "castingSpeedLevel"
	StatIdMovementSpeedLevel            StatId = "movementSpeedLevel"
	StatIdGatheringSpeed                StatId = "gatheringSpeed"
	StatIdWorkerStaminaRecovery         StatId = "workerStaminaRecovery"
)

type StatIdContainer struct {
	MonsterAp                     StatId
	AdventurerAp                  StatId
	HumanAp                       StatId
	DemihumanAp                   StatId
	KamasylvianAp                 StatId
	AllSpeciesAp                  StatId
	HiddenAp                      StatId
	Dp                            StatId
	MeleeAp                       StatId
	RangedAp                      StatId
	MagicAp                       StatId
	CritDamage                    StatId
	SpecialAttackDamage           StatId
	BackAttackDamage              StatId
	DownAttackDamage              StatId
	HuntingDamage                 StatId
	Accuracy                      StatId
	MeleeAccuracy                 StatId
	RangedAccuracy                StatId
	MagicAccuracy                 StatId
	MeleeEvasion                  StatId
	RangedEvasion                 StatId
	MagicEvasion                  StatId
	MeleeDamageReduction          StatId
	RangedDamageReduction         StatId
	MagicDamageReduction          StatId
	DamageReductionRate           StatId
	AllResistance                 StatId
	StunResistance                StatId
	KnockdownResistance           StatId
	KnockbackResistance           StatId
	FearResistance                StatId
	IgnoreAllResistance           StatId
	IgnoreGrappleResistance       StatId
	IgnoreKnockbackResistance     StatId
	IgnoreKnockdownResistance     StatId
	IgnoreStunResistance          StatId
	AttackSpeed                   StatId
	CastingSpeed                  StatId
	MoveSpeed                     StatId
	Luck                          StatId
	MaxHp                         StatId
	HpRecovery                    StatId
	HpRecoveryOnHit               StatId
	HpRecoveryOnCriticalHit       StatId
	ResourceRecovery              StatId
	ResourceRecoveryOnHit         StatId
	ResourceRecoveryOnCriticalHit StatId
	MaxEnergy                     StatId
	EnergyRecovery                StatId
	BlackSpiritRage               StatId
	AllMastery                    StatId
	GatheringMastery              StatId
	HoeMastery                    StatId
	LumberingMastery              StatId
	FluidCollectorMastery         StatId
	TanningMastery                StatId
	ButcherMastery                StatId
	PickaxeMastery                StatId
	FishingMastery                StatId
	HuntingMastery                StatId
	CookingMastery                StatId
	AlchemyMastery                StatId
	ProcessingMastery             StatId
	TrainingMastery               StatId
	SailingMastery                StatId
	LifeExp                       StatId
	CombatExp                     StatId
	SkillExp                      StatId
	GatheringExp                  StatId
	HuntingExp                    StatId
	CookingExp                    StatId
	AlchemyExp                    StatId
	FishingExp                    StatId
	ProcessingExp                 StatId
	TrainingExp                   StatId
	SailingExp                    StatId
	BarteringExp                  StatId
	TradingExp                    StatId
	FarmingExp                    StatId
	MountExp                      StatId
	MountSkillExp                 StatId
	StrengthExp                   StatId
	BreathExp                     StatId
	HealthExp                     StatId
	GatheringTime                 StatId
	CookingTime                   StatId
	AlchemyTime                   StatId
	GatheringDropRate             StatId
	AutoFishingTime               StatId
	RareFishChance                StatId
	HorseCaptureRate              StatId
	ProcessingSuccessRate         StatId
	Amity                         StatId
	DeathPenaltyResistance        StatId
	DurabilityLossResistance      StatId
	FallDamage                    StatId
	ItemDropRate                  StatId
	ItemDropAmount                StatId
	HigherGradeKnowledgeChance    StatId
	KarmaRecovery                 StatId
	SwimmingSpeed                 StatId
	HeatstrokeResistance          StatId
	HypothermiaResistance         StatId
	JumpHeight                    StatId
	KnowledgeChance               StatId
	MermaidsWish                  StatId
	UnderwaterBreathing           StatId
	WeightLimit                   StatId
	Ap                            StatId
	AwakeningAp                   StatId
	TotalAp                       StatId
	TotalAwakeningAp              StatId
	BracketAp                     StatId
	BracketAwakeningAp            StatId
	BracketMonsterAp              StatId
	BracketMonsterAwakeningAp     StatId
	ApVsMonster                   StatId
	ApVsAdventurer                StatId
	ApVsHuman                     StatId
	ApVsDemihuman                 StatId
	ApVsKamasylvian               StatId
	ApVsEdania                    StatId
	ApVsNormal                    StatId
	AwakeningApVsMonster          StatId
	AwakeningApVsAdventurer       StatId
	AwakeningApVsHuman            StatId
	AwakeningApVsDemihuman        StatId
	AwakeningApVsKamasylvian      StatId
	AwakeningApVsEdania           StatId
	AwakeningApVsNormal           StatId
	NormalAp                      StatId
	EdaniaAp                      StatId
	BeastAp                       StatId
	DamageReduction               StatId
	TotalDamageReduction          StatId
	HiddenDamageReduction         StatId
	MonsterDamageReduction        StatId
	MonsterDamageReductionRate    StatId
	MeleeMonsterDamageReduction   StatId
	RangedMonsterDamageReduction  StatId
	MagicMonsterDamageReduction   StatId
	HiddenMeleeDamageReduction    StatId
	HiddenRangedDamageReduction   StatId
	HiddenMagicDamageReduction    StatId
	Evasion                       StatId
	HiddenEvasion                 StatId
	EvasionRate                   StatId
	MeleeEvasionRate              StatId
	RangedEvasionRate             StatId
	MagicEvasionRate              StatId
	HiddenMeleeEvasion            StatId
	HiddenRangedEvasion           StatId
	HiddenMagicEvasion            StatId
	GrappleResistance             StatId
	AirAttackDamage               StatId
	CounterAttackDamage           StatId
	SpeedAttackDamage             StatId
	FarmingMastery                StatId
	TradingMastery                StatId
	FilteringMastery              StatId
	DryingMastery                 StatId
	GrindingMastery               StatId
	HeatingMastery                StatId
	ChoppingMastery               StatId
	ShakingMastery                StatId
	MaxResource                   StatId
	MaxStamina                    StatId
	ApMin                         StatId
	ApMax                         StatId
	AwakeningApMin                StatId
	AwakeningApMax                StatId
	CritLevel                     StatId
	CritChance                    StatId
	FishingSpeed                  StatId
	AttackSpeedLevel              StatId
	CastingSpeedLevel             StatId
	MovementSpeedLevel            StatId
	GatheringSpeed                StatId
	WorkerStaminaRecovery         StatId
}

// StatIds is the entry point for the StatId enum.
var StatIds = StatIdContainer{
	MonsterAp:                     StatIdMonsterAp,
	AdventurerAp:                  StatIdAdventurerAp,
	HumanAp:                       StatIdHumanAp,
	DemihumanAp:                   StatIdDemihumanAp,
	KamasylvianAp:                 StatIdKamasylvianAp,
	AllSpeciesAp:                  StatIdAllSpeciesAp,
	HiddenAp:                      StatIdHiddenAp,
	Dp:                            StatIdDp,
	MeleeAp:                       StatIdMeleeAp,
	RangedAp:                      StatIdRangedAp,
	MagicAp:                       StatIdMagicAp,
	CritDamage:                    StatIdCritDamage,
	SpecialAttackDamage:           StatIdSpecialAttackDamage,
	BackAttackDamage:              StatIdBackAttackDamage,
	DownAttackDamage:              StatIdDownAttackDamage,
	HuntingDamage:                 StatIdHuntingDamage,
	Accuracy:                      StatIdAccuracy,
	MeleeAccuracy:                 StatIdMeleeAccuracy,
	RangedAccuracy:                StatIdRangedAccuracy,
	MagicAccuracy:                 StatIdMagicAccuracy,
	MeleeEvasion:                  StatIdMeleeEvasion,
	RangedEvasion:                 StatIdRangedEvasion,
	MagicEvasion:                  StatIdMagicEvasion,
	MeleeDamageReduction:          StatIdMeleeDamageReduction,
	RangedDamageReduction:         StatIdRangedDamageReduction,
	MagicDamageReduction:          StatIdMagicDamageReduction,
	DamageReductionRate:           StatIdDamageReductionRate,
	AllResistance:                 StatIdAllResistance,
	StunResistance:                StatIdStunResistance,
	KnockdownResistance:           StatIdKnockdownResistance,
	KnockbackResistance:           StatIdKnockbackResistance,
	FearResistance:                StatIdFearResistance,
	IgnoreAllResistance:           StatIdIgnoreAllResistance,
	IgnoreGrappleResistance:       StatIdIgnoreGrappleResistance,
	IgnoreKnockbackResistance:     StatIdIgnoreKnockbackResistance,
	IgnoreKnockdownResistance:     StatIdIgnoreKnockdownResistance,
	IgnoreStunResistance:          StatIdIgnoreStunResistance,
	AttackSpeed:                   StatIdAttackSpeed,
	CastingSpeed:                  StatIdCastingSpeed,
	MoveSpeed:                     StatIdMoveSpeed,
	Luck:                          StatIdLuck,
	MaxHp:                         StatIdMaxHp,
	HpRecovery:                    StatIdHpRecovery,
	HpRecoveryOnHit:               StatIdHpRecoveryOnHit,
	HpRecoveryOnCriticalHit:       StatIdHpRecoveryOnCriticalHit,
	ResourceRecovery:              StatIdResourceRecovery,
	ResourceRecoveryOnHit:         StatIdResourceRecoveryOnHit,
	ResourceRecoveryOnCriticalHit: StatIdResourceRecoveryOnCriticalHit,
	MaxEnergy:                     StatIdMaxEnergy,
	EnergyRecovery:                StatIdEnergyRecovery,
	BlackSpiritRage:               StatIdBlackSpiritRage,
	AllMastery:                    StatIdAllMastery,
	GatheringMastery:              StatIdGatheringMastery,
	HoeMastery:                    StatIdHoeMastery,
	LumberingMastery:              StatIdLumberingMastery,
	FluidCollectorMastery:         StatIdFluidCollectorMastery,
	TanningMastery:                StatIdTanningMastery,
	ButcherMastery:                StatIdButcherMastery,
	PickaxeMastery:                StatIdPickaxeMastery,
	FishingMastery:                StatIdFishingMastery,
	HuntingMastery:                StatIdHuntingMastery,
	CookingMastery:                StatIdCookingMastery,
	AlchemyMastery:                StatIdAlchemyMastery,
	ProcessingMastery:             StatIdProcessingMastery,
	TrainingMastery:               StatIdTrainingMastery,
	SailingMastery:                StatIdSailingMastery,
	LifeExp:                       StatIdLifeExp,
	CombatExp:                     StatIdCombatExp,
	SkillExp:                      StatIdSkillExp,
	GatheringExp:                  StatIdGatheringExp,
	HuntingExp:                    StatIdHuntingExp,
	CookingExp:                    StatIdCookingExp,
	AlchemyExp:                    StatIdAlchemyExp,
	FishingExp:                    StatIdFishingExp,
	ProcessingExp:                 StatIdProcessingExp,
	TrainingExp:                   StatIdTrainingExp,
	SailingExp:                    StatIdSailingExp,
	BarteringExp:                  StatIdBarteringExp,
	TradingExp:                    StatIdTradingExp,
	FarmingExp:                    StatIdFarmingExp,
	MountExp:                      StatIdMountExp,
	MountSkillExp:                 StatIdMountSkillExp,
	StrengthExp:                   StatIdStrengthExp,
	BreathExp:                     StatIdBreathExp,
	HealthExp:                     StatIdHealthExp,
	GatheringTime:                 StatIdGatheringTime,
	CookingTime:                   StatIdCookingTime,
	AlchemyTime:                   StatIdAlchemyTime,
	GatheringDropRate:             StatIdGatheringDropRate,
	AutoFishingTime:               StatIdAutoFishingTime,
	RareFishChance:                StatIdRareFishChance,
	HorseCaptureRate:              StatIdHorseCaptureRate,
	ProcessingSuccessRate:         StatIdProcessingSuccessRate,
	Amity:                         StatIdAmity,
	DeathPenaltyResistance:        StatIdDeathPenaltyResistance,
	DurabilityLossResistance:      StatIdDurabilityLossResistance,
	FallDamage:                    StatIdFallDamage,
	ItemDropRate:                  StatIdItemDropRate,
	ItemDropAmount:                StatIdItemDropAmount,
	HigherGradeKnowledgeChance:    StatIdHigherGradeKnowledgeChance,
	KarmaRecovery:                 StatIdKarmaRecovery,
	SwimmingSpeed:                 StatIdSwimmingSpeed,
	HeatstrokeResistance:          StatIdHeatstrokeResistance,
	HypothermiaResistance:         StatIdHypothermiaResistance,
	JumpHeight:                    StatIdJumpHeight,
	KnowledgeChance:               StatIdKnowledgeChance,
	MermaidsWish:                  StatIdMermaidsWish,
	UnderwaterBreathing:           StatIdUnderwaterBreathing,
	WeightLimit:                   StatIdWeightLimit,
	Ap:                            StatIdAp,
	AwakeningAp:                   StatIdAwakeningAp,
	TotalAp:                       StatIdTotalAp,
	TotalAwakeningAp:              StatIdTotalAwakeningAp,
	BracketAp:                     StatIdBracketAp,
	BracketAwakeningAp:            StatIdBracketAwakeningAp,
	BracketMonsterAp:              StatIdBracketMonsterAp,
	BracketMonsterAwakeningAp:     StatIdBracketMonsterAwakeningAp,
	ApVsMonster:                   StatIdApVsMonster,
	ApVsAdventurer:                StatIdApVsAdventurer,
	ApVsHuman:                     StatIdApVsHuman,
	ApVsDemihuman:                 StatIdApVsDemihuman,
	ApVsKamasylvian:               StatIdApVsKamasylvian,
	ApVsEdania:                    StatIdApVsEdania,
	ApVsNormal:                    StatIdApVsNormal,
	AwakeningApVsMonster:          StatIdAwakeningApVsMonster,
	AwakeningApVsAdventurer:       StatIdAwakeningApVsAdventurer,
	AwakeningApVsHuman:            StatIdAwakeningApVsHuman,
	AwakeningApVsDemihuman:        StatIdAwakeningApVsDemihuman,
	AwakeningApVsKamasylvian:      StatIdAwakeningApVsKamasylvian,
	AwakeningApVsEdania:           StatIdAwakeningApVsEdania,
	AwakeningApVsNormal:           StatIdAwakeningApVsNormal,
	NormalAp:                      StatIdNormalAp,
	EdaniaAp:                      StatIdEdaniaAp,
	BeastAp:                       StatIdBeastAp,
	DamageReduction:               StatIdDamageReduction,
	TotalDamageReduction:          StatIdTotalDamageReduction,
	HiddenDamageReduction:         StatIdHiddenDamageReduction,
	MonsterDamageReduction:        StatIdMonsterDamageReduction,
	MonsterDamageReductionRate:    StatIdMonsterDamageReductionRate,
	MeleeMonsterDamageReduction:   StatIdMeleeMonsterDamageReduction,
	RangedMonsterDamageReduction:  StatIdRangedMonsterDamageReduction,
	MagicMonsterDamageReduction:   StatIdMagicMonsterDamageReduction,
	HiddenMeleeDamageReduction:    StatIdHiddenMeleeDamageReduction,
	HiddenRangedDamageReduction:   StatIdHiddenRangedDamageReduction,
	HiddenMagicDamageReduction:    StatIdHiddenMagicDamageReduction,
	Evasion:                       StatIdEvasion,
	HiddenEvasion:                 StatIdHiddenEvasion,
	EvasionRate:                   StatIdEvasionRate,
	MeleeEvasionRate:              StatIdMeleeEvasionRate,
	RangedEvasionRate:             StatIdRangedEvasionRate,
	MagicEvasionRate:              StatIdMagicEvasionRate,
	HiddenMeleeEvasion:            StatIdHiddenMeleeEvasion,
	HiddenRangedEvasion:           StatIdHiddenRangedEvasion,
	HiddenMagicEvasion:            StatIdHiddenMagicEvasion,
	GrappleResistance:             StatIdGrappleResistance,
	AirAttackDamage:               StatIdAirAttackDamage,
	CounterAttackDamage:           StatIdCounterAttackDamage,
	SpeedAttackDamage:             StatIdSpeedAttackDamage,
	FarmingMastery:                StatIdFarmingMastery,
	TradingMastery:                StatIdTradingMastery,
	FilteringMastery:              StatIdFilteringMastery,
	DryingMastery:                 StatIdDryingMastery,
	GrindingMastery:               StatIdGrindingMastery,
	HeatingMastery:                StatIdHeatingMastery,
	ChoppingMastery:               StatIdChoppingMastery,
	ShakingMastery:                StatIdShakingMastery,
	MaxResource:                   StatIdMaxResource,
	MaxStamina:                    StatIdMaxStamina,
	ApMin:                         StatIdApMin,
	ApMax:                         StatIdApMax,
	AwakeningApMin:                StatIdAwakeningApMin,
	AwakeningApMax:                StatIdAwakeningApMax,
	CritLevel:                     StatIdCritLevel,
	CritChance:                    StatIdCritChance,
	FishingSpeed:                  StatIdFishingSpeed,
	AttackSpeedLevel:              StatIdAttackSpeedLevel,
	CastingSpeedLevel:             StatIdCastingSpeedLevel,
	MovementSpeedLevel:            StatIdMovementSpeedLevel,
	GatheringSpeed:                StatIdGatheringSpeed,
	WorkerStaminaRecovery:         StatIdWorkerStaminaRecovery,
}

// StatIdInfo is the static metadata attached to a StatId.
type StatIdInfo struct {
	StatId
	Name     string
	Label    string
	Category string
	Alias    string
	Fanout   []StatId
	Unit     string
	Cap      int
}

var statIdInfos = map[StatId]StatIdInfo{
	StatIdMonsterAp: {
		StatId:   StatIdMonsterAp,
		Name:     "monsterAp",
		Label:    "Extra AP Against Monsters",
		Category: "ap",
		Alias:    "eaam",
		Fanout:   []StatId{StatIdApVsMonster, StatIdApVsKamasylvian, StatIdApVsHuman, StatIdApVsDemihuman, StatIdApVsNormal, StatIdAwakeningApVsMonster, StatIdAwakeningApVsKamasylvian, StatIdAwakeningApVsHuman, StatIdAwakeningApVsDemihuman, StatIdAwakeningApVsNormal, StatIdApVsEdania, StatIdAwakeningApVsEdania},
		Unit:     "",
		Cap:      0,
	},
	StatIdAdventurerAp: {
		StatId:   StatIdAdventurerAp,
		Name:     "adventurerAp",
		Label:    "Extra AP Against Adventurers",
		Category: "ap",
		Alias:    "edtad",
		Fanout:   []StatId{StatIdApVsAdventurer, StatIdAwakeningApVsAdventurer},
		Unit:     "",
		Cap:      0,
	},
	StatIdHumanAp: {
		StatId:   StatIdHumanAp,
		Name:     "humanAp",
		Label:    "Extra AP Against Humans",
		Category: "ap",
		Alias:    "edth",
		Fanout:   []StatId{StatIdApVsHuman, StatIdAwakeningApVsHuman},
		Unit:     "",
		Cap:      0,
	},
	StatIdDemihumanAp: {
		StatId:   StatIdDemihumanAp,
		Name:     "demihumanAp",
		Label:    "Extra AP Against Demihumans",
		Category: "ap",
		Alias:    "edtd",
		Fanout:   []StatId{StatIdApVsDemihuman, StatIdAwakeningApVsDemihuman},
		Unit:     "",
		Cap:      0,
	},
	StatIdKamasylvianAp: {
		StatId:   StatIdKamasylvianAp,
		Name:     "kamasylvianAp",
		Label:    "Extra AP Against Kamasylvian",
		Category: "ap",
		Alias:    "edtkm",
		Fanout:   []StatId{StatIdApVsKamasylvian, StatIdAwakeningApVsKamasylvian},
		Unit:     "",
		Cap:      0,
	},
	StatIdAllSpeciesAp: {
		StatId:   StatIdAllSpeciesAp,
		Name:     "allSpeciesAp",
		Label:    "Extra AP Against All Species",
		Category: "ap",
		Alias:    "edtas",
		Fanout:   []StatId{StatIdKamasylvianAp, StatIdHumanAp, StatIdDemihumanAp, StatIdNormalAp, StatIdEdaniaAp},
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenAp: {
		StatId:   StatIdHiddenAp,
		Name:     "hiddenAp",
		Label:    "Hidden AP",
		Category: "ap",
		Alias:    "hap",
		Fanout:   []StatId{StatIdTotalAp, StatIdTotalAwakeningAp},
		Unit:     "",
		Cap:      0,
	},
	StatIdDp: {
		StatId:   StatIdDp,
		Name:     "dp",
		Label:    "DP",
		Category: "defense",
		Alias:    "dp",
		Unit:     "",
		Cap:      0,
	},
	StatIdMeleeAp: {
		StatId:   StatIdMeleeAp,
		Name:     "meleeAp",
		Label:    "Melee AP",
		Category: "ap",
		Alias:    "mlap",
		Unit:     "",
		Cap:      0,
	},
	StatIdRangedAp: {
		StatId:   StatIdRangedAp,
		Name:     "rangedAp",
		Label:    "Ranged AP",
		Category: "ap",
		Alias:    "rap",
		Unit:     "",
		Cap:      0,
	},
	StatIdMagicAp: {
		StatId:   StatIdMagicAp,
		Name:     "magicAp",
		Label:    "Magic AP",
		Category: "ap",
		Alias:    "map",
		Unit:     "",
		Cap:      0,
	},
	StatIdCritDamage: {
		StatId:   StatIdCritDamage,
		Name:     "critDamage",
		Label:    "Critical Hit Damage",
		Category: "damage",
		Alias:    "chrp",
		Unit:     "%",
		Cap:      0,
	},
	StatIdSpecialAttackDamage: {
		StatId:   StatIdSpecialAttackDamage,
		Name:     "specialAttackDamage",
		Label:    "All Special Attack Extra Damage",
		Category: "damage",
		Alias:    "asaed",
		Fanout:   []StatId{StatIdAirAttackDamage, StatIdBackAttackDamage, StatIdCounterAttackDamage, StatIdDownAttackDamage, StatIdSpeedAttackDamage, StatIdCritDamage},
		Unit:     "%",
		Cap:      0,
	},
	StatIdBackAttackDamage: {
		StatId:   StatIdBackAttackDamage,
		Name:     "backAttackDamage",
		Label:    "Back Attack Damage",
		Category: "damage",
		Alias:    "abad",
		Unit:     "%",
		Cap:      0,
	},
	StatIdDownAttackDamage: {
		StatId:   StatIdDownAttackDamage,
		Name:     "downAttackDamage",
		Label:    "Down Attack Damage",
		Category: "damage",
		Alias:    "adad",
		Unit:     "%",
		Cap:      0,
	},
	StatIdHuntingDamage: {
		StatId:   StatIdHuntingDamage,
		Name:     "huntingDamage",
		Label:    "Hunting Damage",
		Category: "damage",
		Alias:    "huntdmg",
		Unit:     "",
		Cap:      0,
	},
	StatIdAccuracy: {
		StatId:   StatIdAccuracy,
		Name:     "accuracy",
		Label:    "Accuracy",
		Category: "offense",
		Alias:    "acc",
		Unit:     "",
		Cap:      0,
	},
	StatIdMeleeAccuracy: {
		StatId:   StatIdMeleeAccuracy,
		Name:     "meleeAccuracy",
		Label:    "Melee Accuracy",
		Category: "offense",
		Alias:    "melacc",
		Fanout:   []StatId{StatIdAccuracy},
		Unit:     "",
		Cap:      0,
	},
	StatIdRangedAccuracy: {
		StatId:   StatIdRangedAccuracy,
		Name:     "rangedAccuracy",
		Label:    "Ranged Accuracy",
		Category: "offense",
		Alias:    "ranacc",
		Fanout:   []StatId{StatIdAccuracy},
		Unit:     "",
		Cap:      0,
	},
	StatIdMagicAccuracy: {
		StatId:   StatIdMagicAccuracy,
		Name:     "magicAccuracy",
		Label:    "Magic Accuracy",
		Category: "offense",
		Alias:    "magacc",
		Fanout:   []StatId{StatIdAccuracy},
		Unit:     "",
		Cap:      0,
	},
	StatIdMeleeEvasion: {
		StatId:   StatIdMeleeEvasion,
		Name:     "meleeEvasion",
		Label:    "Melee Evasion",
		Category: "defense",
		Alias:    "meev",
		Unit:     "",
		Cap:      0,
	},
	StatIdRangedEvasion: {
		StatId:   StatIdRangedEvasion,
		Name:     "rangedEvasion",
		Label:    "Ranged Evasion",
		Category: "defense",
		Alias:    "raev",
		Unit:     "",
		Cap:      0,
	},
	StatIdMagicEvasion: {
		StatId:   StatIdMagicEvasion,
		Name:     "magicEvasion",
		Label:    "Magic Evasion",
		Category: "defense",
		Alias:    "maev",
		Unit:     "",
		Cap:      0,
	},
	StatIdMeleeDamageReduction: {
		StatId:   StatIdMeleeDamageReduction,
		Name:     "meleeDamageReduction",
		Label:    "Melee Damage Reduction",
		Category: "defense",
		Alias:    "mldr",
		Unit:     "",
		Cap:      0,
	},
	StatIdRangedDamageReduction: {
		StatId:   StatIdRangedDamageReduction,
		Name:     "rangedDamageReduction",
		Label:    "Ranged Damage Reduction",
		Category: "defense",
		Alias:    "radr",
		Unit:     "",
		Cap:      0,
	},
	StatIdMagicDamageReduction: {
		StatId:   StatIdMagicDamageReduction,
		Name:     "magicDamageReduction",
		Label:    "Magic Damage Reduction",
		Category: "defense",
		Alias:    "madr",
		Unit:     "",
		Cap:      0,
	},
	StatIdDamageReductionRate: {
		StatId:   StatIdDamageReductionRate,
		Name:     "damageReductionRate",
		Label:    "Damage Reduction Rate",
		Category: "defense",
		Alias:    "bdrp",
		Unit:     "%",
		Cap:      0,
	},
	StatIdAllResistance: {
		StatId:   StatIdAllResistance,
		Name:     "allResistance",
		Label:    "All Resistance",
		Category: "resistance",
		Alias:    "ar",
		Fanout:   []StatId{StatIdGrappleResistance, StatIdKnockbackResistance, StatIdKnockdownResistance, StatIdStunResistance},
		Unit:     "%",
		Cap:      0,
	},
	StatIdStunResistance: {
		StatId:   StatIdStunResistance,
		Name:     "stunResistance",
		Label:    "Stun/Stiffness/Freezing Resistance",
		Category: "resistance",
		Alias:    "ssfr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdKnockdownResistance: {
		StatId:   StatIdKnockdownResistance,
		Name:     "knockdownResistance",
		Label:    "Knockdown/Bound Resistance",
		Category: "resistance",
		Alias:    "kbr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdKnockbackResistance: {
		StatId:   StatIdKnockbackResistance,
		Name:     "knockbackResistance",
		Label:    "Knockback/Floating Resistance",
		Category: "resistance",
		Alias:    "kfr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdFearResistance: {
		StatId:   StatIdFearResistance,
		Name:     "fearResistance",
		Label:    "Fear Resistance",
		Category: "resistance",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdIgnoreAllResistance: {
		StatId:   StatIdIgnoreAllResistance,
		Name:     "ignoreAllResistance",
		Label:    "Ignore All Resistance",
		Category: "resistance",
		Alias:    "",
		Fanout:   []StatId{StatIdIgnoreGrappleResistance, StatIdIgnoreKnockbackResistance, StatIdIgnoreKnockdownResistance, StatIdIgnoreStunResistance},
		Unit:     "%",
		Cap:      0,
	},
	StatIdIgnoreGrappleResistance: {
		StatId:   StatIdIgnoreGrappleResistance,
		Name:     "ignoreGrappleResistance",
		Label:    "Ignore Grapple Resistance",
		Category: "resistance",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdIgnoreKnockbackResistance: {
		StatId:   StatIdIgnoreKnockbackResistance,
		Name:     "ignoreKnockbackResistance",
		Label:    "Ignore Knockback/Floating Resistance",
		Category: "resistance",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdIgnoreKnockdownResistance: {
		StatId:   StatIdIgnoreKnockdownResistance,
		Name:     "ignoreKnockdownResistance",
		Label:    "Ignore Knockdown/Bound Resistance",
		Category: "resistance",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdIgnoreStunResistance: {
		StatId:   StatIdIgnoreStunResistance,
		Name:     "ignoreStunResistance",
		Label:    "Ignore Stun/Stiffness/Freezing Resistance",
		Category: "resistance",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdAttackSpeed: {
		StatId:   StatIdAttackSpeed,
		Name:     "attackSpeed",
		Label:    "Attack Speed",
		Category: "combat",
		Alias:    "asp",
		Unit:     "%",
		Cap:      0,
	},
	StatIdCastingSpeed: {
		StatId:   StatIdCastingSpeed,
		Name:     "castingSpeed",
		Label:    "Casting Speed",
		Category: "combat",
		Alias:    "csp",
		Unit:     "%",
		Cap:      0,
	},
	StatIdMoveSpeed: {
		StatId:   StatIdMoveSpeed,
		Name:     "moveSpeed",
		Label:    "Movement Speed",
		Category: "combat",
		Alias:    "msp",
		Unit:     "%",
		Cap:      0,
	},
	StatIdLuck: {
		StatId:   StatIdLuck,
		Name:     "luck",
		Label:    "Luck",
		Category: "combat",
		Alias:    "lk",
		Unit:     "",
		Cap:      0,
	},
	StatIdMaxHp: {
		StatId:   StatIdMaxHp,
		Name:     "maxHp",
		Label:    "Max HP",
		Category: "resource",
		Alias:    "hp",
		Unit:     "",
		Cap:      0,
	},
	StatIdHpRecovery: {
		StatId:   StatIdHpRecovery,
		Name:     "hpRecovery",
		Label:    "HP Recovery",
		Category: "resource",
		Alias:    "hpr",
		Unit:     "",
		Cap:      0,
	},
	StatIdHpRecoveryOnHit: {
		StatId:   StatIdHpRecoveryOnHit,
		Name:     "hpRecoveryOnHit",
		Label:    "HP Recovery on Hit",
		Category: "resource",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdHpRecoveryOnCriticalHit: {
		StatId:   StatIdHpRecoveryOnCriticalHit,
		Name:     "hpRecoveryOnCriticalHit",
		Label:    "HP Recovery on Critical Hit",
		Category: "resource",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdResourceRecovery: {
		StatId:   StatIdResourceRecovery,
		Name:     "resourceRecovery",
		Label:    "MP/WP/SP Recovery",
		Category: "resource",
		Alias:    "mpwpspr",
		Unit:     "",
		Cap:      0,
	},
	StatIdResourceRecoveryOnHit: {
		StatId:   StatIdResourceRecoveryOnHit,
		Name:     "resourceRecoveryOnHit",
		Label:    "MP/WP/SP Recovery on Hit",
		Category: "resource",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdResourceRecoveryOnCriticalHit: {
		StatId:   StatIdResourceRecoveryOnCriticalHit,
		Name:     "resourceRecoveryOnCriticalHit",
		Label:    "MP/WP/SP Recovery on Critical Hit",
		Category: "resource",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdMaxEnergy: {
		StatId:   StatIdMaxEnergy,
		Name:     "maxEnergy",
		Label:    "Max Energy",
		Category: "resource",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdEnergyRecovery: {
		StatId:   StatIdEnergyRecovery,
		Name:     "energyRecovery",
		Label:    "Energy Recovery",
		Category: "resource",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdBlackSpiritRage: {
		StatId:   StatIdBlackSpiritRage,
		Name:     "blackSpiritRage",
		Label:    "Black Spirit's Rage",
		Category: "resource",
		Alias:    "bsr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdAllMastery: {
		StatId:   StatIdAllMastery,
		Name:     "allMastery",
		Label:    "All Life Mastery",
		Category: "mastery",
		Alias:    "mastall",
		Fanout:   []StatId{StatIdAlchemyMastery, StatIdGatheringMastery, StatIdCookingMastery, StatIdHuntingMastery, StatIdFarmingMastery, StatIdProcessingMastery, StatIdSailingMastery, StatIdTradingMastery, StatIdTrainingMastery, StatIdFishingMastery},
		Unit:     "",
		Cap:      0,
	},
	StatIdGatheringMastery: {
		StatId:   StatIdGatheringMastery,
		Name:     "gatheringMastery",
		Label:    "Gathering Mastery",
		Category: "mastery",
		Alias:    "mastgath",
		Fanout:   []StatId{StatIdButcherMastery, StatIdPickaxeMastery, StatIdHoeMastery, StatIdTanningMastery, StatIdLumberingMastery, StatIdFluidCollectorMastery},
		Unit:     "",
		Cap:      0,
	},
	StatIdHoeMastery: {
		StatId:   StatIdHoeMastery,
		Name:     "hoeMastery",
		Label:    "Hoe Mastery",
		Category: "mastery",
		Alias:    "masthoe",
		Unit:     "",
		Cap:      0,
	},
	StatIdLumberingMastery: {
		StatId:   StatIdLumberingMastery,
		Name:     "lumberingMastery",
		Label:    "Lumbering Axe Mastery",
		Category: "mastery",
		Alias:    "mastlumb",
		Unit:     "",
		Cap:      0,
	},
	StatIdFluidCollectorMastery: {
		StatId:   StatIdFluidCollectorMastery,
		Name:     "fluidCollectorMastery",
		Label:    "Fluid Collector Mastery",
		Category: "mastery",
		Alias:    "mastflui",
		Unit:     "",
		Cap:      0,
	},
	StatIdTanningMastery: {
		StatId:   StatIdTanningMastery,
		Name:     "tanningMastery",
		Label:    "Tanning Knife Mastery",
		Category: "mastery",
		Alias:    "masttann",
		Unit:     "",
		Cap:      0,
	},
	StatIdButcherMastery: {
		StatId:   StatIdButcherMastery,
		Name:     "butcherMastery",
		Label:    "Butcher Knife Mastery",
		Category: "mastery",
		Alias:    "mastbutc",
		Unit:     "",
		Cap:      0,
	},
	StatIdPickaxeMastery: {
		StatId:   StatIdPickaxeMastery,
		Name:     "pickaxeMastery",
		Label:    "Pickaxe Mastery",
		Category: "mastery",
		Alias:    "mastpick",
		Unit:     "",
		Cap:      0,
	},
	StatIdFishingMastery: {
		StatId:   StatIdFishingMastery,
		Name:     "fishingMastery",
		Label:    "Fishing Mastery",
		Category: "mastery",
		Alias:    "mastfish",
		Unit:     "",
		Cap:      0,
	},
	StatIdHuntingMastery: {
		StatId:   StatIdHuntingMastery,
		Name:     "huntingMastery",
		Label:    "Hunting Mastery",
		Category: "mastery",
		Alias:    "masthunt",
		Unit:     "",
		Cap:      0,
	},
	StatIdCookingMastery: {
		StatId:   StatIdCookingMastery,
		Name:     "cookingMastery",
		Label:    "Cooking Mastery",
		Category: "mastery",
		Alias:    "mastcook",
		Unit:     "",
		Cap:      0,
	},
	StatIdAlchemyMastery: {
		StatId:   StatIdAlchemyMastery,
		Name:     "alchemyMastery",
		Label:    "Alchemy Mastery",
		Category: "mastery",
		Alias:    "mastalch",
		Unit:     "",
		Cap:      0,
	},
	StatIdProcessingMastery: {
		StatId:   StatIdProcessingMastery,
		Name:     "processingMastery",
		Label:    "Processing Mastery",
		Category: "mastery",
		Alias:    "mastproc",
		Fanout:   []StatId{StatIdFilteringMastery, StatIdDryingMastery, StatIdGrindingMastery, StatIdHeatingMastery, StatIdChoppingMastery, StatIdShakingMastery},
		Unit:     "",
		Cap:      0,
	},
	StatIdTrainingMastery: {
		StatId:   StatIdTrainingMastery,
		Name:     "trainingMastery",
		Label:    "Training Mastery",
		Category: "mastery",
		Alias:    "masttrai",
		Unit:     "",
		Cap:      0,
	},
	StatIdSailingMastery: {
		StatId:   StatIdSailingMastery,
		Name:     "sailingMastery",
		Label:    "Sailing Mastery",
		Category: "mastery",
		Alias:    "mastsail",
		Unit:     "",
		Cap:      0,
	},
	StatIdLifeExp: {
		StatId:   StatIdLifeExp,
		Name:     "lifeExp",
		Label:    "Life EXP",
		Category: "life",
		Alias:    "explifeall",
		Unit:     "%",
		Cap:      0,
	},
	StatIdCombatExp: {
		StatId:   StatIdCombatExp,
		Name:     "combatExp",
		Label:    "Combat EXP",
		Category: "life",
		Alias:    "expcom",
		Unit:     "%",
		Cap:      0,
	},
	StatIdSkillExp: {
		StatId:   StatIdSkillExp,
		Name:     "skillExp",
		Label:    "Skill EXP",
		Category: "life",
		Alias:    "expski",
		Unit:     "%",
		Cap:      0,
	},
	StatIdGatheringExp: {
		StatId:   StatIdGatheringExp,
		Name:     "gatheringExp",
		Label:    "Gathering EXP",
		Category: "life",
		Alias:    "expgat",
		Unit:     "%",
		Cap:      0,
	},
	StatIdHuntingExp: {
		StatId:   StatIdHuntingExp,
		Name:     "huntingExp",
		Label:    "Hunting EXP",
		Category: "life",
		Alias:    "exphun",
		Unit:     "%",
		Cap:      0,
	},
	StatIdCookingExp: {
		StatId:   StatIdCookingExp,
		Name:     "cookingExp",
		Label:    "Cooking EXP",
		Category: "life",
		Alias:    "expcoo",
		Unit:     "%",
		Cap:      0,
	},
	StatIdAlchemyExp: {
		StatId:   StatIdAlchemyExp,
		Name:     "alchemyExp",
		Label:    "Alchemy EXP",
		Category: "life",
		Alias:    "expalc",
		Unit:     "%",
		Cap:      0,
	},
	StatIdFishingExp: {
		StatId:   StatIdFishingExp,
		Name:     "fishingExp",
		Label:    "Fishing EXP",
		Category: "life",
		Alias:    "expfis",
		Unit:     "%",
		Cap:      0,
	},
	StatIdProcessingExp: {
		StatId:   StatIdProcessingExp,
		Name:     "processingExp",
		Label:    "Processing EXP",
		Category: "life",
		Alias:    "exppro",
		Unit:     "%",
		Cap:      0,
	},
	StatIdTrainingExp: {
		StatId:   StatIdTrainingExp,
		Name:     "trainingExp",
		Label:    "Training EXP",
		Category: "life",
		Alias:    "exptrai",
		Unit:     "%",
		Cap:      0,
	},
	StatIdSailingExp: {
		StatId:   StatIdSailingExp,
		Name:     "sailingExp",
		Label:    "Sailing EXP",
		Category: "life",
		Alias:    "expsai",
		Unit:     "%",
		Cap:      0,
	},
	StatIdBarteringExp: {
		StatId:   StatIdBarteringExp,
		Name:     "barteringExp",
		Label:    "Bartering EXP",
		Category: "life",
		Alias:    "expbar",
		Unit:     "%",
		Cap:      0,
	},
	StatIdTradingExp: {
		StatId:   StatIdTradingExp,
		Name:     "tradingExp",
		Label:    "Trading EXP",
		Category: "life",
		Alias:    "exptrad",
		Unit:     "%",
		Cap:      0,
	},
	StatIdFarmingExp: {
		StatId:   StatIdFarmingExp,
		Name:     "farmingExp",
		Label:    "Farming EXP",
		Category: "life",
		Alias:    "expfar",
		Unit:     "%",
		Cap:      0,
	},
	StatIdMountExp: {
		StatId:   StatIdMountExp,
		Name:     "mountExp",
		Label:    "Mount EXP",
		Category: "life",
		Alias:    "expmou",
		Unit:     "%",
		Cap:      0,
	},
	StatIdMountSkillExp: {
		StatId:   StatIdMountSkillExp,
		Name:     "mountSkillExp",
		Label:    "Mount Skill EXP",
		Category: "life",
		Alias:    "expsmou",
		Unit:     "%",
		Cap:      0,
	},
	StatIdStrengthExp: {
		StatId:   StatIdStrengthExp,
		Name:     "strengthExp",
		Label:    "Strength EXP",
		Category: "life",
		Alias:    "expstr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdBreathExp: {
		StatId:   StatIdBreathExp,
		Name:     "breathExp",
		Label:    "Breath EXP",
		Category: "life",
		Alias:    "expbre",
		Unit:     "%",
		Cap:      0,
	},
	StatIdHealthExp: {
		StatId:   StatIdHealthExp,
		Name:     "healthExp",
		Label:    "Health EXP",
		Category: "life",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdGatheringTime: {
		StatId:   StatIdGatheringTime,
		Name:     "gatheringTime",
		Label:    "Gathering Time",
		Category: "life",
		Alias:    "timegath",
		Unit:     "sec",
		Cap:      0,
	},
	StatIdCookingTime: {
		StatId:   StatIdCookingTime,
		Name:     "cookingTime",
		Label:    "Cooking Time",
		Category: "life",
		Alias:    "timecook",
		Unit:     "sec",
		Cap:      0,
	},
	StatIdAlchemyTime: {
		StatId:   StatIdAlchemyTime,
		Name:     "alchemyTime",
		Label:    "Alchemy Time",
		Category: "life",
		Alias:    "timealch",
		Unit:     "sec",
		Cap:      0,
	},
	StatIdGatheringDropRate: {
		StatId:   StatIdGatheringDropRate,
		Name:     "gatheringDropRate",
		Label:    "Gathering Item Drop Rate",
		Category: "life",
		Alias:    "gatidr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdAutoFishingTime: {
		StatId:   StatIdAutoFishingTime,
		Name:     "autoFishingTime",
		Label:    "Auto-Fishing Time",
		Category: "life",
		Alias:    "aft",
		Unit:     "%",
		Cap:      0,
	},
	StatIdRareFishChance: {
		StatId:   StatIdRareFishChance,
		Name:     "rareFishChance",
		Label:    "Rare Fish Chance",
		Category: "life",
		Alias:    "ctcrf",
		Unit:     "",
		Cap:      0,
	},
	StatIdHorseCaptureRate: {
		StatId:   StatIdHorseCaptureRate,
		Name:     "horseCaptureRate",
		Label:    "Horse Capture Rate",
		Category: "life",
		Alias:    "hcr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdProcessingSuccessRate: {
		StatId:   StatIdProcessingSuccessRate,
		Name:     "processingSuccessRate",
		Label:    "Processing Success Rate",
		Category: "life",
		Alias:    "psr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdAmity: {
		StatId:   StatIdAmity,
		Name:     "amity",
		Label:    "Amity",
		Category: "misc",
		Alias:    "am",
		Unit:     "%",
		Cap:      0,
	},
	StatIdDeathPenaltyResistance: {
		StatId:   StatIdDeathPenaltyResistance,
		Name:     "deathPenaltyResistance",
		Label:    "Death Penalty Resistance",
		Category: "misc",
		Alias:    "dpr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdDurabilityLossResistance: {
		StatId:   StatIdDurabilityLossResistance,
		Name:     "durabilityLossResistance",
		Label:    "Durability Reduction Resistance",
		Category: "misc",
		Alias:    "drr",
		Unit:     "%",
		Cap:      0,
	},
	StatIdFallDamage: {
		StatId:   StatIdFallDamage,
		Name:     "fallDamage",
		Label:    "Fall Damage",
		Category: "misc",
		Alias:    "fd",
		Unit:     "%",
		Cap:      0,
	},
	StatIdItemDropRate: {
		StatId:   StatIdItemDropRate,
		Name:     "itemDropRate",
		Label:    "Item Drop Rate",
		Category: "misc",
		Alias:    "idc",
		Unit:     "%",
		Cap:      0,
	},
	StatIdItemDropAmount: {
		StatId:   StatIdItemDropAmount,
		Name:     "itemDropAmount",
		Label:    "Item Drop Amount",
		Category: "misc",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdHigherGradeKnowledgeChance: {
		StatId:   StatIdHigherGradeKnowledgeChance,
		Name:     "higherGradeKnowledgeChance",
		Label:    "Higher Grade Knowledge Gain Chance",
		Category: "misc",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdKarmaRecovery: {
		StatId:   StatIdKarmaRecovery,
		Name:     "karmaRecovery",
		Label:    "Karma Recovery",
		Category: "misc",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdSwimmingSpeed: {
		StatId:   StatIdSwimmingSpeed,
		Name:     "swimmingSpeed",
		Label:    "Swimming Speed",
		Category: "misc",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdHeatstrokeResistance: {
		StatId:   StatIdHeatstrokeResistance,
		Name:     "heatstrokeResistance",
		Label:    "Heatstroke Resistance",
		Category: "misc",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdHypothermiaResistance: {
		StatId:   StatIdHypothermiaResistance,
		Name:     "hypothermiaResistance",
		Label:    "Hypothermia Resistance",
		Category: "misc",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdJumpHeight: {
		StatId:   StatIdJumpHeight,
		Name:     "jumpHeight",
		Label:    "Jump Height",
		Category: "misc",
		Alias:    "jhm",
		Unit:     "m",
		Cap:      0,
	},
	StatIdKnowledgeChance: {
		StatId:   StatIdKnowledgeChance,
		Name:     "knowledgeChance",
		Label:    "Knowledge Gain Chance",
		Category: "misc",
		Alias:    "kac",
		Unit:     "%",
		Cap:      0,
	},
	StatIdMermaidsWish: {
		StatId:   StatIdMermaidsWish,
		Name:     "mermaidsWish",
		Label:    "Mermaid's Wish",
		Category: "misc",
		Alias:    "merwish",
		Unit:     "",
		Cap:      0,
	},
	StatIdUnderwaterBreathing: {
		StatId:   StatIdUnderwaterBreathing,
		Name:     "underwaterBreathing",
		Label:    "Underwater Breathing",
		Category: "misc",
		Alias:    "ub",
		Unit:     "sec",
		Cap:      0,
	},
	StatIdWeightLimit: {
		StatId:   StatIdWeightLimit,
		Name:     "weightLimit",
		Label:    "Weight Limit",
		Category: "misc",
		Alias:    "wl",
		Unit:     "LT",
		Cap:      0,
	},
	StatIdAp: {
		StatId:   StatIdAp,
		Name:     "ap",
		Label:    "AP",
		Category: "apBucket",
		Alias:    "ap",
		Fanout:   []StatId{StatIdTotalAp},
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningAp: {
		StatId:   StatIdAwakeningAp,
		Name:     "awakeningAp",
		Label:    "Awakening AP",
		Category: "apBucket",
		Alias:    "aap",
		Fanout:   []StatId{StatIdTotalAwakeningAp},
		Unit:     "",
		Cap:      0,
	},
	StatIdTotalAp: {
		StatId:   StatIdTotalAp,
		Name:     "totalAp",
		Label:    "Total AP",
		Category: "apBucket",
		Alias:    "totalap",
		Fanout:   []StatId{StatIdApVsMonster, StatIdApVsAdventurer, StatIdApVsKamasylvian, StatIdApVsHuman, StatIdApVsDemihuman, StatIdApVsNormal, StatIdApVsEdania},
		Unit:     "",
		Cap:      0,
	},
	StatIdTotalAwakeningAp: {
		StatId:   StatIdTotalAwakeningAp,
		Name:     "totalAwakeningAp",
		Label:    "Total Awakening AP",
		Category: "apBucket",
		Alias:    "totalaap",
		Fanout:   []StatId{StatIdAwakeningApVsMonster, StatIdAwakeningApVsAdventurer, StatIdAwakeningApVsKamasylvian, StatIdAwakeningApVsHuman, StatIdAwakeningApVsDemihuman, StatIdAwakeningApVsNormal, StatIdAwakeningApVsEdania},
		Unit:     "",
		Cap:      0,
	},
	StatIdBracketAp: {
		StatId:   StatIdBracketAp,
		Name:     "bracketAp",
		Label:    "Bracket Bonus AP",
		Category: "apBucket",
		Alias:    "bap",
		Fanout:   []StatId{StatIdTotalAp},
		Unit:     "",
		Cap:      0,
	},
	StatIdBracketAwakeningAp: {
		StatId:   StatIdBracketAwakeningAp,
		Name:     "bracketAwakeningAp",
		Label:    "Bracket Bonus Awakening AP",
		Category: "apBucket",
		Alias:    "baap",
		Fanout:   []StatId{StatIdTotalAwakeningAp},
		Unit:     "",
		Cap:      0,
	},
	StatIdBracketMonsterAp: {
		StatId:   StatIdBracketMonsterAp,
		Name:     "bracketMonsterAp",
		Label:    "Bracket Bonus AP vs Monsters",
		Category: "apBucket",
		Alias:    "beaam",
		Fanout:   []StatId{StatIdApVsMonster, StatIdApVsKamasylvian, StatIdApVsHuman, StatIdApVsDemihuman, StatIdApVsNormal, StatIdApVsEdania},
		Unit:     "",
		Cap:      0,
	},
	StatIdBracketMonsterAwakeningAp: {
		StatId:   StatIdBracketMonsterAwakeningAp,
		Name:     "bracketMonsterAwakeningAp",
		Label:    "Bracket Bonus Awakening AP vs Monsters",
		Category: "apBucket",
		Alias:    "beaaam",
		Fanout:   []StatId{StatIdAwakeningApVsMonster, StatIdAwakeningApVsKamasylvian, StatIdAwakeningApVsHuman, StatIdAwakeningApVsDemihuman, StatIdAwakeningApVsNormal, StatIdAwakeningApVsEdania},
		Unit:     "",
		Cap:      0,
	},
	StatIdApVsMonster: {
		StatId:   StatIdApVsMonster,
		Name:     "apVsMonster",
		Label:    "AP vs Monsters",
		Category: "apBucket",
		Alias:    "monsterap",
		Unit:     "",
		Cap:      0,
	},
	StatIdApVsAdventurer: {
		StatId:   StatIdApVsAdventurer,
		Name:     "apVsAdventurer",
		Label:    "AP vs Adventurers",
		Category: "apBucket",
		Alias:    "adventureap",
		Unit:     "",
		Cap:      0,
	},
	StatIdApVsHuman: {
		StatId:   StatIdApVsHuman,
		Name:     "apVsHuman",
		Label:    "AP vs Humans",
		Category: "apBucket",
		Alias:    "humanap",
		Unit:     "",
		Cap:      0,
	},
	StatIdApVsDemihuman: {
		StatId:   StatIdApVsDemihuman,
		Name:     "apVsDemihuman",
		Label:    "AP vs Demihumans",
		Category: "apBucket",
		Alias:    "demiap",
		Unit:     "",
		Cap:      0,
	},
	StatIdApVsKamasylvian: {
		StatId:   StatIdApVsKamasylvian,
		Name:     "apVsKamasylvian",
		Label:    "AP vs Kamasylvian",
		Category: "apBucket",
		Alias:    "kamaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdApVsEdania: {
		StatId:   StatIdApVsEdania,
		Name:     "apVsEdania",
		Label:    "AP vs Edania",
		Category: "apBucket",
		Alias:    "edaniaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdApVsNormal: {
		StatId:   StatIdApVsNormal,
		Name:     "apVsNormal",
		Label:    "AP vs Normal",
		Category: "apBucket",
		Alias:    "normalap",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApVsMonster: {
		StatId:   StatIdAwakeningApVsMonster,
		Name:     "awakeningApVsMonster",
		Label:    "Awakening AP vs Monsters",
		Category: "apBucket",
		Alias:    "monsteraap",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApVsAdventurer: {
		StatId:   StatIdAwakeningApVsAdventurer,
		Name:     "awakeningApVsAdventurer",
		Label:    "Awakening AP vs Adventurers",
		Category: "apBucket",
		Alias:    "adventureaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApVsHuman: {
		StatId:   StatIdAwakeningApVsHuman,
		Name:     "awakeningApVsHuman",
		Label:    "Awakening AP vs Humans",
		Category: "apBucket",
		Alias:    "humanaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApVsDemihuman: {
		StatId:   StatIdAwakeningApVsDemihuman,
		Name:     "awakeningApVsDemihuman",
		Label:    "Awakening AP vs Demihumans",
		Category: "apBucket",
		Alias:    "demiaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApVsKamasylvian: {
		StatId:   StatIdAwakeningApVsKamasylvian,
		Name:     "awakeningApVsKamasylvian",
		Label:    "Awakening AP vs Kamasylvian",
		Category: "apBucket",
		Alias:    "kamaaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApVsEdania: {
		StatId:   StatIdAwakeningApVsEdania,
		Name:     "awakeningApVsEdania",
		Label:    "Awakening AP vs Edania",
		Category: "apBucket",
		Alias:    "edaniaaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApVsNormal: {
		StatId:   StatIdAwakeningApVsNormal,
		Name:     "awakeningApVsNormal",
		Label:    "Awakening AP vs Normal",
		Category: "apBucket",
		Alias:    "normalaap",
		Unit:     "",
		Cap:      0,
	},
	StatIdNormalAp: {
		StatId:   StatIdNormalAp,
		Name:     "normalAp",
		Label:    "Extra AP Against Normal",
		Category: "ap",
		Alias:    "edta",
		Fanout:   []StatId{StatIdApVsNormal, StatIdAwakeningApVsNormal},
		Unit:     "",
		Cap:      0,
	},
	StatIdEdaniaAp: {
		StatId:   StatIdEdaniaAp,
		Name:     "edaniaAp",
		Label:    "Extra AP Against Edanian Monsters",
		Category: "ap",
		Alias:    "edtae",
		Fanout:   []StatId{StatIdApVsEdania, StatIdAwakeningApVsEdania},
		Unit:     "",
		Cap:      0,
	},
	StatIdBeastAp: {
		StatId:   StatIdBeastAp,
		Name:     "beastAp",
		Label:    "Extra AP Against Beasts",
		Category: "ap",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
	StatIdDamageReduction: {
		StatId:   StatIdDamageReduction,
		Name:     "damageReduction",
		Label:    "Damage Reduction",
		Category: "aggregate",
		Alias:    "dr",
		Fanout:   []StatId{StatIdMeleeDamageReduction, StatIdRangedDamageReduction, StatIdMagicDamageReduction, StatIdMeleeMonsterDamageReduction, StatIdRangedMonsterDamageReduction, StatIdMagicMonsterDamageReduction},
		Unit:     "",
		Cap:      0,
	},
	StatIdTotalDamageReduction: {
		StatId:   StatIdTotalDamageReduction,
		Name:     "totalDamageReduction",
		Label:    "Total Damage Reduction",
		Category: "aggregate",
		Alias:    "totaldr",
		Fanout:   []StatId{StatIdMeleeDamageReduction, StatIdRangedDamageReduction, StatIdMagicDamageReduction, StatIdMeleeMonsterDamageReduction, StatIdRangedMonsterDamageReduction, StatIdMagicMonsterDamageReduction},
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenDamageReduction: {
		StatId:   StatIdHiddenDamageReduction,
		Name:     "hiddenDamageReduction",
		Label:    "Hidden Damage Reduction",
		Category: "hidden",
		Alias:    "hdr",
		Fanout:   []StatId{StatIdMeleeDamageReduction, StatIdRangedDamageReduction, StatIdMagicDamageReduction, StatIdMeleeMonsterDamageReduction, StatIdRangedMonsterDamageReduction, StatIdMagicMonsterDamageReduction},
		Unit:     "",
		Cap:      0,
	},
	StatIdMonsterDamageReduction: {
		StatId:   StatIdMonsterDamageReduction,
		Name:     "monsterDamageReduction",
		Label:    "Monster Damage Reduction",
		Category: "defense",
		Alias:    "mdr",
		Fanout:   []StatId{StatIdMeleeMonsterDamageReduction, StatIdRangedMonsterDamageReduction, StatIdMagicMonsterDamageReduction},
		Unit:     "",
		Cap:      0,
	},
	StatIdMonsterDamageReductionRate: {
		StatId:   StatIdMonsterDamageReductionRate,
		Name:     "monsterDamageReductionRate",
		Label:    "Monster Damage Reduction Rate",
		Category: "defense",
		Alias:    "",
		Unit:     "%",
		Cap:      0,
	},
	StatIdMeleeMonsterDamageReduction: {
		StatId:   StatIdMeleeMonsterDamageReduction,
		Name:     "meleeMonsterDamageReduction",
		Label:    "Melee Damage Reduction vs Monsters",
		Category: "defense",
		Alias:    "memdr",
		Unit:     "",
		Cap:      0,
	},
	StatIdRangedMonsterDamageReduction: {
		StatId:   StatIdRangedMonsterDamageReduction,
		Name:     "rangedMonsterDamageReduction",
		Label:    "Ranged Damage Reduction vs Monsters",
		Category: "defense",
		Alias:    "ramdr",
		Unit:     "",
		Cap:      0,
	},
	StatIdMagicMonsterDamageReduction: {
		StatId:   StatIdMagicMonsterDamageReduction,
		Name:     "magicMonsterDamageReduction",
		Label:    "Magic Damage Reduction vs Monsters",
		Category: "defense",
		Alias:    "mamdr",
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenMeleeDamageReduction: {
		StatId:   StatIdHiddenMeleeDamageReduction,
		Name:     "hiddenMeleeDamageReduction",
		Label:    "Hidden Melee Damage Reduction",
		Category: "hidden",
		Alias:    "hmedr",
		Fanout:   []StatId{StatIdMeleeDamageReduction, StatIdMeleeMonsterDamageReduction},
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenRangedDamageReduction: {
		StatId:   StatIdHiddenRangedDamageReduction,
		Name:     "hiddenRangedDamageReduction",
		Label:    "Hidden Ranged Damage Reduction",
		Category: "hidden",
		Alias:    "hradr",
		Fanout:   []StatId{StatIdRangedDamageReduction, StatIdRangedMonsterDamageReduction},
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenMagicDamageReduction: {
		StatId:   StatIdHiddenMagicDamageReduction,
		Name:     "hiddenMagicDamageReduction",
		Label:    "Hidden Magic Damage Reduction",
		Category: "hidden",
		Alias:    "hmadr",
		Fanout:   []StatId{StatIdMagicDamageReduction, StatIdMagicMonsterDamageReduction},
		Unit:     "",
		Cap:      0,
	},
	StatIdEvasion: {
		StatId:   StatIdEvasion,
		Name:     "evasion",
		Label:    "Evasion",
		Category: "aggregate",
		Alias:    "ev",
		Fanout:   []StatId{StatIdMeleeEvasion, StatIdRangedEvasion, StatIdMagicEvasion},
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenEvasion: {
		StatId:   StatIdHiddenEvasion,
		Name:     "hiddenEvasion",
		Label:    "Hidden Evasion",
		Category: "hidden",
		Alias:    "hev",
		Fanout:   []StatId{StatIdEvasion},
		Unit:     "",
		Cap:      0,
	},
	StatIdEvasionRate: {
		StatId:   StatIdEvasionRate,
		Name:     "evasionRate",
		Label:    "Evasion Rate",
		Category: "defense",
		Alias:    "evr",
		Fanout:   []StatId{StatIdMeleeEvasionRate, StatIdRangedEvasionRate, StatIdMagicEvasionRate},
		Unit:     "",
		Cap:      0,
	},
	StatIdMeleeEvasionRate: {
		StatId:   StatIdMeleeEvasionRate,
		Name:     "meleeEvasionRate",
		Label:    "Melee Evasion Rate",
		Category: "defense",
		Alias:    "meevr",
		Unit:     "",
		Cap:      0,
	},
	StatIdRangedEvasionRate: {
		StatId:   StatIdRangedEvasionRate,
		Name:     "rangedEvasionRate",
		Label:    "Ranged Evasion Rate",
		Category: "defense",
		Alias:    "raevr",
		Unit:     "",
		Cap:      0,
	},
	StatIdMagicEvasionRate: {
		StatId:   StatIdMagicEvasionRate,
		Name:     "magicEvasionRate",
		Label:    "Magic Evasion Rate",
		Category: "defense",
		Alias:    "maevr",
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenMeleeEvasion: {
		StatId:   StatIdHiddenMeleeEvasion,
		Name:     "hiddenMeleeEvasion",
		Label:    "Hidden Melee Evasion",
		Category: "hidden",
		Alias:    "hmeev",
		Fanout:   []StatId{StatIdMeleeEvasion},
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenRangedEvasion: {
		StatId:   StatIdHiddenRangedEvasion,
		Name:     "hiddenRangedEvasion",
		Label:    "Hidden Ranged Evasion",
		Category: "hidden",
		Alias:    "hraev",
		Fanout:   []StatId{StatIdRangedEvasion},
		Unit:     "",
		Cap:      0,
	},
	StatIdHiddenMagicEvasion: {
		StatId:   StatIdHiddenMagicEvasion,
		Name:     "hiddenMagicEvasion",
		Label:    "Hidden Magic Evasion",
		Category: "hidden",
		Alias:    "hmaev",
		Fanout:   []StatId{StatIdMagicEvasion},
		Unit:     "",
		Cap:      0,
	},
	StatIdGrappleResistance: {
		StatId:   StatIdGrappleResistance,
		Name:     "grappleResistance",
		Label:    "Grapple Resistance",
		Category: "resistance",
		Alias:    "gr",
		Unit:     "",
		Cap:      0,
	},
	StatIdAirAttackDamage: {
		StatId:   StatIdAirAttackDamage,
		Name:     "airAttackDamage",
		Label:    "Air Attack Damage",
		Category: "damage",
		Alias:    "aaad",
		Unit:     "",
		Cap:      0,
	},
	StatIdCounterAttackDamage: {
		StatId:   StatIdCounterAttackDamage,
		Name:     "counterAttackDamage",
		Label:    "Counter Attack Damage",
		Category: "damage",
		Alias:    "acad",
		Unit:     "",
		Cap:      0,
	},
	StatIdSpeedAttackDamage: {
		StatId:   StatIdSpeedAttackDamage,
		Name:     "speedAttackDamage",
		Label:    "Speed Attack Damage",
		Category: "damage",
		Alias:    "asad",
		Unit:     "",
		Cap:      0,
	},
	StatIdFarmingMastery: {
		StatId:   StatIdFarmingMastery,
		Name:     "farmingMastery",
		Label:    "Farming Mastery",
		Category: "mastery",
		Alias:    "mastfarm",
		Unit:     "",
		Cap:      0,
	},
	StatIdTradingMastery: {
		StatId:   StatIdTradingMastery,
		Name:     "tradingMastery",
		Label:    "Trading Mastery",
		Category: "mastery",
		Alias:    "masttrad",
		Unit:     "",
		Cap:      0,
	},
	StatIdFilteringMastery: {
		StatId:   StatIdFilteringMastery,
		Name:     "filteringMastery",
		Label:    "Filtering Mastery",
		Category: "mastery",
		Alias:    "mastfilt",
		Unit:     "",
		Cap:      0,
	},
	StatIdDryingMastery: {
		StatId:   StatIdDryingMastery,
		Name:     "dryingMastery",
		Label:    "Drying Mastery",
		Category: "mastery",
		Alias:    "mastdryi",
		Unit:     "",
		Cap:      0,
	},
	StatIdGrindingMastery: {
		StatId:   StatIdGrindingMastery,
		Name:     "grindingMastery",
		Label:    "Grinding Mastery",
		Category: "mastery",
		Alias:    "mastgrin",
		Unit:     "",
		Cap:      0,
	},
	StatIdHeatingMastery: {
		StatId:   StatIdHeatingMastery,
		Name:     "heatingMastery",
		Label:    "Heating Mastery",
		Category: "mastery",
		Alias:    "mastheat",
		Unit:     "",
		Cap:      0,
	},
	StatIdChoppingMastery: {
		StatId:   StatIdChoppingMastery,
		Name:     "choppingMastery",
		Label:    "Chopping Mastery",
		Category: "mastery",
		Alias:    "mastchop",
		Unit:     "",
		Cap:      0,
	},
	StatIdShakingMastery: {
		StatId:   StatIdShakingMastery,
		Name:     "shakingMastery",
		Label:    "Shaking Mastery",
		Category: "mastery",
		Alias:    "mastshak",
		Unit:     "",
		Cap:      0,
	},
	StatIdMaxResource: {
		StatId:   StatIdMaxResource,
		Name:     "maxResource",
		Label:    "Max MP/WP/SP",
		Category: "resource",
		Alias:    "mpwpsp",
		Unit:     "",
		Cap:      0,
	},
	StatIdMaxStamina: {
		StatId:   StatIdMaxStamina,
		Name:     "maxStamina",
		Label:    "Max Stamina",
		Category: "resource",
		Alias:    "stam",
		Unit:     "",
		Cap:      0,
	},
	StatIdApMin: {
		StatId:   StatIdApMin,
		Name:     "apMin",
		Label:    "Min AP",
		Category: "apBucket",
		Alias:    "apmin",
		Unit:     "",
		Cap:      0,
	},
	StatIdApMax: {
		StatId:   StatIdApMax,
		Name:     "apMax",
		Label:    "Max AP",
		Category: "apBucket",
		Alias:    "apmax",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApMin: {
		StatId:   StatIdAwakeningApMin,
		Name:     "awakeningApMin",
		Label:    "Min Awakening AP",
		Category: "apBucket",
		Alias:    "aapmin",
		Unit:     "",
		Cap:      0,
	},
	StatIdAwakeningApMax: {
		StatId:   StatIdAwakeningApMax,
		Name:     "awakeningApMax",
		Label:    "Max Awakening AP",
		Category: "apBucket",
		Alias:    "aapmax",
		Unit:     "",
		Cap:      0,
	},
	StatIdCritLevel: {
		StatId:   StatIdCritLevel,
		Name:     "critLevel",
		Label:    "Critical Hit",
		Category: "offense",
		Alias:    "chr",
		Unit:     "",
		Cap:      5,
	},
	StatIdCritChance: {
		StatId:   StatIdCritChance,
		Name:     "critChance",
		Label:    "Critical Hit Chance",
		Category: "offense",
		Alias:    "chc",
		Unit:     "%",
		Cap:      0,
	},
	StatIdFishingSpeed: {
		StatId:   StatIdFishingSpeed,
		Name:     "fishingSpeed",
		Label:    "Fishing Speed",
		Category: "life",
		Alias:    "fa",
		Unit:     "",
		Cap:      5,
	},
	StatIdAttackSpeedLevel: {
		StatId:   StatIdAttackSpeedLevel,
		Name:     "attackSpeedLevel",
		Label:    "Attack Speed Level",
		Category: "combat",
		Alias:    "as",
		Unit:     "",
		Cap:      5,
	},
	StatIdCastingSpeedLevel: {
		StatId:   StatIdCastingSpeedLevel,
		Name:     "castingSpeedLevel",
		Label:    "Casting Speed Level",
		Category: "combat",
		Alias:    "cs",
		Unit:     "",
		Cap:      5,
	},
	StatIdMovementSpeedLevel: {
		StatId:   StatIdMovementSpeedLevel,
		Name:     "movementSpeedLevel",
		Label:    "Movement Speed Level",
		Category: "combat",
		Alias:    "ms",
		Unit:     "",
		Cap:      5,
	},
	StatIdGatheringSpeed: {
		StatId:   StatIdGatheringSpeed,
		Name:     "gatheringSpeed",
		Label:    "Gathering Speed",
		Category: "life",
		Alias:    "ga",
		Unit:     "",
		Cap:      5,
	},
	StatIdWorkerStaminaRecovery: {
		StatId:   StatIdWorkerStaminaRecovery,
		Name:     "workerStaminaRecovery",
		Label:    "Worker Stamina Recovery",
		Category: "life",
		Alias:    "",
		Unit:     "",
		Cap:      0,
	},
}

var statIdValues = []StatId{
	StatIdMonsterAp,
	StatIdAdventurerAp,
	StatIdHumanAp,
	StatIdDemihumanAp,
	StatIdKamasylvianAp,
	StatIdAllSpeciesAp,
	StatIdHiddenAp,
	StatIdDp,
	StatIdMeleeAp,
	StatIdRangedAp,
	StatIdMagicAp,
	StatIdCritDamage,
	StatIdSpecialAttackDamage,
	StatIdBackAttackDamage,
	StatIdDownAttackDamage,
	StatIdHuntingDamage,
	StatIdAccuracy,
	StatIdMeleeAccuracy,
	StatIdRangedAccuracy,
	StatIdMagicAccuracy,
	StatIdMeleeEvasion,
	StatIdRangedEvasion,
	StatIdMagicEvasion,
	StatIdMeleeDamageReduction,
	StatIdRangedDamageReduction,
	StatIdMagicDamageReduction,
	StatIdDamageReductionRate,
	StatIdAllResistance,
	StatIdStunResistance,
	StatIdKnockdownResistance,
	StatIdKnockbackResistance,
	StatIdFearResistance,
	StatIdIgnoreAllResistance,
	StatIdIgnoreGrappleResistance,
	StatIdIgnoreKnockbackResistance,
	StatIdIgnoreKnockdownResistance,
	StatIdIgnoreStunResistance,
	StatIdAttackSpeed,
	StatIdCastingSpeed,
	StatIdMoveSpeed,
	StatIdLuck,
	StatIdMaxHp,
	StatIdHpRecovery,
	StatIdHpRecoveryOnHit,
	StatIdHpRecoveryOnCriticalHit,
	StatIdResourceRecovery,
	StatIdResourceRecoveryOnHit,
	StatIdResourceRecoveryOnCriticalHit,
	StatIdMaxEnergy,
	StatIdEnergyRecovery,
	StatIdBlackSpiritRage,
	StatIdAllMastery,
	StatIdGatheringMastery,
	StatIdHoeMastery,
	StatIdLumberingMastery,
	StatIdFluidCollectorMastery,
	StatIdTanningMastery,
	StatIdButcherMastery,
	StatIdPickaxeMastery,
	StatIdFishingMastery,
	StatIdHuntingMastery,
	StatIdCookingMastery,
	StatIdAlchemyMastery,
	StatIdProcessingMastery,
	StatIdTrainingMastery,
	StatIdSailingMastery,
	StatIdLifeExp,
	StatIdCombatExp,
	StatIdSkillExp,
	StatIdGatheringExp,
	StatIdHuntingExp,
	StatIdCookingExp,
	StatIdAlchemyExp,
	StatIdFishingExp,
	StatIdProcessingExp,
	StatIdTrainingExp,
	StatIdSailingExp,
	StatIdBarteringExp,
	StatIdTradingExp,
	StatIdFarmingExp,
	StatIdMountExp,
	StatIdMountSkillExp,
	StatIdStrengthExp,
	StatIdBreathExp,
	StatIdHealthExp,
	StatIdGatheringTime,
	StatIdCookingTime,
	StatIdAlchemyTime,
	StatIdGatheringDropRate,
	StatIdAutoFishingTime,
	StatIdRareFishChance,
	StatIdHorseCaptureRate,
	StatIdProcessingSuccessRate,
	StatIdAmity,
	StatIdDeathPenaltyResistance,
	StatIdDurabilityLossResistance,
	StatIdFallDamage,
	StatIdItemDropRate,
	StatIdItemDropAmount,
	StatIdHigherGradeKnowledgeChance,
	StatIdKarmaRecovery,
	StatIdSwimmingSpeed,
	StatIdHeatstrokeResistance,
	StatIdHypothermiaResistance,
	StatIdJumpHeight,
	StatIdKnowledgeChance,
	StatIdMermaidsWish,
	StatIdUnderwaterBreathing,
	StatIdWeightLimit,
	StatIdAp,
	StatIdAwakeningAp,
	StatIdTotalAp,
	StatIdTotalAwakeningAp,
	StatIdBracketAp,
	StatIdBracketAwakeningAp,
	StatIdBracketMonsterAp,
	StatIdBracketMonsterAwakeningAp,
	StatIdApVsMonster,
	StatIdApVsAdventurer,
	StatIdApVsHuman,
	StatIdApVsDemihuman,
	StatIdApVsKamasylvian,
	StatIdApVsEdania,
	StatIdApVsNormal,
	StatIdAwakeningApVsMonster,
	StatIdAwakeningApVsAdventurer,
	StatIdAwakeningApVsHuman,
	StatIdAwakeningApVsDemihuman,
	StatIdAwakeningApVsKamasylvian,
	StatIdAwakeningApVsEdania,
	StatIdAwakeningApVsNormal,
	StatIdNormalAp,
	StatIdEdaniaAp,
	StatIdBeastAp,
	StatIdDamageReduction,
	StatIdTotalDamageReduction,
	StatIdHiddenDamageReduction,
	StatIdMonsterDamageReduction,
	StatIdMonsterDamageReductionRate,
	StatIdMeleeMonsterDamageReduction,
	StatIdRangedMonsterDamageReduction,
	StatIdMagicMonsterDamageReduction,
	StatIdHiddenMeleeDamageReduction,
	StatIdHiddenRangedDamageReduction,
	StatIdHiddenMagicDamageReduction,
	StatIdEvasion,
	StatIdHiddenEvasion,
	StatIdEvasionRate,
	StatIdMeleeEvasionRate,
	StatIdRangedEvasionRate,
	StatIdMagicEvasionRate,
	StatIdHiddenMeleeEvasion,
	StatIdHiddenRangedEvasion,
	StatIdHiddenMagicEvasion,
	StatIdGrappleResistance,
	StatIdAirAttackDamage,
	StatIdCounterAttackDamage,
	StatIdSpeedAttackDamage,
	StatIdFarmingMastery,
	StatIdTradingMastery,
	StatIdFilteringMastery,
	StatIdDryingMastery,
	StatIdGrindingMastery,
	StatIdHeatingMastery,
	StatIdChoppingMastery,
	StatIdShakingMastery,
	StatIdMaxResource,
	StatIdMaxStamina,
	StatIdApMin,
	StatIdApMax,
	StatIdAwakeningApMin,
	StatIdAwakeningApMax,
	StatIdCritLevel,
	StatIdCritChance,
	StatIdFishingSpeed,
	StatIdAttackSpeedLevel,
	StatIdCastingSpeedLevel,
	StatIdMovementSpeedLevel,
	StatIdGatheringSpeed,
	StatIdWorkerStaminaRecovery,
}

var statIdByName = map[string]StatId{
	"monsterap":                     StatIdMonsterAp,
	"adventurerap":                  StatIdAdventurerAp,
	"humanap":                       StatIdHumanAp,
	"demihumanap":                   StatIdDemihumanAp,
	"kamasylvianap":                 StatIdKamasylvianAp,
	"allspeciesap":                  StatIdAllSpeciesAp,
	"hiddenap":                      StatIdHiddenAp,
	"dp":                            StatIdDp,
	"meleeap":                       StatIdMeleeAp,
	"rangedap":                      StatIdRangedAp,
	"magicap":                       StatIdMagicAp,
	"critdamage":                    StatIdCritDamage,
	"specialattackdamage":           StatIdSpecialAttackDamage,
	"backattackdamage":              StatIdBackAttackDamage,
	"downattackdamage":              StatIdDownAttackDamage,
	"huntingdamage":                 StatIdHuntingDamage,
	"accuracy":                      StatIdAccuracy,
	"meleeaccuracy":                 StatIdMeleeAccuracy,
	"rangedaccuracy":                StatIdRangedAccuracy,
	"magicaccuracy":                 StatIdMagicAccuracy,
	"meleeevasion":                  StatIdMeleeEvasion,
	"rangedevasion":                 StatIdRangedEvasion,
	"magicevasion":                  StatIdMagicEvasion,
	"meleedamagereduction":          StatIdMeleeDamageReduction,
	"rangeddamagereduction":         StatIdRangedDamageReduction,
	"magicdamagereduction":          StatIdMagicDamageReduction,
	"damagereductionrate":           StatIdDamageReductionRate,
	"allresistance":                 StatIdAllResistance,
	"stunresistance":                StatIdStunResistance,
	"knockdownresistance":           StatIdKnockdownResistance,
	"knockbackresistance":           StatIdKnockbackResistance,
	"fearresistance":                StatIdFearResistance,
	"ignoreallresistance":           StatIdIgnoreAllResistance,
	"ignoregrappleresistance":       StatIdIgnoreGrappleResistance,
	"ignoreknockbackresistance":     StatIdIgnoreKnockbackResistance,
	"ignoreknockdownresistance":     StatIdIgnoreKnockdownResistance,
	"ignorestunresistance":          StatIdIgnoreStunResistance,
	"attackspeed":                   StatIdAttackSpeed,
	"castingspeed":                  StatIdCastingSpeed,
	"movespeed":                     StatIdMoveSpeed,
	"luck":                          StatIdLuck,
	"maxhp":                         StatIdMaxHp,
	"hprecovery":                    StatIdHpRecovery,
	"hprecoveryonhit":               StatIdHpRecoveryOnHit,
	"hprecoveryoncriticalhit":       StatIdHpRecoveryOnCriticalHit,
	"resourcerecovery":              StatIdResourceRecovery,
	"resourcerecoveryonhit":         StatIdResourceRecoveryOnHit,
	"resourcerecoveryoncriticalhit": StatIdResourceRecoveryOnCriticalHit,
	"maxenergy":                     StatIdMaxEnergy,
	"energyrecovery":                StatIdEnergyRecovery,
	"blackspiritrage":               StatIdBlackSpiritRage,
	"allmastery":                    StatIdAllMastery,
	"gatheringmastery":              StatIdGatheringMastery,
	"hoemastery":                    StatIdHoeMastery,
	"lumberingmastery":              StatIdLumberingMastery,
	"fluidcollectormastery":         StatIdFluidCollectorMastery,
	"tanningmastery":                StatIdTanningMastery,
	"butchermastery":                StatIdButcherMastery,
	"pickaxemastery":                StatIdPickaxeMastery,
	"fishingmastery":                StatIdFishingMastery,
	"huntingmastery":                StatIdHuntingMastery,
	"cookingmastery":                StatIdCookingMastery,
	"alchemymastery":                StatIdAlchemyMastery,
	"processingmastery":             StatIdProcessingMastery,
	"trainingmastery":               StatIdTrainingMastery,
	"sailingmastery":                StatIdSailingMastery,
	"lifeexp":                       StatIdLifeExp,
	"combatexp":                     StatIdCombatExp,
	"skillexp":                      StatIdSkillExp,
	"gatheringexp":                  StatIdGatheringExp,
	"huntingexp":                    StatIdHuntingExp,
	"cookingexp":                    StatIdCookingExp,
	"alchemyexp":                    StatIdAlchemyExp,
	"fishingexp":                    StatIdFishingExp,
	"processingexp":                 StatIdProcessingExp,
	"trainingexp":                   StatIdTrainingExp,
	"sailingexp":                    StatIdSailingExp,
	"barteringexp":                  StatIdBarteringExp,
	"tradingexp":                    StatIdTradingExp,
	"farmingexp":                    StatIdFarmingExp,
	"mountexp":                      StatIdMountExp,
	"mountskillexp":                 StatIdMountSkillExp,
	"strengthexp":                   StatIdStrengthExp,
	"breathexp":                     StatIdBreathExp,
	"healthexp":                     StatIdHealthExp,
	"gatheringtime":                 StatIdGatheringTime,
	"cookingtime":                   StatIdCookingTime,
	"alchemytime":                   StatIdAlchemyTime,
	"gatheringdroprate":             StatIdGatheringDropRate,
	"autofishingtime":               StatIdAutoFishingTime,
	"rarefishchance":                StatIdRareFishChance,
	"horsecapturerate":              StatIdHorseCaptureRate,
	"processingsuccessrate":         StatIdProcessingSuccessRate,
	"amity":                         StatIdAmity,
	"deathpenaltyresistance":        StatIdDeathPenaltyResistance,
	"durabilitylossresistance":      StatIdDurabilityLossResistance,
	"falldamage":                    StatIdFallDamage,
	"itemdroprate":                  StatIdItemDropRate,
	"itemdropamount":                StatIdItemDropAmount,
	"highergradeknowledgechance":    StatIdHigherGradeKnowledgeChance,
	"karmarecovery":                 StatIdKarmaRecovery,
	"swimmingspeed":                 StatIdSwimmingSpeed,
	"heatstrokeresistance":          StatIdHeatstrokeResistance,
	"hypothermiaresistance":         StatIdHypothermiaResistance,
	"jumpheight":                    StatIdJumpHeight,
	"knowledgechance":               StatIdKnowledgeChance,
	"mermaidswish":                  StatIdMermaidsWish,
	"underwaterbreathing":           StatIdUnderwaterBreathing,
	"weightlimit":                   StatIdWeightLimit,
	"ap":                            StatIdAp,
	"awakeningap":                   StatIdAwakeningAp,
	"totalap":                       StatIdTotalAp,
	"totalawakeningap":              StatIdTotalAwakeningAp,
	"bracketap":                     StatIdBracketAp,
	"bracketawakeningap":            StatIdBracketAwakeningAp,
	"bracketmonsterap":              StatIdBracketMonsterAp,
	"bracketmonsterawakeningap":     StatIdBracketMonsterAwakeningAp,
	"apvsmonster":                   StatIdApVsMonster,
	"apvsadventurer":                StatIdApVsAdventurer,
	"apvshuman":                     StatIdApVsHuman,
	"apvsdemihuman":                 StatIdApVsDemihuman,
	"apvskamasylvian":               StatIdApVsKamasylvian,
	"apvsedania":                    StatIdApVsEdania,
	"apvsnormal":                    StatIdApVsNormal,
	"awakeningapvsmonster":          StatIdAwakeningApVsMonster,
	"awakeningapvsadventurer":       StatIdAwakeningApVsAdventurer,
	"awakeningapvshuman":            StatIdAwakeningApVsHuman,
	"awakeningapvsdemihuman":        StatIdAwakeningApVsDemihuman,
	"awakeningapvskamasylvian":      StatIdAwakeningApVsKamasylvian,
	"awakeningapvsedania":           StatIdAwakeningApVsEdania,
	"awakeningapvsnormal":           StatIdAwakeningApVsNormal,
	"normalap":                      StatIdNormalAp,
	"edaniaap":                      StatIdEdaniaAp,
	"beastap":                       StatIdBeastAp,
	"damagereduction":               StatIdDamageReduction,
	"totaldamagereduction":          StatIdTotalDamageReduction,
	"hiddendamagereduction":         StatIdHiddenDamageReduction,
	"monsterdamagereduction":        StatIdMonsterDamageReduction,
	"monsterdamagereductionrate":    StatIdMonsterDamageReductionRate,
	"meleemonsterdamagereduction":   StatIdMeleeMonsterDamageReduction,
	"rangedmonsterdamagereduction":  StatIdRangedMonsterDamageReduction,
	"magicmonsterdamagereduction":   StatIdMagicMonsterDamageReduction,
	"hiddenmeleedamagereduction":    StatIdHiddenMeleeDamageReduction,
	"hiddenrangeddamagereduction":   StatIdHiddenRangedDamageReduction,
	"hiddenmagicdamagereduction":    StatIdHiddenMagicDamageReduction,
	"evasion":                       StatIdEvasion,
	"hiddenevasion":                 StatIdHiddenEvasion,
	"evasionrate":                   StatIdEvasionRate,
	"meleeevasionrate":              StatIdMeleeEvasionRate,
	"rangedevasionrate":             StatIdRangedEvasionRate,
	"magicevasionrate":              StatIdMagicEvasionRate,
	"hiddenmeleeevasion":            StatIdHiddenMeleeEvasion,
	"hiddenrangedevasion":           StatIdHiddenRangedEvasion,
	"hiddenmagicevasion":            StatIdHiddenMagicEvasion,
	"grappleresistance":             StatIdGrappleResistance,
	"airattackdamage":               StatIdAirAttackDamage,
	"counterattackdamage":           StatIdCounterAttackDamage,
	"speedattackdamage":             StatIdSpeedAttackDamage,
	"farmingmastery":                StatIdFarmingMastery,
	"tradingmastery":                StatIdTradingMastery,
	"filteringmastery":              StatIdFilteringMastery,
	"dryingmastery":                 StatIdDryingMastery,
	"grindingmastery":               StatIdGrindingMastery,
	"heatingmastery":                StatIdHeatingMastery,
	"choppingmastery":               StatIdChoppingMastery,
	"shakingmastery":                StatIdShakingMastery,
	"maxresource":                   StatIdMaxResource,
	"maxstamina":                    StatIdMaxStamina,
	"apmin":                         StatIdApMin,
	"apmax":                         StatIdApMax,
	"awakeningapmin":                StatIdAwakeningApMin,
	"awakeningapmax":                StatIdAwakeningApMax,
	"critlevel":                     StatIdCritLevel,
	"critchance":                    StatIdCritChance,
	"fishingspeed":                  StatIdFishingSpeed,
	"attackspeedlevel":              StatIdAttackSpeedLevel,
	"castingspeedlevel":             StatIdCastingSpeedLevel,
	"movementspeedlevel":            StatIdMovementSpeedLevel,
	"gatheringspeed":                StatIdGatheringSpeed,
	"workerstaminarecovery":         StatIdWorkerStaminaRecovery,
}

// Values returns every declared value in declaration order.
func (c StatIdContainer) Values() []StatId {
	out := make([]StatId, len(statIdValues))
	copy(out, statIdValues)
	return out
}

// Infos returns every declared value's metadata in declaration order.
func (c StatIdContainer) Infos() []StatIdInfo {
	out := make([]StatIdInfo, len(statIdValues))
	for i, v := range statIdValues {
		out[i] = statIdInfos[v]
	}
	return out
}

// Len returns the number of declared values.
func (c StatIdContainer) Len() int {
	return len(statIdValues)
}

// All iterates every declared value in declaration order.
func (c StatIdContainer) All() iter.Seq[StatId] {
	return func(yield func(StatId) bool) {
		for _, v := range statIdValues {
			if !yield(v) {
				return
			}
		}
	}
}

// FromWire converts a raw wire value, reporting whether it is declared.
func (c StatIdContainer) FromWire(w string) (StatId, bool) {
	v := StatId(w)
	_, ok := statIdInfos[v]
	return v, ok
}

// FromWireUnsafe converts a raw wire value, assuming it's declared.
func (c StatIdContainer) FromWireUnsafe(w string) StatId {
	return StatId(w)
}

// Parse resolves a value by name, case-insensitively.
func (c StatIdContainer) Parse(s string) (StatId, error) {
	if v, ok := statIdByName[strings.ToLower(strings.TrimSpace(s))]; ok {
		return v, nil
	}
	var zero StatId
	return zero, fmt.Errorf("unknown StatId: %q", s)
}

// TryGetInfo returns the metadata for v, and whether v is a declared value.
func (v StatId) TryGetInfo() (StatIdInfo, bool) {
	i, ok := statIdInfos[v]
	return i, ok
}

// Info returns the metadata for v, and whether v is a declared value.
func (v StatId) Info() StatIdInfo {
	return statIdInfos[v]
}

func (v StatId) Valid() bool {
	_, ok := statIdInfos[v]
	return ok
}

func (v StatId) Wire() string {
	return string(v)
}

func (v StatId) Name() string {
	return statIdInfos[v].Name
}

func (v StatId) String() string {
	if i, ok := statIdInfos[v]; ok {
		return i.Name
	}
	return fmt.Sprintf("StatId(%q)", string(v))
}

func (v StatId) Label() string {
	return statIdInfos[v].Label
}

func (v StatId) Category() string {
	return statIdInfos[v].Category
}

func (v StatId) Alias() string {
	return statIdInfos[v].Alias
}

func (v StatId) Fanout() []StatId {
	return statIdInfos[v].Fanout
}

func (v StatId) Unit() string {
	return statIdInfos[v].Unit
}

func (v StatId) Cap() int {
	return statIdInfos[v].Cap
}
